#Path to the location where the project is
 path_project: "C:\\PTC_Project\\eCS"

#Path where the output file with the result is
 output_path: "..\\Outputs"

#Select the positions where the column for the rom code, data and data abs starts and ends for the Application file
 app_rom_ro_code_start: 47
 app_rom_ro_code_end: 55
 app_rom_ro_data_start: 65
 app_rom_ro_data_end: 73
 app_rom_ro_data_abs_start: 83
 app_rom_ro_data_abs_end: 91

#Select the positions where the column for the ram code, data and data abs starts and ends for the Application file
 app_ram_rw_code_start: 56
 app_ram_rw_code_end: 64
 app_ram_rw_data_start: 74
 app_ram_rw_data_end: 82
 app_ram_rw_data_abs_start: 92
 app_ram_rw_data_abs_end: 100

#Select the positions where the column for the rom code and data starts and ends for the Bootmanager file
 fbm_rom_ro_code_start: 20
 fbm_rom_ro_code_end: 28
 fbm_rom_ro_data_start: 29
 fbm_rom_ro_data_end: 38

#Select the positions where the column for the ram code and data starts and ends for the Bootmanager file
 fbm_ram_rw_data_start: 38
 fbm_ram_rw_data_end: 46

#Select the positions where the column for the rom code and data starts and ends for the Bootloader file
 fbl_rom_ro_code_start: 34
 fbl_rom_ro_code_end: 46
 fbl_rom_ro_data_start: 47
 fbl_rom_ro_data_end: 55

#Select the positions where the column for the ram code and data starts and ends for the Bootloader file
 fbl_ram_rw_data_start: 56
 fbl_ram_rw_data_end: 64

#List of directors to ignore for the Application
 list_of_app_director_to_ignor:
   - .git
   - Bootloader
   - Bootloader_updater
   - Bootmanager
   - Architectures
   - Scripts
   - Design
   - Build_Env
   - unittest
   - sources
   - Quality_Assurance
   - EB_Bootloader
   - MBD
   - Tresos_configuration_Bootloader
   - templates
   - BootManager
   - Deliveries
   - Release
   - EB_BSW_8.8.7

#List of directors to ignore for the Bootloader
 list_of_fbl_director_to_ignor:
   - .git
   - Application
   - Bootloader_updater
   - Bootmanager
   - Architectures
   - Scripts
   - Design
   - Build_Env
   - unittest
   - sources
   - Quality_Assurance
   - EB_Bootloader
   - MBD
   - Tresos_configuration_Bootloader
   - templates
   - BootManager
   - Deliveries
   - Release
   - EB_BSW_8.8.7

#List of directors to ignore for the Bootmanager
 list_of_fbm_director_to_ignor:
   - .git
   - Application
   - Bootloader_updater
   - Bootloader
   - Architectures
   - Scripts
   - Design
   - Build_Env
   - unittest
   - sources
   - Quality_Assurance
   - EB_Bootloader
   - MBD
   - Tresos_configuration_Bootloader
   - templates
   - BootManager
   - Deliveries
   - Release
   - EB_BSW_8.8.7

 #Parameter for Grand total RAM and ROM Consumption for Application
 ram_consumption_app_excel: =A7/(60*1024)
 rom_consumption_app_excel: =B7/(524288)

 #Parameter for Grand total RAM and ROM Consumption for Bootloader
 ram_consumption_fbl_excel: =C7/(60*1024)
 rom_consumption_fbl_excel: =D7/(524288)

 #Parameter for Grand total RAM and ROM Consumption for Bootlmanager
 ram_consumption_fbm_excel: =E7/(60*1024)
 rom_consumption_fbm_excel: =F7/(524288)