document_name: "Exxxxxxx DAIMLER MMA CM Items Status PTC" # no extension required

# no project label
#ptc_label = ""
# project label example
#ptc_label = "--projectRevision=VW_SBE_PP4G_TR6_P030_P30_DEV"

ptc_label: ""

application_path:
    - "s:/Components/Application/Autoliv/"

ptc_project_stems:
    - "e:/MKSProjects/SBE/PP/DAIMLER_MMA/Phase_02/View_Development/Components/Application/Autoliv/{}/Implementation/project.pj"
    - "e:/MKSProjects/SBE/PP/DAIMLER_MMA/Phase_02/View_Development/Components/Application/Autoliv/{}/Design/project.pj"
    - "e:/MKSProjects/SBE/PP/DAIMLER_MMA/Phase_02/View_Development/Components/Application/Autoliv/{}/Quality_Assurance/Peer_Review/project.pj"
    - "e:/MKSProjects/SBE/PP/DAIMLER_MMA/Phase_02/View_Development/Components/Application/Autoliv/{}/Quality_Assurance/Static_Analysis/project.pj"
    - "e:/MKSProjects/SBE/PP/DAIMLER_MMA/Phase_02/View_Development/Components/Application/Autoliv/{}/Tests/project.pj"

arch_application_paths:
    - "s:/Architectures/Application/Description/Associated_Documents/"
    - "s:/Architectures/Application/Description/"

arch_project_stems:
    - "e:/MKSProjects/SBE/PP/DAIMLER_MMA/Phase_02/View_Development/Architectures/Application/Description/project.pj"
    - "e:/MKSProjects/SBE/PP/DAIMLER_MMA/Phase_02/View_Development/Architectures/Application/Description/Associated_Documents/project.pj"

main_document_architecture: "DAIMLER_MMA_SWarchitectureDesignInterfaceDescription.docx"