/**************************************************************************************************\
 *** 
 *** Simulink model       : PRO_TestHarness
 *** TargetLink subsystem : PRO_TestHarness/PRO_AC_ProductionCycles
 *** Codefile             : PRO_AC_ProductionCycles.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-26 08:25:26
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      PRO_AC_ProductionCycles
 *** Sa2                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles
 *** Sa3                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s
 *** Sa4                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/WriteSystemContextOutp
 ***                          uts
 *** Sa5                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/Dem_GetEventStatus
 *** Sa5                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/Dem_GetEventStatus1
 *** Sa6                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/Flags_PRO1
 *** Sa7                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/Flags_PRO2
 *** Sa8                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/PRO enabled
 *** Sa5                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/SCA_runCheckSystemContext1
 *** Sa5                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/SCA_runCheckSystemContext2
 *** Sa9                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/PRO enabled/FctCommonPROManageInputs
 *** Sa10                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/PRO enabled/FctTrigAbortCycle_AllPRO
 *** Sa11                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCheckUnderVoltageDuringTensi
 ***                          oningForAllPRO
 *** Sa12                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluateAbortionCondit
 ***                          ions
 *** Sa13                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluatePreActivationF
 ***                          lags
 *** Sa14                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluatePreConditions
 *** Sa15                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCheckUnderVoltageDuringTensi
 ***                          oningForAllPRO/For IteratorSubsystem
 *** Sa16                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluatePreActivationF
 ***                          lags/For IteratorSubsystem
 *** Sa17                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluatePreActivationF
 ***                          lags/For IteratorSubsystem/FctEvaluatePreActivationFlags_PRO
 *** Sa18                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluatePreActivationF
 *** lags/For IteratorSubsystem/FctEvaluatePreActivationFlags_PRO/Acquite D
 ***                          iag Request From DIA
 *** Sa19                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluatePreActivationF
 *** lags/For IteratorSubsystem/FctEvaluatePreActivationFlags_PRO/Clear act
 ***                          ivation
 *** Sa20                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluatePreActivationF
 *** lags/For IteratorSubsystem/FctEvaluatePreActivationFlags_PRO/Keep acti
 ***                          vation
 *** Sa21                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluatePreActivationF
 *** lags/For IteratorSubsystem/FctEvaluatePreActivationFlags_PRO/Set activ
 ***                          ation
 *** Sa22                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctCommonPROManageInputs/FctCommonEvaluatePreActivationF
 *** lags/For IteratorSubsystem/FctEvaluatePreActivationFlags_PRO/Acquite D
 ***                          iag Request From DIA/ClearDiagRequestCycle
 *** Sa23                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem
 *** Sa24                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO
 *** Sa25                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Switch Ca
 ***                          se ActionSubsystem
 *** Sa26                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Switch Ca
 ***                          se ActionSubsystem1
 *** Sa27                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Switch Ca
 ***                          se ActionSubsystem2
 *** Sa28                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctAbort_PRO
 *** Sa29                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO
 *** Sa30                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctAbort_PRO/Check end diag request for PRO
 *** Sa31                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctAbort_PRO/ToFormatFlag_bInterruptFlag
 *** Sa32                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 *** FctAbort_PRO/Check end diag request for PRO/Acquite end of diag reques
 ***                          t
 *** Sa33                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctAbort_PRO/Check end diag request for PRO/End of diag request
 *** Sa34                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 *** FctAbort_PRO/Check end diag request for PRO/Memorize end of diag reque
 ***                          st
 *** Sa35                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctAbort_PRO/ToFormatFlag_bInterruptFlag/If ActionSubsystem4
 *** Sa36                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctAbort_PRO/ToFormatFlag_bInterruptFlag/If ActionSubsystem5
 *** Sa37                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormatFlag_PreActivationFlag
 *** Sa38                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormatFlag_PreConditionsFlag
 *** Sa39                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormatFlag_TriggeringOrder
 *** Sa40                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormat_TriggeringSource
 *** Sa41                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormatFlag_PreActivationFlag/If ActionSubsystem
 *** Sa42                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormatFlag_PreActivationFlag/If ActionSubsystem1
 *** Sa43                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormatFlag_PreConditionsFlag/If ActionSubsystem4
 *** Sa44                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormatFlag_PreConditionsFlag/If ActionSubsystem5
 *** Sa45                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormatFlag_TriggeringOrder/If ActionSubsystem
 *** Sa46                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormatFlag_TriggeringOrder/If ActionSubsystem1
 *** Sa47                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormat_TriggeringSource/None
 *** Sa48                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 *** s/PRO enabled/FctTrigAbortCycle_AllPRO/For IteratorSubsystem/Algo PRO/
 ***                          FctTrigg_PRO/ToFormat_TriggeringSource/Tester
 *** Sa9                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/SCA_runCheckSystemContext1/If ActionSubsystem1
 *** Sa10                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/SCA_runCheckSystemContext1/If ActionSubsystem2
 *** Sa9                      PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/SCA_runCheckSystemContext2/If ActionSubsystem1
 *** Sa10                     PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycle
 ***                          s/SCA_runCheckSystemContext2/If ActionSubsystem2
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef PRO_AC_PRODUCTIONCYCLES_C
#define PRO_AC_PRODUCTIONCYCLES_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte.h"
#include "PRO_AC_ProductionCycles_ARfrm.h"
#include "PRO_AC_ProductionCycles.h"
#include "common.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 16
\******************************************************************************/
sint16 Sa1_u8RequestedCycle;
sint16 Sa1_u8Status_OverVoltage;
sint16 Sa1_u8Status_UVDuringTensioning;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
uint8 Sa1_b8DTCAbortion;
uint8 Sa1_b8DTCInhibition;
uint8 Sa1_u8ExecutedCycle;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: N.A.
\******************************************************************************/
struct BS_OP_Sa1_psrAlgoFlags_PRO1 Sa1_psrAlgoFlags_PRO1;

struct BS_OP_Sa1_psrAlgoFlags_PRO2 Sa1_psrAlgoFlags_PRO2;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      PRO_AC_ProductionCycles
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void PRO_AC_ProductionCycles(void)
{
   /* Data store write: PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/WriteSystemContextOutputs/Da
      ta Store Write5 */
   u8Status_OVO = (uint8) Sa1_u8Status_OverVoltage;

   /* Data store write: PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/WriteSystemContextOutputs/Da
      ta Store Write4 */
   u8Status_UVT = (uint8) Sa1_u8Status_UVDuringTensioning;

   /* Data store write: PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/WriteSystemContextOutputs/Da
      ta Store Write2 */
   b8CyclesAbortedByDTC = Sa1_b8DTCAbortion;

   /* Data store write: PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/WriteSystemContextOutputs/Da
      ta Store Write1 */
   b8CyclesInhibitedByDTC = Sa1_b8DTCInhibition;

   /* update(s) for inport PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycles/u
      8ExecutedCycle */
   Rte_PRO_AC_ProductionCycles_prrExecutedCycle_u8CycleNumber = Sa1_u8ExecutedCycle;

   /* update(s) for inport PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycles/u
      8RequestedCycle */
   Rte_PRO_AC_Pro__iagRequestCycle = (uint8) Sa1_u8RequestedCycle;

   /* call of function: PRO_AC_ProductionCycles/PRO_AC_ProductionCycles/PRO_runProductionCycles */
   Task_PRO_runPr__nCycles_Wrapper();

   /* BusOutport: PRO_AC_ProductionCycles/psrAlgoFlags_PRO2 */
   Sa1_psrAlgoFlags_PRO2.Sa1_b8TriggerFlag_PRO2 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO2_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRO2.Sa1_b8InterruptFlag_PRO2 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO2_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRO2.Sa1_b8ActivationFlag_PRO2 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO2_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRO2.Sa1_b8PreConditionsFlag_PRO2 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO2_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRO2.Sa1_u8TriggeringSource_PRO2 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO2_u8TriggeringSource;

   /* BusOutport: PRO_AC_ProductionCycles/psrAlgoFlags_PRO1 */
   Sa1_psrAlgoFlags_PRO1.Sa1_b8TriggerFlag_PR01 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO1_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRO1.Sa1_b8InterruptFlag_PRO1 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO1_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRO1.Sa1_b8PreActivationFlag_PRO1 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO1_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRO1.Sa1_b8PreConditionsFlag_PRO1 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO1_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRO1.Sa1_u8TriggeringSource_PRO1 = (sint16)
    Rte_PRO_AC_ProductionCycles_psrAlgo_Flags_PRO1_u8TriggeringSource;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* PRO_AC_PRODUCTIONCYCLES_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
