/****************************************************************************************************************************************************\
 *** 
 *** Simulink model       : BFE_TestHarness
 *** TargetLink subsystem : BFE_TestHarness/BFE_AC_BeltFunctionExecution
 *** Codefile             : BFE_AC_BeltFunctionExecution_lut.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-04-17 16:56:17
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 150
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Config\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      BFE_AC_BeltFunctionExecution
 *** Sa2                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution
 *** Sa3                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteEmergencyBrakingSequence
 *** Sa4                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep
 *** Sa5                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps
 *** Sa6                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runResetMotorStageStatus
 *** Sa7                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep
 *** Sa8                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables
 *** Sa9                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/Switch Case ActionSubsystem
 *** Sa10                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteEmergencyBrakingSequence/ANG regulation
 *** Sa11                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteEmergencyBrakingSequence/Idle State
 *** Sa12                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteEmergencyBrakingSequence/ANG regulation/If Actio
 ***                          nSubsystem1
 *** Sa13                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteEmergencyBrakingSequence/ANG regulation/Product
 *** Sa14                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteEmergencyBrakingSequence/ANG regulation/Src
 *** Sa15                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteEmergencyBrakingSequence/Idle State/If ActionSub
 ***                          system
 *** Sa16                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteEmergencyBrakingSequence/Idle State/Src
 *** Sa17                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated
 *** Sa18                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion
 *** Sa19                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/IsNewCycle
 *** Sa20                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/BoostInterruptConditions_MotorCurrent
 *** Sa21                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/BoostInterruptConditions_Timing
 *** Sa22                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/CalculateIntegerInit
 *** Sa23                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/CalculateSintegerMaxInit
 *** Sa24                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/Calculate_MotorPowerOrder
 *** Sa25                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/Consign rescaling
 *** Sa26                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/If ActionSubsystem1
 *** Sa27                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/Limit_Integer
 *** Sa28                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/ManageTimer
 *** Sa29                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/PerformRegulation
 *** Sa30                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/SlowBoostDecrease
 *** Sa31                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/SupplyCurrent
 *** Sa32                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/SupplyCurrent/Drift_Compensation
 *** Sa33                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteHighPowerStep/HP feature activated/CurrentRegula
 ***                          tion/SupplyCurrent/RescaleMotorMeasure
 *** Sa34                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps
 *** Sa35                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/Mange Power S
 ***                          tage consign update
 *** Sa36                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower
 *** Sa37                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemUpda
 ***                          teConsigns
 *** Sa38                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/Mange Power S
 ***                          tage consign update/Call PAL service to update the PWM
 *** Sa39                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/Mange Power S
 ***                          tage consign update/Resume ISR
 *** Sa40                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/Mange Power S
 ***                          tage consign update/Suspend ISR
 *** Sa41                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/Mange Power S
 ***                          tage consign update/Call PAL service to update the PWM/Apply power order
 *** Sa42                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/Mange Power S
 ***                          tage consign update/Call PAL service to update the PWM/Apply power order/If ActionSubsystem
 *** Sa43                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation
 *** Sa44                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Init_Error_Calculation
 *** Sa45                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/ManageIntegerErrorReset
 *** Sa46                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/MotorVoltage_Regulation
 *** Sa47                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/No_Regulation
 *** Sa48                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/PWM_Regulation
 *** Sa49                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/RescaleOrderType
 *** Sa50                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation
 *** Sa51                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation
 *** Sa52                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature disabled
 *** Sa53                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled
 *** Sa54                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/DecidePID_Type
 *** Sa55                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/Limit_Integer_Action
 *** Sa56                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/No_PID
 *** Sa57                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/Operation_Motor
 *** Sa58                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/Operation_Supply
 *** Sa59                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/Rescale Current consign1lsb = 50mA
 *** Sa60                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/RescaleMotorMeasure1A = 20lsb
 *** Sa61                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/DecidePID_Type/LastPIDType
 *** Sa62                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/DecidePID_Type/MotorPID
 *** Sa63                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/DecidePID_Type/SupplyPID
 *** Sa64                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/Operation_Motor/Product10
 *** Sa65                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/PID Regulation/PID feature enabled/Operation_Supply/Product10
 *** Sa66                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Current regulation algo
 *** Sa67                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Init of current regulation for a new cycle
 *** Sa68                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Product10
 *** Sa69                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Rescale Current consign1lsb = 50mA
 *** Sa70                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/RescaleMotorMeasure1lsb = 50mA
 *** Sa71                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Current regulation algo/If ActionSubsystem
 *** Sa72                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Current regulation algo/If ActionSubsystem1
 *** Sa73                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Current regulation algo/If ActionSubsystem2
 *** Sa74                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Current regulation algo/If ActionSubsystem3
 *** Sa75                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Current regulation algo/If ActionSubsystem4
 *** Sa76                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/Current_Regulation/Standard Regulation/Current regulation algo/ProtectAgainstSignChange
 *** Sa77                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/MotorVoltage_Regulation/Battery voltage rescaling
 *** Sa78                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/MotorVoltage_Regulation/Consign < Battery voltage => Compute PWM
 *** Sa79                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/MotorVoltage_Regulation/Consign > Battery voltage => Saturate to MAX PWM
 *** Sa80                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/RescaleOrderType/If ActionSubsystem
 *** Sa81                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/RescaleOrderType/If ActionSubsystem1
 *** Sa82                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/RescaleOrderType/If ActionSubsystem/8Bit Decoder
 *** Sa83                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemConv
 ***                          ertOrderToMotorPower/RescaleOrderType/If ActionSubsystem1/8Bit Decoder
 *** Sa84                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runExecuteStandardSteps/ExecuteStandardSteps/SubsystemUpda
 ***                          teConsigns/SubsystemDetectConsignsChange
 *** Sa85                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runResetMotorStageStatus/Src
 *** Sa86                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core
 *** Sa87                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/Critical section for outputs to protect ag
 ***                          ainst ISR access
 *** Sb1                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step1
 *** Sa88                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step2
 *** Sa89                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112
 *** Sa90                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_113
 *** Sa91                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution
 *** Sc1                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep
 *** Sb2                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step1/No Step to play
 *** Sb3                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step1/Select Step To Exe
 ***                          cute
 *** Sb4                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step1/Select Step To Exe
 ***                          cute/Continue Step execution
 *** Sb5                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step1/Select Step To Exe
 ***                          cute/Filter StepId to Execute
 *** Sb6                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step1/Select Step To Exe
 ***                          cute/Increment Step Index
 *** Sb7                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step1/Select Step To Exe
 ***                          cute/Init Step Id
 *** Sa92                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step2/All is good
 *** Sa93                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step2/Free wheel phase
 *** Sa94                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step2/Invalid step
 *** Sa95                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_111 step2/no selected cycle 
 ***                          ORno step to execute
 *** Sa96                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Invalid Range for inputs
 *** Sa97                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters
 *** Sa98                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Preliminary Checks for S
 ***                          tep Parameters Content
 *** Sa99                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters
 *** Sa100                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/K
 ***                          eepPreviousValues
 *** Sa101                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/8Bit Decoder
 *** Sa102                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/8Bit Decoder1
 *** Sa103                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/8Bit Decoder2
 *** Sa104                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/Manage Current Regulation Type
 *** Sa105                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/Manage HES monitoring
 *** Sa106                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/Manage Release Controlled Option
 *** Sa107                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/Subsystem6
 *** Sa108                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/Manage Current Regulation Type/HP
 *** Sa109                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/Manage Current Regulation Type/PID battery
 *** Sa110                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/Manage Current Regulation Type/PID motor
 *** Sa111                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_112/Manage Step Parameters/E
 ***                          xtractParameters/Manage Current Regulation Type/Standard Current regulation
 *** Sa112                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_113/Keep last values
 *** Sa113                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_113/New cycle is started
 *** Sa114                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_113/New cycle is started/8Bi
 ***                          t Decoder
 *** Sa115                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_113/New cycle is started/NOT
 ***                           Power Degradable Belt Function
 *** Sa116                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_113/New cycle is started/Pow
 ***                          er Degradable Belt Function
 *** Sa117                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/Extr
 ***                          apolate Next Consign
 *** Sa118                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/Mana
 ***                          geTimer
 *** Sa119                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started
 *** Sa120                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/No s
 ***                          tep executed
 *** Sa121                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/Step
 ***                           execution continues
 *** Sa122                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/Extr
 ***                          apolate Next Consign/SubsystemDetectConsignsChange
 *** Sa123                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value
 *** Sa124                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType
 *** Sa125                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Ramp step characteristics computation
 *** Sa126                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/RescaleStepDuration
 *** Sa127                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/No TemperatureAdaptation
 *** Sa128                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/Temperature Weighted
 *** Sa129                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/Temperature Weighted/Step Order Negative
 *** Sa130                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/Temperature Weighted/Step Order Positive
 *** Sa131                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/Temperature Weighted/Step Order equal 0
 *** Sa132                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/Temperature Weighted/Step Order Positive/Switch Case ActionSubsystem
 *** Sa133                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/Temperature Weighted/Step Order Positive/Switch Case ActionSubsystem1
 *** Sa134                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/Temperature Weighted/Step Order Positive/Switch Case ActionSubsystem2
 *** Sa135                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/Temperature Weighted/Step Order Positive/Switch Case ActionSubsystem3
 *** Sa136                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Adapt Step Target Value/Temperature Weighted/Step Order Positive/Switch Case ActionSubsystem4
 *** Sa137                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem
 *** Sa138                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem1
 *** Sa139                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem2
 *** Sa140                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem
 *** Sa141                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem1
 *** Sa142                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem2
 *** Sa143                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem3
 *** Sa144                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem/If ActionSubsystem
 *** Sa145                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem/If ActionSubsystem1
 *** Sa146                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem1/If ActionSubsystem
 *** Sa147                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem1/If ActionSubsystem1
 *** Sa148                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem2/If ActionSubsystem
 *** Sa149                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/AdaptOrderType/If ActionSubsystem/If ActionSubsystem2/If ActionSubsystem1
 *** Sa150                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Ramp step characteristics computation/If ActionSubsystem
 *** Sa151                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Ramp step characteristics computation/If ActionSubsystem1
 *** Sa152                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ControlStepExecution/New 
 ***                          Step started/Ramp step characteristics computation/If ActionSubsystem2
 *** Sc2                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/No step 
 ***                          running
 *** Sc3                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress
 *** Sc4                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageAdaptiveCurrentInterruptionPoint(Comfort Belt Functions)
 *** Sc5                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageBeltBlocked(HES sensors)
 *** Sc6                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageBeltMvtDetection(HES sensors)
 *** Sc7                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageBeltPayOutAbortion
 *** Sc8                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageMotorBlocked(Motor OverCurrent)
 *** Sc9                      BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageTriggOff(end of holding steps)
 *** Sc10                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageAdaptiveCurrentInterruptionPoint(Comfort Belt Functions)/Current Int Point Opt Activated
 *** Sc11                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageAdaptiveCurrentInterruptionPoint(Comfort Belt Functions)/Current Int Point Opt Deactivated
 *** Sc12                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageBeltBlocked(HES sensors)/Belt Blocked Opt Activated
 *** Sc13                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageBeltBlocked(HES sensors)/Belt Blocked Opt Deactivated
 *** Sc14                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageBeltMvtDetection(HES sensors)/Belt Mvt Detect Opt Activated
 *** Sc15                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageBeltMvtDetection(HES sensors)/Belt Mvt Detect Opt Deactivated
 *** Sc16                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageBeltPayOutAbortion/Belt Payout Abortion Opt Activated
 *** Sc17                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageBeltPayOutAbortion/Belt Payout Abortion Opt Deactivated
 *** Sc18                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Activated
 *** Sc19                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Deactivated
 *** Sc20                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Activated/If ActionSubsystem
 *** Sc21                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Activated/If ActionSubsystem1
 *** Sc22                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 *** cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Activated/If ActionSubsystem1/GetBoardResista
 ***                          nce
 *** Sc23                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 *** cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Activated/If ActionSubsystem1/GetMotorResista
 ***                          nce
 *** Sc24                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 *** cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Activated/If ActionSubsystem1/Integratorwith 
 ***                          u8 saturation
 *** Sc25                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 *** cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Activated/If ActionSubsystem1/Integratorwith 
 ***                          u8 saturation/If ActionSubsystem1
 *** Sc26                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 *** cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Activated/If ActionSubsystem1/Integratorwith 
 ***                          u8 saturation/Reset Counter 2
 *** Sc27                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 *** cution in progress/ManageMotorBlocked(Motor OverCurrent)/Motor Blocked Opt Activated/If ActionSubsystem1/Integratorwith 
 ***                          u8 saturation/Reset counter
 *** Sc28                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageTriggOff(end of holding steps)/TriggOff Opt Activated
 *** Sc29                     BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_Core/TF_G_12_ManageEndingStep/Step exe
 ***                          cution in progress/ManageTriggOff(end of holding steps)/TriggOff Opt Deactivated
 *** Sa153                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/Critical section for outputs to protect ag
 ***                          ainst ISR access/Switch Case ActionSubsystem
 *** Sa154                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/Critical section for outputs to protect ag
 ***                          ainst ISR access/Switch Case ActionSubsystem1
 *** Sa155                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/Critical section for outputs to protect ag
 ***                          ainst ISR access/Switch Case ActionSubsystem2
 *** Sa156                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/Critical section for outputs to protect ag
 ***                          ainst ISR access/Switch Case ActionSubsystem3
 *** Sa157                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables/If ActionSubsystem
 *** Sa158                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables/If ActionSubsystem1
 *** Sa159                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables/If ActionSubsystem2
 *** Sa160                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables/If ActionSubsystem3
 *** Sa161                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables/If ActionSubsystem/If ActionSubsystem
 *** Sa162                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables/If ActionSubsystem1/If ActionSubsystem
 *** Sa163                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables/If ActionSubsystem2/If ActionSubsystem1
 *** Sa164                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables/If ActionSubsystem2/If ActionSubsystem2
 *** Sa165                    BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/ManageRunnables/If ActionSubsystem3/If ActionSubsystem1
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE         CORRESPONDING STATEFLOW NODE                                                       DESCRIPTION
 *** Ca0             LIB_TF_G_12_StepControl                                                            
 *** Ca1             BFE_AC_BeltFunctionExecution/BFE_AC_BeltFunctionExecution/BFE_runScheduleStep/BFE_
 ***                 Core/TF_G_12_ControlStepExecution/ChartManageLatencyTimer                          
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\****************************************************************************************************************************************************/

#ifndef BFE_AC_BELTFUNCTIONEXECUTION_LUT_C
#define BFE_AC_BELTFUNCTIONEXECUTION_LUT_C

/*------------------------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------------------------*/

#include "BFE_AC_BeltFunctionExecution_lut.h"

/*------------------------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------------------------*/

/****************************************************************************************************************************************************\
 ***  FUNCTION:
 ***      Tab1DS0I2T2081_a
 *** 
 ***  DESCRIPTION:
 ***      Generated function for look-up tables.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_Tab1DS0I2T2081_a *map                 data structure
 ***      uint16             x                   table input
 ***
 ***  RETURNS:
 ***      sint16
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: linear search, start low
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***      Behavior at boundaries.............: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***
\****************************************************************************************************************************************************/
sint16 Tab1DS0I2T2081_a(const MAP_Tab1DS0I2T2081_a * map, uint16 x)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   sint16 Aux_S16;
   sint16 Aux_S16_a;
   uint16 Aux_U16;
   uint16 Aux_U16_a;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const uint16 * x_table; /* Scaling may differ through function reuse. */
   const sint16 * z_table; /* Scaling may differ through function reuse. */

   x_table = map->x_table;
   z_table = map->z_table;
   if (x <= *x_table) {
      /* Saturation. */
      return z_table[0];
   }
   if (x >= x_table[(uint8) (map->Nx - 1)]) {
      return z_table[(uint8) (map->Nx - 1)];
   }

   /* Linear search, start low. */
   x_table++;
   while (x > *(x_table++)) {
      z_table++;
   }
   x_table -= 2;
   Aux_S16 = *(z_table++);
   Aux_S16_a = *z_table;

   /* Interpolation. */
   Aux_U16 = (uint16) (x - x_table[0]);
   Aux_U16_a = (uint16) (x_table[1] - x_table[0]);
   if (Aux_S16 <= Aux_S16_a) {
      /* Positive slope. */
      Aux_S16 += ((sint16) (uint16) ((((uint32) (uint16) (((uint16) Aux_S16_a) - ((uint16) Aux_S16))) * ((uint32) Aux_U16)) / Aux_U16_a));
   }
   else {
      /* Negative slope. */
      Aux_S16 -= ((sint16) (uint16) ((((uint32) (uint16) (((uint16) Aux_S16) - ((uint16) Aux_S16_a))) * ((uint32) Aux_U16)) / Aux_U16_a));
   }
   return Aux_S16;
}

/****************************************************************************************************************************************************\
 ***  FUNCTION:
 ***      Tab1DS0I2T1_a
 *** 
 ***  DESCRIPTION:
 ***      Generated function for look-up tables.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_Tab1DS0I2T1_a *map                 data structure
 ***      uint16             x                   table input
 ***
 ***  RETURNS:
 ***      uint8
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: linear search, start low
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***      Behavior at boundaries.............: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***
\****************************************************************************************************************************************************/
uint8 Tab1DS0I2T1_a(const MAP_Tab1DS0I2T1_a * map, uint16 x)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   uint16 Aux_U16;
   uint16 Aux_U16_a;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const uint16 * x_table; /* Scaling may differ through function reuse. */
   const uint8 * z_table; /* Scaling may differ through function reuse. */

   x_table = map->x_table;
   z_table = map->z_table;
   if (x <= *x_table) {
      /* Saturation. */
      return z_table[0];
   }
   if (x >= x_table[(uint8) (map->Nx - 1)]) {
      return z_table[(uint8) (map->Nx - 1)];
   }

   /* Linear search, start low. */
   x_table++;
   while (x > *(x_table++)) {
      z_table++;
   }
   x_table -= 2;

   /* Interpolation. */
   Aux_U16 = (uint16) (x - x_table[0]);
   Aux_U16_a = (uint16) (x_table[1] - x);
   return ((uint8) (((((uint32) Aux_U16) * ((uint32) z_table[1])) + (((uint32) Aux_U16_a) * ((uint32) z_table[0]))) / ((uint16) (Aux_U16 +
    Aux_U16_a))));
}

/*------------------------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------------------------*/
#endif /* BFE_AC_BELTFUNCTIONEXECUTION_LUT_C */
/*------------------------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------------------------*/
