/**************************************************************************************************\
 *** 
 *** Simulink model       : SFR_TestHarness
 *** TargetLink subsystem : SFR_TestHarness/SFR_AC_StandardFunctionRecovery
 *** Codefile             : SFR_Config.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-04-24 08:44:57
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef SFR_CONFIG_H
#define SFR_CONFIG_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "Rte_Type.h"
#include "NVP_Generated.h"
#include "Nvp_Cfg.h"

/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SFR_Config_Calibrations: Calibratable global variables, which are declared in a user-written head
   er file | Width: 8
\******************************************************************************/

/* NVP Timeout to replace smooth by hard release, after BSR only, if car acceleration still high */
#define CAL_KU16_SFR_NVP_HIGH_CAR_ACCELERATION_TIMEOUT       65535u

#define CAL_AU8_SFR_BELT_PROFILES_DEFINITIONS          NVP_BLOCK_ID_CYCLE_0_RamBlockData.NVP_au8BeltProfilesDefinitions
/*
   Description: 12 bytes x n cycles */

/* Position of the following cycle identifier in the cycle header */
#define CAL_KU8_SFR_NVP_FOLLOWING_CYCLE_ID             KU8_NVP_FOLLOWING_CYCLE_ID

/* Size of the NVP descriptor for one cycle */
#define CAL_KU8_SFR_SIZE_OF_NVP_CYCLE_BLOCK            KU8_NVP_CYCLE_SIZE

/* Configuration of the identifier of startup cycle */
#define CAL_KU8_SFR_ANTI_PATINA_CYCLE        KU8_BELT_FUNCTION_32

/* Configuration of the identifier of releasing cycles */
#define CAL_KU8_SFR_HARD_RELEASE_CYCLE       KU8_BELT_FUNCTION_30
#define CAL_KU8_SFR_SMOOTH_RELEASE_CYCLE     KU8_BELT_FUNCTION_29
#define CAL_KU8_SFR_BACKUP_RELEASE_CYCLE     KU8_BELT_FUNCTION_31

#define CAL_KU8_SFR_BSR_CYCLE                KU8_BELT_FUNCTION_26
/* Configure ERH interface */
#define CFG_KU8_SFR_HALL_EFFECT_SENSOR_INTERNAL_FAULT_ID  ERH_KU8_HALL_SENSOR_AEC_CFG
#define CFG_KU8_SFR_QUALIFIED_STATUS_MASK                 ERH_KU8_AEC_QUALIFIED_STATUS_MASK

/* Configure ATM interface */
#define CFG_KU8_SFR_HW_PROTECTION_TEST_ID                 ATM_KU8_ID_TEST_DRIVER_SELF_PROTECTION

/* Timeout to inhibit SFR after HW protection no more detected */
/* LSB = 10ms */
#define CFG_KU8_SFR_HW_PROTECTION_TIMEOUT_10MS            ((uint8) 100)

/* Masks to get MMG contexts */
#define CFG_KU32_SFR_MASK_ABORTING_MODES        (MMG_KU32_MASK_AEC_ECU_DEFECT_ALL_CYCLES)
#define CFG_KU32_SFR_MASK_INHIBITING_MODES      (MMG_KU32_MASK_CRITICAL_AT_NOK | MMG_KU32_MASK_AEC_INHIB_ALL_CYCLES | MMG_KU32_MASK_AEC_ECU_DEFECT_ALL_CYCLES|MMG_KU32_MASK_SIGNAL_RELEASE_INHIBITION)

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

#endif/*SFR_CONFIG_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
