/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2022 by Vector Informatik GmbH.                                              All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------*/
/*!        \file  Crypto_30_vHsm_Core.h
 *        \brief  Used to redirect function names generated by the CryIf
 *
 *      \details  -
 *
 *********************************************************************************************************************/

 /**********************************************************************************************************************
 *  REVISION HISTORY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Refer to the module's header file.
 *********************************************************************************************************************/

#if !defined (CRYPTO_30_VHSM_CORE_H)
# define CRYPTO_30_VHSM_CORE_H

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
# include "vHsm_Core.h"

/**********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS
 *********************************************************************************************************************/

# define Crypto_30_vHsm_Core_CancelJob                                vHsm_Core_CancelJob
# define Crypto_30_vHsm_Core_KeyElementGet                            vHsm_Core_KeyElementGet
# define Crypto_30_vHsm_Core_KeyElementSet                            vHsm_Core_KeyElementSet
# define Crypto_30_vHsm_Core_ProcessJob                               vHsm_Core_ProcessJob
# define Crypto_30_vHsm_Core_KeyValidSet                              vHsm_Core_KeyValidSet

/* Functions will always return E_NOT_OK because the functionality is not provided by the core driver. */
# define Crypto_30_vHsm_Core_CertificateParse                         vHsm_Core_CertificateParse
# define Crypto_30_vHsm_Core_CertificateVerify                        vHsm_Core_CertificateVerify
# define Crypto_30_vHsm_Core_KeyCopy                                  vHsm_Core_KeyCopy
# define Crypto_30_vHsm_Core_KeyDerive                                vHsm_Core_KeyDerive
# define Crypto_30_vHsm_Core_KeyElementCopy                           vHsm_Core_KeyElementCopy
# define Crypto_30_vHsm_Core_KeyElementCopyPartial                    vHsm_Core_KeyElementCopyPartial
# define Crypto_30_vHsm_Core_KeyElementIdsGet                         vHsm_Core_KeyElementIdsGet
# define Crypto_30_vHsm_Core_KeyExchangeCalcPubVal                    vHsm_Core_KeyExchangeCalcPubVal
# define Crypto_30_vHsm_Core_KeyExchangeCalcSecret                    vHsm_Core_KeyExchangeCalcSecret
# define Crypto_30_vHsm_Core_KeyGenerate                              vHsm_Core_KeyGenerate
# define Crypto_30_vHsm_Core_RandomSeed                               vHsm_Core_RandomSeed

/**********************************************************************************************************************
 *  GLOBAL FUNCTION MACROS
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA TYPES AND STRUCTURES
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA PROTOTYPES
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL FUNCTION PROTOTYPES
 *********************************************************************************************************************/

#endif /* CRYPTO_30_VHSM_CORE_H */

/**********************************************************************************************************************
 *  END OF FILE: Crypto_30_vHsm_Core.h
 *********************************************************************************************************************/
