# =========================================================================
#                     CONFIG FILE FOR Detail Design Generator
#   Written by: Ardeleanu Lucian
#   Date: 03 Feb. 2022
#   Copyright Autoliv, RBE, 2022
#   Status: Released
# ==========================================================================

# GENERAL PATHS USED IN SCRIPT

# Please provide here path to Application folder, where components are stored
# For example, on AUDI_TR6: S:\Components\Application
Path to Application Folder: 'C:\GIT_Projects\eCS_Platform_Git\Components\Application\Autoliv'

# Write here entity of data to be parsed. Type of data to analyse (functions/variables/defines/structures/all)
Data entity to parse: 'all'

# Write here component name to be analysed from Application folder upper defined
Component to be analysed: 'PwmIf'

# Path to Templace_DetailedDesign file location with filename and extension.
Path to template file: 'Template_DetailedDesign.docx'

# Write here path to output file WITHOUT FILENAME AND EXTENSION, JUST FOLDER ONLY
Path to output file: 'C:\pycharm_projects\detailed_design_generator'

# Write here new tags to be created in your comments
# The left tag will be used in comments from your code, and the Right tag will be seen in generated design document
New Tags:
  dynamicaspectdescription: 'DynamicAspectDescription'
  dynamiaspectcaller: 'DynamicAspectCaller'
  initialization: 'Initialization'
  staticaspect: 'StaticAspect'
  constrains: 'Constrains'
  range: 'Range'
  inputparam: 'InputParameters'
  outputparam: 'OutputParameters'
  ddesignrequirement: 'Detailed Design Requirement'
  archrequirement: 'Architecture Requirement'