# =========================================================================
#                     CONFIG FILE FOR PeerReview_and_WarningReport Script
#   Written by: Motoc Mihai
#   Date: 9 March 2023
#   Copyright Autoliv, RBE, 2023
#   Status:
# =========================================================================

# path to the components list
sw_comp_folder: "D:\\workspace\\KPI_Manager\\DAIMLER_MMA_Reports\\Components\\Application\\Autoliv"

# path to where you want to save the report file
output_folder: "D:\\workspace\\KPI_Manager\\DAIMLER_MMA_Reports\\Scripts\\Configuration_Management\\peer_review_and_warningReport_analisys\\Outputs"

# choose here the sorting method by commenting one and uncommenting the other
sort_version: "natsorted"
#sort_version: "last_element_from_list"


# list of files you want to ignore from the modules
list_of_files_to_ignore:
#   - ACC.c
#   - AdcIf.h
#   - ATM.C
#   - BswM_Callouts.h

# list of modules you want to ignore
list_of_directories_to_ignore:
  - Quality_Assurance
  - eCS
  - NVP

# list of all modules to analyse, you can either uncomment all and it will parse the entire list
# or comment it and select specific modules
sw_components_list:
  - all
#  - ACC
#  - AdcIf
#  - ATM
#  - BswMIf
#  - CanTrcvIf
#  - CIL
#  - DcmIf
#  - DemIf
#  - DIA
#  - DioIf
#  - eCS
#  - EcuMIf
#  - EFX
#  - FlsIf
#  - FSM
#  - IoHwAb
#  - LPM
#  - MIC
#  - NmIf
#  - NvmIf
#  - NVP
#  - OsIf
#  - PlatformsIf
#  - PortIf
#  - PwmIf
#  - RCM
#  - RTE
#  - RteIf
#  - SAD
#  - SBC
#  - SpiIf
#  - Startup
#  - STM

