/**************************************************************************************************\
 *** 
 *** Simulink model       : HWA_TestHarness
 *** TargetLink subsystem : HWA_TestHarness/HWA
 *** Codefile             : HWA.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-25 15:44:07
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef HWA_H
#define HWA_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 16
\******************************************************************************/
extern sint16 Sa1_b8CyclesAbortedByMode;
extern sint16 Sa1_b8CyclesAbortedByMode_Ext;
extern sint16 Sa1_b8CyclesInhibitedByMode;
extern sint16 Sa1_b8CyclesInhibitedByMode_Ext;
extern sint16 Sa1_b8InterruptFlag_HWA0;
extern sint16 Sa1_b8InterruptFlag_HWA1;
extern sint16 Sa1_b8IsCarCrashDetected;
extern sint16 Sa1_b8PreActivationFlag_HWA0;
extern sint16 Sa1_b8PreActivationFlag_HWA1;
extern sint16 Sa1_b8PreConditionsFlag_HWA0;
extern sint16 Sa1_b8PreConditionsFlag_HWA1;
extern sint16 Sa1_b8TriggerFlag_HWA0;
extern sint16 Sa1_b8TriggerFlag_HWA1;
extern sint16 Sa1_prrExecutedCycle;
extern sint16 Sa1_u8BuckleSwitch;
extern sint16 Sa1_u8HapticRequest;
extern sint16 Sa1_u8RequestedCycle;
extern sint16 Sa1_u8Status_EndOfLife;
extern sint16 Sa1_u8Status_OverVoltage;
extern sint16 Sa1_u8Status_UVDuringTensioning;
extern sint16 Sa1_u8TriggeringSource_HWA0;
extern sint16 Sa1_u8TriggeringSource_HWA1;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   GlobalStep: Default function class for not static model step functions
\******************************************************************************/
extern void HWA(void);

#endif /* HWA_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
