/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2018 by Vector Informatik GmbH.                                              All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------*/
/*!        \file  Crypto_30_vHsm_Custom.h
 *        \brief  Used to redirect function names generated by the CryIf
 *
 *      \details  
 *
 *********************************************************************************************************************/

 /**********************************************************************************************************************
 *  REVISION HISTORY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Refer to the module's header file.
 *********************************************************************************************************************/

#if !defined (CRYPTO_30_VHSM_CUSTOM_H)
# define CRYPTO_30_VHSM_CUSTOM_H

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
# include "vHsm_Custom.h"

/**********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS
 *********************************************************************************************************************/
# define Crypto_30_vHsm_Custom_CancelJob                vHsm_Custom_CancelJob
# define Crypto_30_vHsm_Custom_CertificateParse         vHsm_Custom_CertificateParse
# define Crypto_30_vHsm_Custom_CertificateVerify        vHsm_Custom_CertificateVerify
# define Crypto_30_vHsm_Custom_KeyCopy                  vHsm_Custom_KeyCopy
# define Crypto_30_vHsm_Custom_KeyDerive                vHsm_Custom_KeyDerive
# define Crypto_30_vHsm_Custom_KeyElementCopy           vHsm_Custom_KeyElementCopy
# define Crypto_30_vHsm_Custom_KeyElementGet            vHsm_Custom_KeyElementGet
# define Crypto_30_vHsm_Custom_KeyElementIdsGet         vHsm_Custom_KeyElementIdsGet
# define Crypto_30_vHsm_Custom_KeyElementSet            vHsm_Custom_KeyElementSet
# define Crypto_30_vHsm_Custom_KeyExchangeCalcPubVal    vHsm_Custom_KeyExchangeCalcPubVal
# define Crypto_30_vHsm_Custom_KeyExchangeCalcSecret    vHsm_Custom_KeyExchangeCalcSecret
# define Crypto_30_vHsm_Custom_KeyGenerate              vHsm_Custom_KeyGenerate
# define Crypto_30_vHsm_Custom_KeyValidSet              vHsm_Custom_KeyValidSet
# define Crypto_30_vHsm_Custom_ProcessJob               vHsm_Custom_ProcessJob
# define Crypto_30_vHsm_Custom_RandomSeed               vHsm_Custom_RandomSeed

/**********************************************************************************************************************
 *  GLOBAL FUNCTION MACROS
 *********************************************************************************************************************/
 
/**********************************************************************************************************************
 *  GLOBAL DATA TYPES AND STRUCTURES
 *********************************************************************************************************************/
 
/**********************************************************************************************************************
 *  GLOBAL DATA PROTOTYPES
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL FUNCTION PROTOTYPES
 *********************************************************************************************************************/

#endif /* CRYPTO_30_VHSM_CUSTOM_H */

/**********************************************************************************************************************
 *  END OF FILE: Crypto_30_vHsm_Custom.h
 *********************************************************************************************************************/
 
