/****************************************************************************************************************************************************\
 *** 
 *** Simulink model       : BFE_TestHarness
 *** TargetLink subsystem : BFE_TestHarness/BFE_AC_BeltFunctionExecution
 *** Codefile             : BFE_Config.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2018-04-17 16:56:17
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 150
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Config\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\****************************************************************************************************************************************************/

#ifndef BFE_CONFIG_H
#define BFE_CONFIG_H

/*------------------------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------------------------*/

#include "Rte_Type.h"

/*------------------------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------------------------*/

/********************************************************************************************************************\
   DEFINE_CFG_BFE: Variable class
\********************************************************************************************************************/
#define CAL_KS16_GAIN_INTEGER_BOOST ((sint16) 2)
#define CAL_KS16_GAIN_INTEGER_STANDARD ((sint16) 8)
#define CAL_KU16_ECU_RESISTANCE ((uint16) 75)
#define CAL_KU16_MOTOR_RESISTANCE ((uint16) 150)
#define CAL_KU16_PYRO_SEQ_BRAKING_DURATION ((uint16) 125) /* Description: Resolution : 1lsb = 400µs */

/********************************************************************************************************************\
   DEFINE_CFG_BFE: Variable class
\********************************************************************************************************************/
#define CAL_KU8_MAX_MOTOR_CURRENT ((uint8) 40)
#define CAL_KU8_PID_BATTERY_KD ((uint8) 0)
#define CAL_KU8_PID_BATTERY_KI ((uint8) 10)
#define CAL_KU8_PID_BATTERY_KP ((uint8) 7)
#define CAL_KU8_PID_MOTOR_KD ((uint8) 0)
#define CAL_KU8_PID_MOTOR_KI ((uint8) 27)
#define CAL_KU8_PID_MOTOR_KP ((uint8) 5)
#define KU8_CYCLE_SIZE ((uint8) 12)
#define KU8_INDEX_OF_FIRST_STEP ((uint8) 4)
#define KU8_MAX_STEP_INDEX ((uint8) 8)
#define KU8_NB_MAX_BELT_FCT_LIBRARY ((uint8) 17)
#define KU8_NB_MAX_STEP_LIBRARY ((uint8) 80)
#define KU8_STEP_SIZE ((uint8) 6)

/********************************************************************************************************************\
   MACRO_CFG_BFE: Variable class
\********************************************************************************************************************/
#define CAL_KU16_HIGH_OFFSET ((uint16) 320)
#define CAL_KU16_HIGH_THRS ((uint16) 2500)
#define CAL_KU16_LOW_OFFSET ((uint16) 64)
#define CAL_KU16_LOW_THRS ((uint16) 500)

/********************************************************************************************************************\
   MACRO_CFG_BFE: Variable class
\********************************************************************************************************************/
#define BFE_CFG_OPT_ADAPT_CURRENT 1
#define BFE_CFG_OPT_BELT_BLOCKED_HES 1
#define BFE_CFG_OPT_BELT_MVT_DETECT 1
#define BFE_CFG_OPT_BELT_PAYOUT_ABORTION 1
#define BFE_CFG_OPT_HIGH_POWER 1
#define BFE_CFG_OPT_MOTOR_BLOCKED 1
#define BFE_CFG_OPT_PID 1
#define BFE_CFG_OPT_TRIGG_OFF 1

/*------------------------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------------------------*/

/********************************************************************************************************************\
   DATA_CFG_BFE: global variables (RAM) | Width: 16
\********************************************************************************************************************/
extern uint16 CAL_AU16_MOTOR_RES_TABLE_TEMPERATURE[7]; /* LSB: 2^-2 OFF: -0 MIN/MAX: 0 .. 16383.75 */
extern uint16 CAL_AU8_MOTOR_RESIST_VALUES[7];
extern uint16 CAL_AU16_CURRENT_INT_POINT_TEMPERATURE[7]; /* LSB: 2^-2 OFF: -0 MIN/MAX: 0 .. 16383.75 */
extern uint16 CAL_AU16_POWER_DEG_VBATT[6];
extern uint16 CAL_AU16_TEMP_WEIGHT_INDEX_RELEASE[7]; /* LSB: 2^-2 OFF: -0 MIN/MAX: 0 .. 16383.75 */
extern uint16 CAL_AU16_TEMP_WEIGHT_INDEX_TENS_0[7]; /* LSB: 2^-2 OFF: -0 MIN/MAX: 0 .. 16383.75 */
extern uint16 CAL_AU16_TEMP_WEIGHT_INDEX_TENS_1[7]; /* LSB: 2^-2 OFF: -0 MIN/MAX: 0 .. 16383.75 */
extern uint16 CAL_AU16_TEMP_WEIGHT_INDEX_TENS_2[7]; /* LSB: 2^-2 OFF: -0 MIN/MAX: 0 .. 16383.75 */
extern uint16 CAL_AU16_TEMP_WEIGHT_INDEX_TENS_3[7]; /* LSB: 2^-2 OFF: -0 MIN/MAX: 0 .. 16383.75 */
extern uint16 CAL_KAU16_ALPHA_MOTOR_CURRENT[3];
extern uint16 CAL_KAU16_BETA_SUPPLY_CURRENT[3];
extern uint16 CAL_KAU16_CURRENT_INT_POINT[64];
extern uint16 CAL_KU16_BELT_PAYOUT_ABORTION_THRS1;
extern uint16 CAL_KU16_BELT_PAYOUT_ABORTION_THRS2;

/********************************************************************************************************************\
   DATA_CFG_BFE: global variables (RAM) | Width: 8
\********************************************************************************************************************/
extern uint8 CAL_AU8_BELT_PROFILES[204];
extern uint8 CAL_AU8_CURRENT_INT_POINT_FACTOR[7];
extern uint8 CAL_AU8_POWER_DEG_FACTORS[6];
extern uint8 CAL_AU8_STEPS_DEFINITION[480];
extern uint8 CAL_AU8_TEMP_WEIGHT_FACTORS_RELEASE[7];
extern uint8 CAL_AU8_TEMP_WEIGHT_FACTORS_TENS_0[7];
extern uint8 CAL_AU8_TEMP_WEIGHT_FACTORS_TENS_1[7];
extern uint8 CAL_AU8_TEMP_WEIGHT_FACTORS_TENS_2[7];
extern uint8 CAL_AU8_TEMP_WEIGHT_FACTORS_TENS_3[7];
extern uint8 CAL_KAU8_ALPHA_COEF[3];
extern uint8 CAL_KAU8_BETA_COEF[3];

/*------------------------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------------------------*/

/********************************************************************************************************************\
   EXTERN_FCN_CRITICAL_SECTION: external function(s) (imported from another module)
\********************************************************************************************************************/
extern void BFE_EnterCriticalSection(void);

extern void BFE_ExitCriticalSection(void);

#endif /* BFE_CONFIG_H */
/*------------------------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------------------------*/
