/*************************************************************************
                                                                          
AUTOLIV ELECTRONIC document.                                              
                                                                          
-------------------------------------                                     
                                                                          
DUPLICATION or DISCLOSURE PROHIBITED without prior written consent        
                                                                          
**************************************************************************
                                                                          
This file Nvp_alias.h is generated by the Excel document SBE_4G_NVP_layout.xls
when using "Generate All" Button 
                                                                          
Date and time of generation of files:     3/21/2024 / 8:04:01 PM
 
Current revision: $Revision: 1.15.1.26 $
Checked in:       $Date: 2024/03/22 10:46:46CET $
 
*************************************************************************/
                                                                          
#ifndef NVP_ALIAS_H_
#define NVP_ALIAS_H_ 1
                                                                          
#include "Nvp_MemoryMapping.h"
                                                                          
/*************************************************************************
Other components external interface inclusion                             
*************************************************************************/
                                                                          
/*************************************************************************
Declaration of constants
*************************************************************************/
                                                                          
/*************************************************************************
Declaration of macros
*************************************************************************/
                                                                          
/*************************************************************************
Declaration of types
*************************************************************************/
                                                                          
/*************************************************************************
Declaration of variables
*************************************************************************/
                                                                          
#define BlockAddress_RAM_EcuLocation                                 __RAM_SHADOW__(0x500)
#define BlockAddress_ROM_EcuLocation                                 __ROM_DEFAULT__(0x020)
 
#define BlockAddress_RAM_AssemblyManufDateAndSn                      __RAM_SHADOW__(0x504)
#define BlockAddress_ROM_AssemblyManufDateAndSn                      __ROM_DEFAULT__(0x028)
 
#define BlockAddress_RAM_HbCalibration                               __RAM_SHADOW__(0x520)
#define BlockAddress_ROM_HbCalibration                               __ROM_DEFAULT__(0x044)
 
#define BlockAddress_RAM_AEETraceability                             __RAM_SHADOW__(0x548)
#define BlockAddress_ROM_AEETraceability                             __ROM_DEFAULT__(0x06C)
 
#define BlockAddress_RAM_ExecutionCounters                           __RAM_SHADOW__(0x554)
#define BlockAddress_ROM_ExecutionCounters                           __ROM_DEFAULT__(0x078)
 
#define BlockAddress_RAM_MeasurementFrame12Config                    __RAM_SHADOW__(0x568)
#define BlockAddress_ROM_MeasurementFrame12Config                    __ROM_DEFAULT__(0x08C)
 
#define BlockAddress_RAM_MeasurementFrameConfig                      __RAM_SHADOW__(0x570)
#define BlockAddress_ROM_MeasurementFrameConfig                      __ROM_DEFAULT__(0x098)
 
#define BlockAddress_RAM_WarmReset                                   __RAM_SHADOW__(0x574)
#define BlockAddress_ROM_WarmReset                                   __ROM_DEFAULT__(0x09C)
 
#define BlockAddress_RAM_HWARepetition                               __RAM_SHADOW__(0x57C)
#define BlockAddress_ROM_HWARepetition                               __ROM_DEFAULT__(0x0A4)
 
#define BlockAddress_RAM_TestsParam                                  __RAM_SHADOW__(0x580)
#define BlockAddress_ROM_TestsParam                                  __ROM_DEFAULT__(0x0AC)
 
#define BlockAddress_RAM_Temp_Sensor_Table                           __RAM_SHADOW__(0x5E4)
#define BlockAddress_ROM_Temp_Sensor_Table                           __ROM_DEFAULT__(0x114)
 
#define BlockAddress_RAM_VelocityPID                                 __RAM_SHADOW__(0x610)
#define BlockAddress_ROM_VelocityPID                                 __ROM_DEFAULT__(0x144)
 
#define BlockAddress_RAM_AecStatus                                   __RAM_SHADOW__(0x630)
#define BlockAddress_ROM_AecStatus                                   __ROM_DEFAULT__(0x168)
 
#define BlockAddress_RAM_ATMEnableParam                              __RAM_SHADOW__(0x670)
#define BlockAddress_ROM_ATMEnableParam                              __ROM_DEFAULT__(0x1A8)
 
#define BlockAddress_RAM_PRE_SAFE_RECORDER_1                         __RAM_SHADOW__(0x6A8)
#define BlockAddress_ROM_PRE_SAFE_RECORDER_1                         __ROM_DEFAULT__(0x1E4)
 
#define BlockAddress_RAM_PRE_SAFE_RECORDER_2                         __RAM_SHADOW__(0x6C0)
#define BlockAddress_ROM_PRE_SAFE_RECORDER_2                         __ROM_DEFAULT__(0x200)
 
#define BlockAddress_RAM_PRE_SAFE_RECORDER_ID                        __RAM_SHADOW__(0x6D8)
#define BlockAddress_ROM_PRE_SAFE_RECORDER_ID                        __ROM_DEFAULT__(0x21C)
 
#define BlockAddress_RAM_Cycle0                                      __RAM_SHADOW__(0x6DC)
#define BlockAddress_ROM_Cycle0                                      __ROM_DEFAULT__(0x224)
 
#define BlockAddress_RAM_Cycle1                                      __RAM_SHADOW__(0x6E8)
#define BlockAddress_ROM_Cycle1                                      __ROM_DEFAULT__(0x230)
 
#define BlockAddress_RAM_Cycle2                                      __RAM_SHADOW__(0x6F4)
#define BlockAddress_ROM_Cycle2                                      __ROM_DEFAULT__(0x23C)
 
#define BlockAddress_RAM_Cycle3                                      __RAM_SHADOW__(0x700)
#define BlockAddress_ROM_Cycle3                                      __ROM_DEFAULT__(0x248)
 
#define BlockAddress_RAM_Cycle4                                      __RAM_SHADOW__(0x70C)
#define BlockAddress_ROM_Cycle4                                      __ROM_DEFAULT__(0x254)
 
#define BlockAddress_RAM_Cycle5                                      __RAM_SHADOW__(0x718)
#define BlockAddress_ROM_Cycle5                                      __ROM_DEFAULT__(0x260)
 
#define BlockAddress_RAM_Cycle6                                      __RAM_SHADOW__(0x724)
#define BlockAddress_ROM_Cycle6                                      __ROM_DEFAULT__(0x26C)
 
#define BlockAddress_RAM_Cycle7                                      __RAM_SHADOW__(0x730)
#define BlockAddress_ROM_Cycle7                                      __ROM_DEFAULT__(0x278)
 
#define BlockAddress_RAM_Cycle8                                      __RAM_SHADOW__(0x73C)
#define BlockAddress_ROM_Cycle8                                      __ROM_DEFAULT__(0x284)
 
#define BlockAddress_RAM_Cycle9                                      __RAM_SHADOW__(0x748)
#define BlockAddress_ROM_Cycle9                                      __ROM_DEFAULT__(0x290)
 
#define BlockAddress_RAM_Cycle10                                     __RAM_SHADOW__(0x754)
#define BlockAddress_ROM_Cycle10                                     __ROM_DEFAULT__(0x29C)
 
#define BlockAddress_RAM_Cycle11                                     __RAM_SHADOW__(0x760)
#define BlockAddress_ROM_Cycle11                                     __ROM_DEFAULT__(0x2A8)
 
#define BlockAddress_RAM_Cycle12                                     __RAM_SHADOW__(0x76C)
#define BlockAddress_ROM_Cycle12                                     __ROM_DEFAULT__(0x2B4)
 
#define BlockAddress_RAM_Cycle13                                     __RAM_SHADOW__(0x778)
#define BlockAddress_ROM_Cycle13                                     __ROM_DEFAULT__(0x2C0)
 
#define BlockAddress_RAM_Cycle14                                     __RAM_SHADOW__(0x784)
#define BlockAddress_ROM_Cycle14                                     __ROM_DEFAULT__(0x2CC)
 
#define BlockAddress_RAM_Cycle15                                     __RAM_SHADOW__(0x790)
#define BlockAddress_ROM_Cycle15                                     __ROM_DEFAULT__(0x2D8)
 
#define BlockAddress_RAM_Cycle16                                     __RAM_SHADOW__(0x79C)
#define BlockAddress_ROM_Cycle16                                     __ROM_DEFAULT__(0x2E4)
 
#define BlockAddress_RAM_Cycle17                                     __RAM_SHADOW__(0x7A8)
#define BlockAddress_ROM_Cycle17                                     __ROM_DEFAULT__(0x2F0)
 
#define BlockAddress_RAM_Cycle18                                     __RAM_SHADOW__(0x7B4)
#define BlockAddress_ROM_Cycle18                                     __ROM_DEFAULT__(0x2FC)
 
#define BlockAddress_RAM_Cycle19                                     __RAM_SHADOW__(0x7C0)
#define BlockAddress_ROM_Cycle19                                     __ROM_DEFAULT__(0x308)
 
#define BlockAddress_RAM_Cycle20                                     __RAM_SHADOW__(0x7CC)
#define BlockAddress_ROM_Cycle20                                     __ROM_DEFAULT__(0x314)
 
#define BlockAddress_RAM_Cycle21                                     __RAM_SHADOW__(0x7D8)
#define BlockAddress_ROM_Cycle21                                     __ROM_DEFAULT__(0x320)
 
#define BlockAddress_RAM_Cycle22                                     __RAM_SHADOW__(0x7E4)
#define BlockAddress_ROM_Cycle22                                     __ROM_DEFAULT__(0x32C)
 
#define BlockAddress_RAM_Cycle23                                     __RAM_SHADOW__(0x7F0)
#define BlockAddress_ROM_Cycle23                                     __ROM_DEFAULT__(0x338)
 
#define BlockAddress_RAM_Cycle24                                     __RAM_SHADOW__(0x7FC)
#define BlockAddress_ROM_Cycle24                                     __ROM_DEFAULT__(0x344)
 
#define BlockAddress_RAM_Cycle25                                     __RAM_SHADOW__(0x808)
#define BlockAddress_ROM_Cycle25                                     __ROM_DEFAULT__(0x350)
 
#define BlockAddress_RAM_Cycle26                                     __RAM_SHADOW__(0x814)
#define BlockAddress_ROM_Cycle26                                     __ROM_DEFAULT__(0x35C)
 
#define BlockAddress_RAM_Cycle27                                     __RAM_SHADOW__(0x820)
#define BlockAddress_ROM_Cycle27                                     __ROM_DEFAULT__(0x368)
 
#define BlockAddress_RAM_Cycle28                                     __RAM_SHADOW__(0x82C)
#define BlockAddress_ROM_Cycle28                                     __ROM_DEFAULT__(0x374)
 
#define BlockAddress_RAM_Cycle29                                     __RAM_SHADOW__(0x838)
#define BlockAddress_ROM_Cycle29                                     __ROM_DEFAULT__(0x380)
 
#define BlockAddress_RAM_Cycle30                                     __RAM_SHADOW__(0x844)
#define BlockAddress_ROM_Cycle30                                     __ROM_DEFAULT__(0x38C)
 
#define BlockAddress_RAM_Cycle31                                     __RAM_SHADOW__(0x850)
#define BlockAddress_ROM_Cycle31                                     __ROM_DEFAULT__(0x398)
 
#define BlockAddress_RAM_Cycle31                                     __RAM_SHADOW__(0x85C)
#define BlockAddress_ROM_Cycle31                                     __ROM_DEFAULT__(0x3A4)
 
#define BlockAddress_RAM_Cycle31                                     __RAM_SHADOW__(0x868)
#define BlockAddress_ROM_Cycle31                                     __ROM_DEFAULT__(0x3B0)
 
#define BlockAddress_RAM_Cycle31                                     __RAM_SHADOW__(0x874)
#define BlockAddress_ROM_Cycle31                                     __ROM_DEFAULT__(0x3BC)
 
#define BlockAddress_RAM_Step0                                       __RAM_SHADOW__(0x880)
#define BlockAddress_ROM_Step0                                       __ROM_DEFAULT__(0x3C8)
 
#define BlockAddress_RAM_Step1                                       __RAM_SHADOW__(0x888)
#define BlockAddress_ROM_Step1                                       __ROM_DEFAULT__(0x3D0)
 
#define BlockAddress_RAM_Step2                                       __RAM_SHADOW__(0x890)
#define BlockAddress_ROM_Step2                                       __ROM_DEFAULT__(0x3D8)
 
#define BlockAddress_RAM_Step3                                       __RAM_SHADOW__(0x898)
#define BlockAddress_ROM_Step3                                       __ROM_DEFAULT__(0x3E0)
 
#define BlockAddress_RAM_Step4                                       __RAM_SHADOW__(0x8A0)
#define BlockAddress_ROM_Step4                                       __ROM_DEFAULT__(0x3E8)
 
#define BlockAddress_RAM_Step5                                       __RAM_SHADOW__(0x8A8)
#define BlockAddress_ROM_Step5                                       __ROM_DEFAULT__(0x3F0)
 
#define BlockAddress_RAM_Step6                                       __RAM_SHADOW__(0x8B0)
#define BlockAddress_ROM_Step6                                       __ROM_DEFAULT__(0x3F8)
 
#define BlockAddress_RAM_Step7                                       __RAM_SHADOW__(0x8B8)
#define BlockAddress_ROM_Step7                                       __ROM_DEFAULT__(0x400)
 
#define BlockAddress_RAM_Step8                                       __RAM_SHADOW__(0x8C0)
#define BlockAddress_ROM_Step8                                       __ROM_DEFAULT__(0x408)
 
#define BlockAddress_RAM_Step9                                       __RAM_SHADOW__(0x8C8)
#define BlockAddress_ROM_Step9                                       __ROM_DEFAULT__(0x410)
 
#define BlockAddress_RAM_Step10                                      __RAM_SHADOW__(0x8D0)
#define BlockAddress_ROM_Step10                                      __ROM_DEFAULT__(0x418)
 
#define BlockAddress_RAM_Step11                                      __RAM_SHADOW__(0x8D8)
#define BlockAddress_ROM_Step11                                      __ROM_DEFAULT__(0x420)
 
#define BlockAddress_RAM_Step12                                      __RAM_SHADOW__(0x8E0)
#define BlockAddress_ROM_Step12                                      __ROM_DEFAULT__(0x428)
 
#define BlockAddress_RAM_Step13                                      __RAM_SHADOW__(0x8E8)
#define BlockAddress_ROM_Step13                                      __ROM_DEFAULT__(0x430)
 
#define BlockAddress_RAM_Step14                                      __RAM_SHADOW__(0x8F0)
#define BlockAddress_ROM_Step14                                      __ROM_DEFAULT__(0x438)
 
#define BlockAddress_RAM_Step15                                      __RAM_SHADOW__(0x8F8)
#define BlockAddress_ROM_Step15                                      __ROM_DEFAULT__(0x440)
 
#define BlockAddress_RAM_Step16                                      __RAM_SHADOW__(0x900)
#define BlockAddress_ROM_Step16                                      __ROM_DEFAULT__(0x448)
 
#define BlockAddress_RAM_Step17                                      __RAM_SHADOW__(0x908)
#define BlockAddress_ROM_Step17                                      __ROM_DEFAULT__(0x450)
 
#define BlockAddress_RAM_Step18                                      __RAM_SHADOW__(0x910)
#define BlockAddress_ROM_Step18                                      __ROM_DEFAULT__(0x458)
 
#define BlockAddress_RAM_Step19                                      __RAM_SHADOW__(0x918)
#define BlockAddress_ROM_Step19                                      __ROM_DEFAULT__(0x460)
 
#define BlockAddress_RAM_Step20                                      __RAM_SHADOW__(0x920)
#define BlockAddress_ROM_Step20                                      __ROM_DEFAULT__(0x468)
 
#define BlockAddress_RAM_Step21                                      __RAM_SHADOW__(0x928)
#define BlockAddress_ROM_Step21                                      __ROM_DEFAULT__(0x470)
 
#define BlockAddress_RAM_Step22                                      __RAM_SHADOW__(0x930)
#define BlockAddress_ROM_Step22                                      __ROM_DEFAULT__(0x478)
 
#define BlockAddress_RAM_Step23                                      __RAM_SHADOW__(0x938)
#define BlockAddress_ROM_Step23                                      __ROM_DEFAULT__(0x480)
 
#define BlockAddress_RAM_Step24                                      __RAM_SHADOW__(0x940)
#define BlockAddress_ROM_Step24                                      __ROM_DEFAULT__(0x488)
 
#define BlockAddress_RAM_Step25                                      __RAM_SHADOW__(0x948)
#define BlockAddress_ROM_Step25                                      __ROM_DEFAULT__(0x490)
 
#define BlockAddress_RAM_Step26                                      __RAM_SHADOW__(0x950)
#define BlockAddress_ROM_Step26                                      __ROM_DEFAULT__(0x498)
 
#define BlockAddress_RAM_Step27                                      __RAM_SHADOW__(0x958)
#define BlockAddress_ROM_Step27                                      __ROM_DEFAULT__(0x4A0)
 
#define BlockAddress_RAM_Step28                                      __RAM_SHADOW__(0x960)
#define BlockAddress_ROM_Step28                                      __ROM_DEFAULT__(0x4A8)
 
#define BlockAddress_RAM_Step29                                      __RAM_SHADOW__(0x968)
#define BlockAddress_ROM_Step29                                      __ROM_DEFAULT__(0x4B0)
 
#define BlockAddress_RAM_Step30                                      __RAM_SHADOW__(0x970)
#define BlockAddress_ROM_Step30                                      __ROM_DEFAULT__(0x4B8)
 
#define BlockAddress_RAM_Step31                                      __RAM_SHADOW__(0x978)
#define BlockAddress_ROM_Step31                                      __ROM_DEFAULT__(0x4C0)
 
#define BlockAddress_RAM_Step32                                      __RAM_SHADOW__(0x980)
#define BlockAddress_ROM_Step32                                      __ROM_DEFAULT__(0x4C8)
 
#define BlockAddress_RAM_Step33                                      __RAM_SHADOW__(0x988)
#define BlockAddress_ROM_Step33                                      __ROM_DEFAULT__(0x4D0)
 
#define BlockAddress_RAM_Step34                                      __RAM_SHADOW__(0x990)
#define BlockAddress_ROM_Step34                                      __ROM_DEFAULT__(0x4D8)
 
#define BlockAddress_RAM_Step35                                      __RAM_SHADOW__(0x998)
#define BlockAddress_ROM_Step35                                      __ROM_DEFAULT__(0x4E0)
 
#define BlockAddress_RAM_Step36                                      __RAM_SHADOW__(0x9A0)
#define BlockAddress_ROM_Step36                                      __ROM_DEFAULT__(0x4E8)
 
#define BlockAddress_RAM_Step37                                      __RAM_SHADOW__(0x9A8)
#define BlockAddress_ROM_Step37                                      __ROM_DEFAULT__(0x4F0)
 
#define BlockAddress_RAM_Step38                                      __RAM_SHADOW__(0x9B0)
#define BlockAddress_ROM_Step38                                      __ROM_DEFAULT__(0x4F8)
 
#define BlockAddress_RAM_Step39                                      __RAM_SHADOW__(0x9B8)
#define BlockAddress_ROM_Step39                                      __ROM_DEFAULT__(0x500)
 
#define BlockAddress_RAM_Step40                                      __RAM_SHADOW__(0x9C0)
#define BlockAddress_ROM_Step40                                      __ROM_DEFAULT__(0x508)
 
#define BlockAddress_RAM_Step41                                      __RAM_SHADOW__(0x9C8)
#define BlockAddress_ROM_Step41                                      __ROM_DEFAULT__(0x510)
 
#define BlockAddress_RAM_Step42                                      __RAM_SHADOW__(0x9D0)
#define BlockAddress_ROM_Step42                                      __ROM_DEFAULT__(0x518)
 
#define BlockAddress_RAM_Step43                                      __RAM_SHADOW__(0x9D8)
#define BlockAddress_ROM_Step43                                      __ROM_DEFAULT__(0x520)
 
#define BlockAddress_RAM_Step44                                      __RAM_SHADOW__(0x9E0)
#define BlockAddress_ROM_Step44                                      __ROM_DEFAULT__(0x528)
 
#define BlockAddress_RAM_Step45                                      __RAM_SHADOW__(0x9E8)
#define BlockAddress_ROM_Step45                                      __ROM_DEFAULT__(0x530)
 
#define BlockAddress_RAM_Step46                                      __RAM_SHADOW__(0x9F0)
#define BlockAddress_ROM_Step46                                      __ROM_DEFAULT__(0x538)
 
#define BlockAddress_RAM_Step47                                      __RAM_SHADOW__(0x9F8)
#define BlockAddress_ROM_Step47                                      __ROM_DEFAULT__(0x540)
 
#define BlockAddress_RAM_Step48                                      __RAM_SHADOW__(0xA00)
#define BlockAddress_ROM_Step48                                      __ROM_DEFAULT__(0x548)
 
#define BlockAddress_RAM_Step49                                      __RAM_SHADOW__(0xA08)
#define BlockAddress_ROM_Step49                                      __ROM_DEFAULT__(0x550)
 
#define BlockAddress_RAM_Step50                                      __RAM_SHADOW__(0xA10)
#define BlockAddress_ROM_Step50                                      __ROM_DEFAULT__(0x558)
 
#define BlockAddress_RAM_Step51                                      __RAM_SHADOW__(0xA18)
#define BlockAddress_ROM_Step51                                      __ROM_DEFAULT__(0x560)
 
#define BlockAddress_RAM_Step52                                      __RAM_SHADOW__(0xA20)
#define BlockAddress_ROM_Step52                                      __ROM_DEFAULT__(0x568)
 
#define BlockAddress_RAM_Step53                                      __RAM_SHADOW__(0xA28)
#define BlockAddress_ROM_Step53                                      __ROM_DEFAULT__(0x570)
 
#define BlockAddress_RAM_Step54                                      __RAM_SHADOW__(0xA30)
#define BlockAddress_ROM_Step54                                      __ROM_DEFAULT__(0x578)
 
#define BlockAddress_RAM_Step55                                      __RAM_SHADOW__(0xA38)
#define BlockAddress_ROM_Step55                                      __ROM_DEFAULT__(0x580)
 
#define BlockAddress_RAM_Step56                                      __RAM_SHADOW__(0xA40)
#define BlockAddress_ROM_Step56                                      __ROM_DEFAULT__(0x588)
 
#define BlockAddress_RAM_Step57                                      __RAM_SHADOW__(0xA48)
#define BlockAddress_ROM_Step57                                      __ROM_DEFAULT__(0x590)
 
#define BlockAddress_RAM_Step58                                      __RAM_SHADOW__(0xA50)
#define BlockAddress_ROM_Step58                                      __ROM_DEFAULT__(0x598)
 
#define BlockAddress_RAM_Step59                                      __RAM_SHADOW__(0xA58)
#define BlockAddress_ROM_Step59                                      __ROM_DEFAULT__(0x5A0)
 
#define BlockAddress_RAM_Step60                                      __RAM_SHADOW__(0xA60)
#define BlockAddress_ROM_Step60                                      __ROM_DEFAULT__(0x5A8)
 
#define BlockAddress_RAM_Step61                                      __RAM_SHADOW__(0xA68)
#define BlockAddress_ROM_Step61                                      __ROM_DEFAULT__(0x5B0)
 
#define BlockAddress_RAM_Step62                                      __RAM_SHADOW__(0xA70)
#define BlockAddress_ROM_Step62                                      __ROM_DEFAULT__(0x5B8)
 
#define BlockAddress_RAM_Step63                                      __RAM_SHADOW__(0xA78)
#define BlockAddress_ROM_Step63                                      __ROM_DEFAULT__(0x5C0)
 
#define BlockAddress_RAM_Step64                                      __RAM_SHADOW__(0xA80)
#define BlockAddress_ROM_Step64                                      __ROM_DEFAULT__(0x5C8)
 
#define BlockAddress_RAM_Step65                                      __RAM_SHADOW__(0xA88)
#define BlockAddress_ROM_Step65                                      __ROM_DEFAULT__(0x5D0)
 
#define BlockAddress_RAM_Step66                                      __RAM_SHADOW__(0xA90)
#define BlockAddress_ROM_Step66                                      __ROM_DEFAULT__(0x5D8)
 
#define BlockAddress_RAM_Step67                                      __RAM_SHADOW__(0xA98)
#define BlockAddress_ROM_Step67                                      __ROM_DEFAULT__(0x5E0)
 
#define BlockAddress_RAM_Step68                                      __RAM_SHADOW__(0xAA0)
#define BlockAddress_ROM_Step68                                      __ROM_DEFAULT__(0x5E8)
 
#define BlockAddress_RAM_Step69                                      __RAM_SHADOW__(0xAA8)
#define BlockAddress_ROM_Step69                                      __ROM_DEFAULT__(0x5F0)
 
#define BlockAddress_RAM_Step70                                      __RAM_SHADOW__(0xAB0)
#define BlockAddress_ROM_Step70                                      __ROM_DEFAULT__(0x5F8)
 
#define BlockAddress_RAM_Step71                                      __RAM_SHADOW__(0xAB8)
#define BlockAddress_ROM_Step71                                      __ROM_DEFAULT__(0x600)
 
#define BlockAddress_RAM_Step72                                      __RAM_SHADOW__(0xAC0)
#define BlockAddress_ROM_Step72                                      __ROM_DEFAULT__(0x608)
 
#define BlockAddress_RAM_Step73                                      __RAM_SHADOW__(0xAC8)
#define BlockAddress_ROM_Step73                                      __ROM_DEFAULT__(0x610)
 
#define BlockAddress_RAM_Step74                                      __RAM_SHADOW__(0xAD0)
#define BlockAddress_ROM_Step74                                      __ROM_DEFAULT__(0x618)
 
#define BlockAddress_RAM_Step75                                      __RAM_SHADOW__(0xAD8)
#define BlockAddress_ROM_Step75                                      __ROM_DEFAULT__(0x620)
 
#define BlockAddress_RAM_Step76                                      __RAM_SHADOW__(0xAE0)
#define BlockAddress_ROM_Step76                                      __ROM_DEFAULT__(0x628)
 
#define BlockAddress_RAM_Step77                                      __RAM_SHADOW__(0xAE8)
#define BlockAddress_ROM_Step77                                      __ROM_DEFAULT__(0x630)
 
#define BlockAddress_RAM_Step78                                      __RAM_SHADOW__(0xAF0)
#define BlockAddress_ROM_Step78                                      __ROM_DEFAULT__(0x638)
 
#define BlockAddress_RAM_Step79                                      __RAM_SHADOW__(0xAF8)
#define BlockAddress_ROM_Step79                                      __ROM_DEFAULT__(0x640)
 
#define BlockAddress_RAM_Step80                                      __RAM_SHADOW__(0xB00)
#define BlockAddress_ROM_Step80                                      __ROM_DEFAULT__(0x648)
 
#define BlockAddress_RAM_Step81                                      __RAM_SHADOW__(0xB08)
#define BlockAddress_ROM_Step81                                      __ROM_DEFAULT__(0x650)
 
#define BlockAddress_RAM_Step82                                      __RAM_SHADOW__(0xB10)
#define BlockAddress_ROM_Step82                                      __ROM_DEFAULT__(0x658)
 
#define BlockAddress_RAM_Step83                                      __RAM_SHADOW__(0xB18)
#define BlockAddress_ROM_Step83                                      __ROM_DEFAULT__(0x660)
 
#define BlockAddress_RAM_Step84                                      __RAM_SHADOW__(0xB20)
#define BlockAddress_ROM_Step84                                      __ROM_DEFAULT__(0x668)
 
#define BlockAddress_RAM_Step85                                      __RAM_SHADOW__(0xB28)
#define BlockAddress_ROM_Step85                                      __ROM_DEFAULT__(0x670)
 
#define BlockAddress_RAM_Step86                                      __RAM_SHADOW__(0xB30)
#define BlockAddress_ROM_Step86                                      __ROM_DEFAULT__(0x678)
 
#define BlockAddress_RAM_Step87                                      __RAM_SHADOW__(0xB38)
#define BlockAddress_ROM_Step87                                      __ROM_DEFAULT__(0x680)
 
#define BlockAddress_RAM_Step88                                      __RAM_SHADOW__(0xB40)
#define BlockAddress_ROM_Step88                                      __ROM_DEFAULT__(0x688)
 
#define BlockAddress_RAM_Step89                                      __RAM_SHADOW__(0xB48)
#define BlockAddress_ROM_Step89                                      __ROM_DEFAULT__(0x690)
 
#define BlockAddress_RAM_Step90                                      __RAM_SHADOW__(0xB50)
#define BlockAddress_ROM_Step90                                      __ROM_DEFAULT__(0x698)
 
#define BlockAddress_RAM_Step91                                      __RAM_SHADOW__(0xB58)
#define BlockAddress_ROM_Step91                                      __ROM_DEFAULT__(0x6A0)
 
#define BlockAddress_RAM_Step92                                      __RAM_SHADOW__(0xB60)
#define BlockAddress_ROM_Step92                                      __ROM_DEFAULT__(0x6A8)
 
#define BlockAddress_RAM_Step93                                      __RAM_SHADOW__(0xB68)
#define BlockAddress_ROM_Step93                                      __ROM_DEFAULT__(0x6B0)
 
#define BlockAddress_RAM_Step94                                      __RAM_SHADOW__(0xB70)
#define BlockAddress_ROM_Step94                                      __ROM_DEFAULT__(0x6B8)
 
#define BlockAddress_RAM_Step95                                      __RAM_SHADOW__(0xB78)
#define BlockAddress_ROM_Step95                                      __ROM_DEFAULT__(0x6C0)
 
#define BlockAddress_RAM_Step96                                      __RAM_SHADOW__(0xB80)
#define BlockAddress_ROM_Step96                                      __ROM_DEFAULT__(0x6C8)
 
#define BlockAddress_RAM_Step97                                      __RAM_SHADOW__(0xB88)
#define BlockAddress_ROM_Step97                                      __ROM_DEFAULT__(0x6D0)
 
#define BlockAddress_RAM_Step98                                      __RAM_SHADOW__(0xB90)
#define BlockAddress_ROM_Step98                                      __ROM_DEFAULT__(0x6D8)
 
#define BlockAddress_RAM_Step99                                      __RAM_SHADOW__(0xB98)
#define BlockAddress_ROM_Step99                                      __ROM_DEFAULT__(0x6E0)
 
#define BlockAddress_RAM_Step100                                     __RAM_SHADOW__(0xBA0)
#define BlockAddress_ROM_Step100                                     __ROM_DEFAULT__(0x6E8)
 
#define BlockAddress_RAM_Step101                                     __RAM_SHADOW__(0xBA8)
#define BlockAddress_ROM_Step101                                     __ROM_DEFAULT__(0x6F0)
 
#define BlockAddress_RAM_Step102                                     __RAM_SHADOW__(0xBB0)
#define BlockAddress_ROM_Step102                                     __ROM_DEFAULT__(0x6F8)
 
#define BlockAddress_RAM_Step103                                     __RAM_SHADOW__(0xBB8)
#define BlockAddress_ROM_Step103                                     __ROM_DEFAULT__(0x700)
 
#define BlockAddress_RAM_Step104                                     __RAM_SHADOW__(0xBC0)
#define BlockAddress_ROM_Step104                                     __ROM_DEFAULT__(0x708)
 
#define BlockAddress_RAM_Step105                                     __RAM_SHADOW__(0xBC8)
#define BlockAddress_ROM_Step105                                     __ROM_DEFAULT__(0x710)
 
#define BlockAddress_RAM_Step106                                     __RAM_SHADOW__(0xBD0)
#define BlockAddress_ROM_Step106                                     __ROM_DEFAULT__(0x718)
 
#define BlockAddress_RAM_Step107                                     __RAM_SHADOW__(0xBD8)
#define BlockAddress_ROM_Step107                                     __ROM_DEFAULT__(0x720)
 
#define BlockAddress_RAM_Step108                                     __RAM_SHADOW__(0xBE0)
#define BlockAddress_ROM_Step108                                     __ROM_DEFAULT__(0x728)
 
#define BlockAddress_RAM_Step109                                     __RAM_SHADOW__(0xBE8)
#define BlockAddress_ROM_Step109                                     __ROM_DEFAULT__(0x730)
 
#define BlockAddress_RAM_Step110                                     __RAM_SHADOW__(0xBF0)
#define BlockAddress_ROM_Step110                                     __ROM_DEFAULT__(0x738)
 
#define BlockAddress_RAM_Step111                                     __RAM_SHADOW__(0xBF8)
#define BlockAddress_ROM_Step111                                     __ROM_DEFAULT__(0x740)
 
#define BlockAddress_RAM_Step112                                     __RAM_SHADOW__(0xC00)
#define BlockAddress_ROM_Step112                                     __ROM_DEFAULT__(0x748)
 
#define BlockAddress_RAM_Step113                                     __RAM_SHADOW__(0xC08)
#define BlockAddress_ROM_Step113                                     __ROM_DEFAULT__(0x750)
 
#define BlockAddress_RAM_Step114                                     __RAM_SHADOW__(0xC10)
#define BlockAddress_ROM_Step114                                     __ROM_DEFAULT__(0x758)
 
#define BlockAddress_RAM_Step115                                     __RAM_SHADOW__(0xC18)
#define BlockAddress_ROM_Step115                                     __ROM_DEFAULT__(0x760)
 
#define BlockAddress_RAM_Step116                                     __RAM_SHADOW__(0xC20)
#define BlockAddress_ROM_Step116                                     __ROM_DEFAULT__(0x768)
 
#define BlockAddress_RAM_Step117                                     __RAM_SHADOW__(0xC28)
#define BlockAddress_ROM_Step117                                     __ROM_DEFAULT__(0x770)
 
#define BlockAddress_RAM_Step118                                     __RAM_SHADOW__(0xC30)
#define BlockAddress_ROM_Step118                                     __ROM_DEFAULT__(0x778)
 
#define BlockAddress_RAM_Step119                                     __RAM_SHADOW__(0xC38)
#define BlockAddress_ROM_Step119                                     __ROM_DEFAULT__(0x780)
 
#define BlockAddress_RAM_Step120                                     __RAM_SHADOW__(0xC40)
#define BlockAddress_ROM_Step120                                     __ROM_DEFAULT__(0x788)
 
#define BlockAddress_RAM_Step121                                     __RAM_SHADOW__(0xC48)
#define BlockAddress_ROM_Step121                                     __ROM_DEFAULT__(0x790)
 
#define BlockAddress_RAM_Step122                                     __RAM_SHADOW__(0xC50)
#define BlockAddress_ROM_Step122                                     __ROM_DEFAULT__(0x798)
 
#define BlockAddress_RAM_Step123                                     __RAM_SHADOW__(0xC58)
#define BlockAddress_ROM_Step123                                     __ROM_DEFAULT__(0x7A0)
 
#define BlockAddress_RAM_Step124                                     __RAM_SHADOW__(0xC60)
#define BlockAddress_ROM_Step124                                     __ROM_DEFAULT__(0x7A8)
 
#define BlockAddress_RAM_Step125                                     __RAM_SHADOW__(0xC68)
#define BlockAddress_ROM_Step125                                     __ROM_DEFAULT__(0x7B0)
 
#define BlockAddress_RAM_Step126                                     __RAM_SHADOW__(0xC70)
#define BlockAddress_ROM_Step126                                     __ROM_DEFAULT__(0x7B8)
 
#define BlockAddress_RAM_Step127                                     __RAM_SHADOW__(0xC78)
#define BlockAddress_ROM_Step127                                     __ROM_DEFAULT__(0x7C0)
 
#define BlockAddress_RAM_Step128                                     __RAM_SHADOW__(0xC80)
#define BlockAddress_ROM_Step128                                     __ROM_DEFAULT__(0x7C8)
 
#define BlockAddress_RAM_Step129                                     __RAM_SHADOW__(0xC88)
#define BlockAddress_ROM_Step129                                     __ROM_DEFAULT__(0x7D0)
 
#define BlockAddress_RAM_Step130                                     __RAM_SHADOW__(0xC90)
#define BlockAddress_ROM_Step130                                     __ROM_DEFAULT__(0x7D8)
 
#define BlockAddress_RAM_Step131                                     __RAM_SHADOW__(0xC98)
#define BlockAddress_ROM_Step131                                     __ROM_DEFAULT__(0x7E0)
 
#define BlockAddress_RAM_Step132                                     __RAM_SHADOW__(0xCA0)
#define BlockAddress_ROM_Step132                                     __ROM_DEFAULT__(0x7E8)
 
#define BlockAddress_RAM_Step133                                     __RAM_SHADOW__(0xCA8)
#define BlockAddress_ROM_Step133                                     __ROM_DEFAULT__(0x7F0)
 
#define BlockAddress_RAM_Step134                                     __RAM_SHADOW__(0xCB0)
#define BlockAddress_ROM_Step134                                     __ROM_DEFAULT__(0x7F8)
 
#define BlockAddress_RAM_Step135                                     __RAM_SHADOW__(0xCB8)
#define BlockAddress_ROM_Step135                                     __ROM_DEFAULT__(0x800)
 
#define BlockAddress_RAM_Step136                                     __RAM_SHADOW__(0xCC0)
#define BlockAddress_ROM_Step136                                     __ROM_DEFAULT__(0x808)
 
#define BlockAddress_RAM_Step137                                     __RAM_SHADOW__(0xCC8)
#define BlockAddress_ROM_Step137                                     __ROM_DEFAULT__(0x810)
 
#define BlockAddress_RAM_Step138                                     __RAM_SHADOW__(0xCD0)
#define BlockAddress_ROM_Step138                                     __ROM_DEFAULT__(0x818)
 
#define BlockAddress_RAM_Step139                                     __RAM_SHADOW__(0xCD8)
#define BlockAddress_ROM_Step139                                     __ROM_DEFAULT__(0x820)
 
#define BlockAddress_RAM_Step140                                     __RAM_SHADOW__(0xCE0)
#define BlockAddress_ROM_Step140                                     __ROM_DEFAULT__(0x828)
 
#define BlockAddress_RAM_Step141                                     __RAM_SHADOW__(0xCE8)
#define BlockAddress_ROM_Step141                                     __ROM_DEFAULT__(0x830)
 
#define BlockAddress_RAM_Step142                                     __RAM_SHADOW__(0xCF0)
#define BlockAddress_ROM_Step142                                     __ROM_DEFAULT__(0x838)
 
#define BlockAddress_RAM_Step143                                     __RAM_SHADOW__(0xCF8)
#define BlockAddress_ROM_Step143                                     __ROM_DEFAULT__(0x840)
 
#define BlockAddress_RAM_Step144                                     __RAM_SHADOW__(0xD00)
#define BlockAddress_ROM_Step144                                     __ROM_DEFAULT__(0x848)
 
#define BlockAddress_RAM_System_Context_0                            __RAM_SHADOW__(0xD08)
#define BlockAddress_ROM_System_Context_0                            __ROM_DEFAULT__(0x850)
 
#define BlockAddress_RAM_System_Context_1                            __RAM_SHADOW__(0xD14)
#define BlockAddress_ROM_System_Context_1                            __ROM_DEFAULT__(0x85C)
 
#define BlockAddress_RAM_System_Context_2                            __RAM_SHADOW__(0xD20)
#define BlockAddress_ROM_System_Context_2                            __ROM_DEFAULT__(0x868)
 
#define BlockAddress_RAM_Cycle_Delays_MB                             __RAM_SHADOW__(0xD2C)
#define BlockAddress_ROM_Cycle_Delays_MB                             __ROM_DEFAULT__(0x874)
 
#define BlockAddress_RAM_Haptic_Config_MB                            __RAM_SHADOW__(0xD38)
#define BlockAddress_ROM_Haptic_Config_MB                            __ROM_DEFAULT__(0x884)
 
#define BlockAddress_RAM_EOL_Mapping_MB                              __RAM_SHADOW__(0xD44)
#define BlockAddress_ROM_EOL_Mapping_MB                              __ROM_DEFAULT__(0x894)
 
#define BlockAddress_RAM_CAN_INPUT_SIGNALS                           __RAM_SHADOW__(0xD50)
#define BlockAddress_ROM_CAN_INPUT_SIGNALS                           __ROM_DEFAULT__(0x8A0)
 
#define BlockAddress_RAM_HW_VERSION                                  __RAM_SHADOW__(0xD54)
#define BlockAddress_ROM_HW_VERSION                                  __ROM_DEFAULT__(0x8A8)
 
#define BlockAddress_RAM_PCBA_PPN                                    __RAM_SHADOW__(0xD58)
#define BlockAddress_ROM_PCBA_PPN                                    __ROM_DEFAULT__(0x8B0)
 
#define BlockAddress_RAM_HW_PARTNUMBER                               __RAM_SHADOW__(0xD64)
#define BlockAddress_ROM_HW_PARTNUMBER                               __ROM_DEFAULT__(0x8C0)
 
 
/*************************************************************************
Declaration of constant data
*************************************************************************/
 
/*************************************************************************
Declaration of functions
*************************************************************************/
 
/*************************************************************************
Evolution of the component
 
Created by: C. Dibourg
 
$Log: Nvp_alias.h  $
Revision 1.15.1.26 2024/03/22 10:46:46CET Emanuel Jivan (emanuel.jivan) 
HW Partnumber implementation.
 
 
*************************************************************************/
 
/* end of file */
 
#endif /* NVP_ALIAS_H_ */
 
