/*************************************************************************
                                                                          
AUTOLIV ELECTRONIC document.                                              
                                                                          
-------------------------------------                                     
                                                                          
DUPLICATION or DISCLOSURE PROHIBITED without prior written consent        
                                                                          
**************************************************************************
                                                                          
This file Nvp_MemoryMapping.h is generated by the Excel document SBE_4G_NVP_layout.xls
when using "Generate All" button
                                                                          
Date and time of generation of files:     3/21/2024 / 8:02:06 PM
 
Current revision: $Revision: 1.16.1.26 $
Checked in:       $Date: 2024/03/22 10:46:46CET $
 
*************************************************************************/
                                                                          
#ifndef NVP_MEMORYMAPPING_H_
#define NVP_MEMORYMAPPING_H_ 1
                                                                          
#include "common.h"
#include "Platform_Types.h"
                                                                          
/*************************************************************************
Other components external interface inclusion
*************************************************************************/
                                                                          
/*************************************************************************
Declaration of constants
*************************************************************************/
                                                                          
#define NVP_KU8_MAJOR_VERSION_CALIB                        ( 0x32u )
#define NVP_KU8_MINOR_VERSION_CALIB                        ( 0x32u )
#define NVP_KU8_SUBVERSION_CALIB                           ( 0x30u )
 
#define NVP_KU8_MAJOR_VERSION_DEFAULT                      ( 0x32u )
#define NVP_KU8_MINOR_VERSION_DEFAULT                      ( 0x32u )
#define NVP_KU8_SUBVERSION_DEFAULT                         ( 0x30u )
 
#define NVP_ROM_DEFAULT_START_ADDRESS                      (0x800FF020)
#define NVP_CALIBRATION_START_ADDRESS                      (0x800FFA20)
#define NVP_SHADOW_RAM_START_ADDRESS                       (0x70017500)
 
/*************************************************************************
Declaration of macros
*************************************************************************/
 
#ifndef __RAM_SHADOW__
#define __RAM_SHADOW__(x)         ((NVP_SHADOW_RAM_START_ADDRESS & 0xFFFFF000)+x)
#else
#define __RAM_SHADOW__(x)
#endif
#ifndef __ROM_DEFAULT__
#define __ROM_DEFAULT__(x)        ((NVP_ROM_DEFAULT_START_ADDRESS & 0xFFFFF000)+x)
#else
#define __ROM_DEFAULT__(x)
#endif
#ifndef __CALIBRATION__
#define __CALIBRATION__(x)        ((NVP_CALIBRATION_START_ADDRESS & 0xFFFFF000)+x)
#else
#define __CALIBRATION__(x)
#endif 
 
/*************************************************************************
Declaration of types
*************************************************************************/
 
/*************************************************************************
Declaration of variables
*************************************************************************/
 
/*************************************************************************
Declaration of constant data
*************************************************************************/
 
/*************************************************************************
Declaration of functions
*************************************************************************/
 
/*************************************************************************
Evolution of the component
 
Created by: C. Dibourg
 
$Log: Nvp_MemoryMapping.h  $
Revision 1.16.1.26 2024/03/22 10:46:46CET Emanuel Jivan (emanuel.jivan) 
HW Partnumber implementation.
 
 
*************************************************************************/
 
/* end of file */
 
#endif /* NVP_MEMORYMAPPING_H_ */
 
