#ifndef __TS_ENVIRO_H
#define __TS_ENVIRO_H

#ifdef TS_MASTER

	const char * _TessyEnvironment[] = {
	"Mode", NULL,
	"TestobjectBreakpoint", NULL,
	"TestobjectId", "2035",
	"PROJECTROOT", "S:\\Tools\\Tessy\\Workspace",
	"ASAP File", "",
	"ASAP Module", "",
	"ASAP Project", "",
	"Alternate Breakpoint", "",
	"Batchtest Wait Time", "0",
	"Buffer Size", "10240",
	"C++ Module", "1",
	"Call Count Size", "8",
	"Check Call Trace Size", "",
	"Check Driver Layers", "",
	"Collect All Enums", "0",
	"Collect const Variables", "0",
	"Comm Buffer Integrity", "0",
	"Comm Checksum", "0",
	"Comm File Compression", "0",
	"Comm Transfer Limit", "0",
	"Compiler", "GNU GCC (C++)",
	"Compiler Call", "g++.exe $(Compiler Dialect) -c $(USEROPTIONS) -DTESSY -o $(OUTPUT) $(INPUT)",
	"Compiler Commandline", "",
	"Compiler Concurrency", "4",
	"Compiler Defines", "BRS_COMP_TASKING=1,AURIX2G_MCAL_DEMOAPP=1,__ACCUM_BIT__=64,__ACCUM_INT_BIT__=17,__ATOMIC_INT_LOCK_FREE__=1,__ATOMIC_LONG_LOCK_FREE__=1,__CHAR_BIT__=8,__CHAR_MAX=SCHAR_MAX,__CHAR_MIN=SCHAR_MIN,__CORE_TC162__=1,__CPU__=tc33x,__CPU_TC33X__=1,__CTC__=1,__DSPC__=1,__DSPC_VERSION__=200001L,__FPU__=1,__FRACT_BIT__=32,__INT_BIT__=32,__INTPTR_BIT__=32,__LACCUM_BIT__=64,__LACCUM_INT_BIT__=17,__LFRACT_BIT__=32,__LLONG_BIT__=64,__LONG_BIT__=32,__PROF_ENABLE__=0,__PTRDIFF_BIT__=32,__PTRDIFF_MAX=INT32_MAX,__PTRDIFF_MIN=INT32_MIN,__SACCUM_BIT__=64,__SACCUM_INT_BIT__=17,__SFRACT_BIT__=16,__SHORT_BIT__=16,__SINGLE_FP__=1,__SIZE_BIT__=32,__SIZE_MAX=UINT32_MAX,__SIZE_MIN=0,__WCHAR_BIT__=16,__WCHAR_MAX=INT16_MAX,__WCHAR_MIN=INT16_MIN,transpose_byte=__transpose_byte,transpose_hword=__transpose_hword",
	"Compiler Dialect", "-std=gnu++11",
	"Compiler Id", "0x01",
	"Compiler Includes", "S:\\Components\\Application\\Autoliv\\BaseFunction\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\BFE\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\BFS\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\CIL\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\DIA\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\MMG\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\PAL\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\PMP\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\PRE\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\SFR\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\TL_Lib\\Implementation\\inc,S:\\Components\\Application\\Autoliv\\..\\Supplier\\_Common,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Adc,S:\\Components\\Application\\Autoliv\\..\\Supplier\\AdcIf,S:\\Components\\Application\\Autoliv\\..\\Supplier\\BswM,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Can,S:\\Components\\Application\\Autoliv\\..\\Supplier\\CanIf,S:\\Components\\Application\\Autoliv\\..\\Supplier\\CanNm,S:\\Components\\Application\\Autoliv\\..\\Supplier\\CanSM,S:\\Components\\Application\\Autoliv\\..\\Supplier\\CanTp,S:\\Components\\Application\\Autoliv\\..\\Supplier\\CanTSyn,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Com,S:\\Components\\Application\\Autoliv\\..\\Supplier\\ComM,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Crc,S:\\Components\\Application\\Autoliv\\..\\Supplier\\CryIf,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Crypto_30_LibCv,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Crypto_30_vHsm,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Csm,S:\\Components\\Application\\Autoliv\\..\\Supplier\\DaVinci_generated,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Dcm,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Dem,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Det,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Dio,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Dma,S:\\Components\\Application\\Autoliv\\..\\Supplier\\E2E,S:\\Components\\Application\\Autoliv\\..\\Supplier\\E2EXf,S:\\Components\\Application\\Autoliv\\..\\Supplier\\EcuM,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Fee,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Fls_17_Dmu,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Gpt,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Hwl\\Sfr\\TC33xA\\_Reg,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Icu_17_TimerIp,S:\\Components\\Application\\Autoliv\\..\\Supplier\\IpduM,S:\\Components\\Application\\Autoliv\\..\\Supplier\\KeyM,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Mcal_Tc3xx,S:\\Components\\Application\\Autoliv\\..\\Supplier\\McalLib,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Mcu,S:\\Components\\Application\\Autoliv\\..\\Supplier\\MemIf,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Nm,S:\\Components\\Application\\Autoliv\\..\\Supplier\\NvM,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Os,S:\\Components\\Application\\Autoliv\\..\\Supplier\\PduR,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Port,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Pwm,S:\\Components\\Application\\Autoliv\\..\\Supplier\\PwmIf,S:\\Components\\Application\\Autoliv\\..\\Supplier\\SBC,S:\\Components\\Application\\Autoliv\\..\\Supplier\\SecOC,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Spi,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Ssa,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Startup,S:\\Components\\Application\\Autoliv\\..\\Supplier\\StbM,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Stm,S:\\Components\\Application\\Autoliv\\..\\Supplier\\vSecPrim,S:\\Components\\Application\\Autoliv\\..\\Supplier\\VStdLib,S:\\Components\\Application\\Autoliv\\..\\Supplier\\Wdg_17_Scu,S:\\Components\\Application\\Autoliv\\..\\Supplier\\WdgIf,S:\\Components\\Application\\Autoliv\\..\\Supplier\\WdgM,S:\\Tools\\Tessy\\Workspace\\Stubs,S:\\Tools\\Tasking\\Installation\\TASKING_TriCore_v6.3r1p2\\ctc\\include",
	"Compiler Install Path", "C:\\PROGRA~1\\Razorcat\\Shared\\1.3\\msys32",
	"Compiler Version", "",
	"Component Test", "0",
	"Constructor Exclude List", "",
	"Conversion DLL", "none",
	"Declare Constructors List", "",
	"Default Call Trace Evaluation", "Ignore Call Trace",
	"Define Value Collapse Exclude List", "",
	"Defines Exclude List", "*TESSY*, unix, _*, *i386*, *X86*, WIN32, WINNT",
	"Deleted Constructors List", "",
	"Display Name", "GNU GCC (C++) --- Eclipse CDT - (Default)",
	"Doxygen Executable", "",
	"Doxygen Ignore Includes", "0",
	"Doxygen Input Encoding", "UTF-8",
	"Duplicated Defines Header", "",
	"Enable ASAP", "0",
	"Enable ASAP Parameter", "0",
	"Enable ASAP Test File", "1",
	"Enable C0 Coverage", "1",
	"Enable C1 Coverage", "1",
	"Enable C99", "1",
	"Enable CLANG", "1",
	"Enable CPC Coverage", "1",
	"Enable CTC++", "0",
	"Enable Collect Implicit Constructors", "1",
	"Enable Create Default Constructors", "1",
	"Enable Create Function Stubs", "0",
	"Enable Create Method Stubs", "1",
	"Enable DC Coverage", "1",
	"Enable Define Variables", "1",
	"Enable Doxygen", "0",
	"Enable EPC Coverage", "1",
	"Enable Exceptions", "1",
	"Enable FC Coverage", "1",
	"Enable Handle BOM", "0",
	"Enable Inline Functions", "1",
	"Enable MC/DC Coverage", "1",
	"Enable MCC Coverage", "1",
	"Enable Singleton Test", "0",
	"Enable Static Functions", "1",
	"Enable Static Locals", "1",
	"Enable User Includes", "0",
	"Enable const As IN", "0",
	"Enable setjmp/longjmp", "0",
	"Endianess", "-",
	"Enum Exclude List", "",
	"Enum Include List", "",
	"Environment", "(Default)",
	"ExeFile Extension", ".exe",
	"Execute Testcases Separately", "0",
	"Execution Mode", "0x02",
	"Execution Timeout", "0",
	"Execution Timeout Call", "",
	"Float Eval Epsilon", "1.0E-6",
	"Float Precision", "-1",
	"Function Stub Exclude List", "",
	"Generate Constructors", "1",
	"Generate Parameter Proxies", "0",
	"Header File Exclude List", "",
	"Header File Include List", "",
	"Hide Functions", "0",
	"IDBMake Makefile", "C:\\PROGRA~1\\Razorcat\\TESSY_4.3\\bin\\idb++.mak",
	"Init Code", "",
	"Init Definitions", "",
	"Insert External Stub At Declaration", "0",
	"Instrumentation Exclude List", "",
	"Instrumenter Consider Hide Functions", "0",
	"Instrumenter Header Exclude List", "",
	"Linker Options", "",
	"MISRA Do While Expressions", "0U, false",
	"Main Type", "0x11",
	"Make Call", "+S:/Tools/Tessy/WORKSP~1/tessy\\work\\00000419\\000004f5\\000007F3:@:mingw32-make.exe --silent -O -j 20 -f",
	"Make Command", "mingw32-make.exe",
	"Make Options", "-O -j 20",
	"Make Use One Shell", "0",
	"Makefile Template", "C:\\PROGRA~1\\Razorcat\\TESSY_4.3\\sys\\templates\\make\\ts_make_socket++.tpl",
	"Master Call", "S:/Tools/Tessy/WORKSP~1/tessy\\work\\00000419\\000004f5\\000007F3\\ts_pal_ComputeCurrentHalfBridgeN(sint32 *const)_m.exe",
	"Method Stub Exclude List", "std::*",
	"Minimum C0 Coverage", "100",
	"Minimum C1 Coverage", "100",
	"Minimum CPC Coverage", "100",
	"Minimum DC Coverage", "100",
	"Minimum EPC Coverage", "100",
	"Minimum FC Coverage", "100",
	"Minimum MC/DC Coverage", "100",
	"Minimum MCC Coverage", "100",
	"ObjFile Extension", ".o",
	"Parser Options", "",
	"Preprocessor Call", "g++.exe $(Compiler Dialect) -E -DTESSY -o $(OUTPUT) $(INPUT)",
	"Relative Path Variables", "",
	"SOURCEROOT", "S:\\Components\\Application\\Autoliv",
	"Scanner Call", "sh.exe tks.sh gcc",
	"Slave Call", "",
	"Synthetic Declarations In Source", "1",
	"TKS Template File", "C:\\PROGRA~1\\Razorcat\\TESSY_4.3\\sys\\templates\\tks\\tks-gnu.tpl",
	"Target", "Eclipse CDT",
	"Target Concurrency", "0",
	"Target Id", "0x25",
	"Target Install Path", "",
	"Target Version", "",
	"Test Data Alternate Pattern", "0x5A",
	"Test Data Pattern", "0xA5",
	"Test Object Exclude List", "std::*,_*",
	"Test Object Include List", "",
	"Time Unit", "cycles",
	"Timer Enabled", "0",
	"Timer File", "C:\\PROGRA~1\\Razorcat\\TESSY_4.3\\sys\\src\\comm\\ts_timer_gcc.c",
	"Timer Prescale", "0",
	"Timer Resolution", "1.0",
	"Type Exclude List", "",
	"Type Include List", "",
	"Type Table File", "C:\\PROGRA~1\\Razorcat\\TESSY_4.3\\sys\\compiler\\typetables\\ts_gcc_i386_typetable_c++.xml",
	"Unit Test", "1",
	"Use Alias Names", "0",
	"Variable Exclude List", "",
	"MODULEPATH", "S:/Tools/Tessy/WORKSP~1/tessy\\work\\00000419\\000004f5\\000007F3",
	"PROJECT", "no-name",
	"MODULE", "PAL",
	"CTEX File", "S:\\Tools\\Tessy\\Workspace\\tessy\\persist\\tessy\\project\\00000419\\000004f5\\.database\\.tdb\\000007F3\\testSpecification.ctex",
	"TESTOBJECT", "pal_ComputeCurrentHalfBridgeN(sint32 *const)",
	"Binary", "S:/Tools/Tessy/WORKSP~1/tessy\\work\\00000419\\000004f5\\000007F3\\ts_pal_ComputeCurrentHalfBridgeN_s.exe",
	"ModulePath", "S:/Tools/Tessy/WORKSP~1/tessy\\work\\00000419\\000004f5\\000007F3",
	"SizeOfDouble", "64",
	NULL, NULL};

	TESSY_uint32 TS_CommTransferLimit;

	TESSY_int16 CheckDriverLayers;

	TESSY_int8 GenerateBuiltinData;

	TESSY_int8 TS_CommCompress;

	TESSY_int8 TS_CommChecksum;

extern "C" {

	int8 check_tslow_connect(const char **) {return 0;}

	void TESSY_CDL_receiveCallTrace(void) {}

}

#endif

#endif /* __TS_ENVIRO_H */
