__builtin void * __alloc(__size_t);
__builtin void __free(void *);
__builtin void * __va_start(void);
__builtin __codeptr __get_return_address(void); 
__builtin void __swi(int);
__builtin void __svc(int);
__builtin unsigned int __getcpsr(void);
__builtin unsigned int __setcpsr(int, int);
__builtin unsigned int __getspsr(void);
__builtin unsigned int __setspsr(int, int);
__builtin unsigned int __getapsr(void);
__builtin unsigned int __setapsr(int, int);
__builtin unsigned int __getipsr(void);
__builtin unsigned int __setipsr(int, int);
__builtin unsigned int __getapsr(void);
__builtin unsigned int __setapsr(int, int);
__builtin void __setcpsr_c(int);
__builtin unsigned int __setcpsr(int, int);
__builtin void __setcpsr_c(int);
__builtin unsigned int __getcpsr(void);
__builtin unsigned int __setspsr(int, int);
__builtin void __setspsr_c(int);
__builtin unsigned int __getspsr(void);
__builtin unsigned int __setapsr(int, int);
__builtin void __setapsr_c(int);
__builtin unsigned int __getapsr(void);
__builtin unsigned int __setipsr(int, int);
__builtin void __setipsr_c(int);
__builtin unsigned int __getipsr(void);
__builtin void __setfpscr(int);
__builtin unsigned int __getfpscr(void);
__builtin void __setsp( __data void * stack );
__builtin void __remap_pc( void );
__builtin void __nop(void);
__builtin void __enable_irq(void);
__builtin void __disable_irq(void);
__builtin void __set_PRIMASK(unsigned int value);
__builtin unsigned int __get_PRIMASK(void);
__builtin void __enable_fault_irq(void);
__builtin void __disable_fault_irq(void);
__builtin void __set_FAULTMASK(unsigned int value);
__builtin unsigned int __get_FAULTMASK(void);
__builtin void __set_BASEPRI(unsigned int value);
__builtin unsigned int __get_BASEPRI(void);
__builtin void __set_CONTROL(unsigned int value);
__builtin unsigned int __get_CONTROL(void);
__builtin void __set_PSP(unsigned int value);
__builtin unsigned int __get_PSP(void);
__builtin void __set_MSP(unsigned int value);
__builtin unsigned int __get_MSP(void);
__builtin void __NOP(void);
__builtin void __WFI(void);
__builtin void __WFE(void);
__builtin void __SEV(void);
__builtin void __ISB(void);
__builtin void __DSB(void);
__builtin void __DMB(void);
__builtin unsigned int __REV(unsigned int value);
__builtin unsigned int __REV16(unsigned short value);
__builtin signed int __REVSH(signed int value);
__builtin unsigned int __RBIT(unsigned int value);
__builtin unsigned int __ROR(unsigned int op, unsigned int shift);
__builtin unsigned char __LDREXB(unsigned char *addr);
__builtin unsigned short __LDREXH(unsigned short *addr);
__builtin unsigned int __LDREXW(unsigned int *addr);
__builtin unsigned int __STREXB(unsigned char value, unsigned char *addr);
__builtin unsigned int __STREXH(unsigned short value, unsigned short *addr);
__builtin unsigned int __STREXW(unsigned int value, unsigned int *addr);
__builtin void __CLREX(void);
__builtin unsigned int __RRX(unsigned int value);
__builtin unsigned char __LDRBT(unsigned char *addr);
__builtin unsigned short __LDRHT(unsigned short *addr);
__builtin unsigned int __LDRT(unsigned int *addr);
__builtin void __STRBT(unsigned char value, unsigned char *addr);
__builtin void __STRHT(unsigned short value, unsigned short *addr);
__builtin void __STRT(unsigned int value, unsigned int *addr);
__builtin void __BKPT(unsigned short int);
__builtin unsigned char __CLZ(unsigned int val1);
__builtin int __SSAT(int val1, unsigned int val2);
__builtin unsigned int __USAT(unsigned int val1, unsigned int val2);
__builtin unsigned int __SADD16(unsigned int val1, unsigned int val2);
__builtin unsigned int __SASX(unsigned int val1, unsigned int val2);
__builtin unsigned int __SSAX(unsigned int val1, unsigned int val2);
__builtin unsigned int __SSUB16(unsigned int val1, unsigned int val2);
__builtin unsigned int __SADD8(unsigned int val1, unsigned int val2);
__builtin unsigned int __SSUB8(unsigned int val1, unsigned int val2);
__builtin unsigned int __QADD16(unsigned int val1, unsigned int val2);
__builtin unsigned int __QASX(unsigned int val1, unsigned int val2);
__builtin unsigned int __QSAX(unsigned int val1, unsigned int val2);
__builtin unsigned int __QSUB16(unsigned int val1, unsigned int val2);
__builtin unsigned int __QADD8(unsigned int val1, unsigned int val2);
__builtin unsigned int __QSUB8(unsigned int val1, unsigned int val2);
__builtin unsigned int __SHADD16(unsigned int val1, unsigned int val2);
__builtin unsigned int __SHASX(unsigned int val1, unsigned int val2);
__builtin unsigned int __SHSAX(unsigned int val1, unsigned int val2);
__builtin unsigned int __SHSUB16(unsigned int val1, unsigned int val2);
__builtin unsigned int __SHADD8(unsigned int val1, unsigned int val2);
__builtin unsigned int __SHSUB8(unsigned int val1, unsigned int val2);
__builtin unsigned int __UADD16(unsigned int val1, unsigned int val2);
__builtin unsigned int __UASX(unsigned int val1, unsigned int val2);
__builtin unsigned int __USAX(unsigned int val1, unsigned int val2);
__builtin unsigned int __USUB16(unsigned int val1, unsigned int val2);
__builtin unsigned int __UADD8(unsigned int val1, unsigned int val2);
__builtin unsigned int __USUB8(unsigned int val1, unsigned int val2);
__builtin unsigned int __UQADD16(unsigned int val1, unsigned int val2);
__builtin unsigned int __UQASX(unsigned int val1, unsigned int val2);
__builtin unsigned int __UQSAX(unsigned int val1, unsigned int val2);
__builtin unsigned int __UQSUB16(unsigned int val1, unsigned int val2);
__builtin unsigned int __UQADD8(unsigned int val1, unsigned int val2);
__builtin unsigned int __UQSUB8(unsigned int val1, unsigned int val2);
__builtin unsigned int __UHADD16(unsigned int val1, unsigned int val2);
__builtin unsigned int __UHASX(unsigned int val1, unsigned int val2);
__builtin unsigned int __UHSAX(unsigned int val1, unsigned int val2);
__builtin unsigned int __UHSUB16(unsigned int val1, unsigned int val2);
__builtin unsigned int __UHADD8(unsigned int val1, unsigned int val2);
__builtin unsigned int __UHSUB8(unsigned int val1, unsigned int val2);
__builtin unsigned int __SXTB16(unsigned int val1);
__builtin unsigned int __UXTB16(unsigned int val1);
__builtin unsigned int __UXTAB16(unsigned int val1, unsigned int val2);
__builtin unsigned int __SXTAB16(unsigned int val1, unsigned int val2);
__builtin unsigned int __SSAT16(unsigned int val1, unsigned int val2);
__builtin unsigned int __USAT16(unsigned int val1, unsigned int val2);
__builtin unsigned int __SMUAD(unsigned int val1, unsigned int val2);
__builtin unsigned int __SMUADX(unsigned int val1, unsigned int val2);
__builtin unsigned int __SMUSD(unsigned int val1, unsigned int val2);
__builtin unsigned int __SMUSDX(unsigned int val1, unsigned int val2);
__builtin unsigned int __QADD(unsigned int val1, unsigned int val2);
__builtin unsigned int __QSUB(unsigned int val1, unsigned int val2);
__builtin unsigned int __USAD8(unsigned int val1, unsigned int val2);
__builtin unsigned int __SEL(unsigned int val1, unsigned int val2);
__builtin unsigned int __SMLAD(unsigned int val1, unsigned int val2, unsigned int val3);
__builtin unsigned int __SMLADX(unsigned int val1, unsigned int val2, unsigned int val3);
__builtin unsigned int __SMLSD(unsigned int val1, unsigned int val2, unsigned int val3);
__builtin unsigned int __SMLSDX(unsigned int val1, unsigned int val2, unsigned int val3);
__builtin unsigned int __USADA8(unsigned int val1, unsigned int val2, unsigned int val3);
__builtin unsigned int __PKHBT(unsigned int val1, unsigned int val2, unsigned int val3);
__builtin unsigned int __PKHTB(unsigned int val1, unsigned int val2, unsigned int val3);
#if __cplusplus >= 201103L
__builtin unsigned long long int __SMLALD(unsigned int val1, unsigned int val2, unsigned long long int val3);
#endif
#if __cplusplus >= 201103L
__builtin unsigned long long int __SMLALDX(unsigned int val1, unsigned int val2, unsigned long long int val3);
#endif
#if __cplusplus >= 201103L
__builtin unsigned long long int __SMLSLD(unsigned int val1, unsigned int val2, unsigned long long int val3);
#endif
#if __cplusplus >= 201103L
__builtin unsigned long long int __SMLSLDX(unsigned int val1, unsigned int val2, unsigned long long int val3);
#endif
__builtin double __vfp_fabs(double x);
__builtin double __vfp_sqrt(double x);
__builtin double __vfp_ceil(double x);
__builtin double __vfp_floor(double x);
__builtin double __vfp_trunc(double x);
__builtin double __vfp_round(double x);
__builtin double __vfp_rint(double x);
__builtin double __vfp_nearbyint(double x);
__builtin double __vfp_fmax(double x, double y);
__builtin double __vfp_fmin(double x, double y);
__builtin double __vfp_fma(double x, double y, double z);
__builtin long __vfp_lrint(double x);
__builtin long __vfp_lround(double x);
__builtin float __vfp_fabsf(float x);
__builtin float __vfp_sqrtf(float x);
__builtin float __vfp_ceilf(float x);
__builtin float __vfp_floorf(float x);
__builtin float __vfp_truncf(float x);
__builtin float __vfp_roundf(float x);
__builtin float __vfp_rintf(float x);
__builtin float __vfp_nearbyintf(float x);
__builtin float __vfp_fmaxf(float x, float y);
__builtin float __vfp_fminf(float x, float y);
__builtin float __vfp_fmaf(float x, float y, float z);
__builtin long __vfp_lrintf(float x);
__builtin long __vfp_lroundf(float x);
__builtin long double __vfp_fabsl(long double x);
__builtin long double __vfp_sqrtl(long double x);
__builtin long double __vfp_ceill(long double x);
__builtin long double __vfp_floorl(long double x);
__builtin long double __vfp_truncl(long double x);
__builtin long double __vfp_roundl(long double x);
__builtin long double __vfp_rintl(long double x);
__builtin long double __vfp_nearbyintl(long double x);
__builtin long double __vfp_fmaxl(long double x, long double y);
__builtin long double __vfp_fminl(long double x, long double y);
__builtin long double __vfp_fmal(long double x, long double y, long double z);
__builtin long __vfp_lrintl(long double x);
__builtin long __vfp_lroundl(long double x);
