/**************************************************************************************************\
 *** 
 *** Simulink model       : PRE_TestHarness
 *** TargetLink subsystem : PRE_TestHarness/PRE_AC_PreTensioning
 *** Codefile             : PRE_PreTensioningCommon.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-25 18:13:36
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef PRE_PRETENSIONINGCOMMON_H
#define PRE_PRETENSIONINGCOMMON_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   GLOBAL_ASR4_INIT: global variables (RAM) | Width: 8
\******************************************************************************/
#define PRE_AC_PreTensioning_START_SEC_VAR_INIT_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern uint8 b8TrigOff;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

/******************************************************************************\
   UserSLGlobal: SLGlobal = { GLOBAL_ASR4 } | Width: 8
\******************************************************************************/
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern boolean bCommonAbortionConditions_PRE;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern boolean bDiagOnCANPreConditions_PRE_WithBoost;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern boolean bDiagOnCANPreConditions_PRE_WithoutBoost;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern boolean bDiagOnCanAbortionConditions_PRE;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern boolean bNoInhibitionByUVDuringTensioning_PRE;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern boolean bVehiclePreConditions_PRE_WithBoost;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern boolean bVehiclePreConditions_PRE_WithoutBoost;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   GLOBAL_FCN_ASR4: global function(s) (exported to other modules)
\******************************************************************************/
#define PRE_AC_PreTensioning_START_SEC_CODE
#include "PRE_AC_PreTensioning_MemMap.h"
extern void ManageCommonInputsForAllPRE(void);
#define PRE_AC_PreTensioning_STOP_SEC_CODE
#include "PRE_AC_PreTensioning_MemMap.h"

#endif /* PRE_PRETENSIONINGCOMMON_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
