/**************************************************************************************************\
 *** 
 *** Simulink model       : PRE_TestHarness
 *** TargetLink subsystem : PRE_TestHarness/PRE_AC_PreTensioning
 *** Codefile             : PRE_AC_PreTensioning.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-25 18:13:35
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      PRE_AC_PreTensioning
 *** Sa2                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo
 *** Sa3                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** Sa4                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutput
 ***                          s
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /ATM_GetAutoTestStatus
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /ATM_GetAutoTestStatus1
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /Dem_GetEventStatus
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /Dem_GetEventStatus1
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /Dem_GetEventStatus3
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /Dem_GetEventStatuss2
 *** Sa6                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE1
 *** Sa7                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE2
 *** Sa8                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE3
 *** Sa9                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE4
 *** Sa10                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE5
 *** Sa11                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE6
 *** Sa12                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE7
 *** Sa13                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE8
 *** Sa14                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE disabled
 *** Sa15                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext1
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext2
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext3
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext4
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext5
 *** Sa16                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctCommonPREManageInputs
 *** Sa17                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctTrigAbortCycle_AllPRE
 *** Sa18                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctCommonPREManageInputs/FctCheckUnderVoltageDuringTensio
 ***                          ningForAllPRE
 *** Sa19                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctCommonPREManageInputs/FctCommonEvaluateAbortionConditi
 ***                          ons
 *** Sa20                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctCommonPREManageInputs/FctCommonEvaluatePreConditions
 *** Sa21                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctCommonPREManageInputs/FctEvaluateTrigOffForAllPRE
 *** Sa22                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem
 *** Sa23                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE
 *** Sa24                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem1
 *** Sa25                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem2
 *** Sa26                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem3
 *** Sa27                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem4
 *** Sa28                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem5
 *** Sa29                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem6
 *** Sa30                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem7
 *** Sa31                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem8
 *** Sa32                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem9
 *** Sa33                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag
 *** Sa34                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE
 *** Sa35                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/Check end diag request
 *** Sa36                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/EvaluateDiagRequest
 *** Sa37                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/Check end diag request/Acquite end of diag request
 *** Sa38                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/Check end diag request/End of diag request
 *** Sa39                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/Check end diag request/Memorize end of diag request
 *** Sa40                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/EvaluateDiagRequest/Acquite Diag Request From DIA
 *** Sa41                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 *** valuateDiag/EvaluateDiagRequest/Acquite Diag Request From DIA/ClearDia
 ***                          gRequestCycle
 *** Sa42                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/EvaluateTriggeringSource
 *** Sa43                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/If ActionSubsystem
 *** Sa44                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/If ActionSubsystem1
 *** Sa45                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreActivationFlag
 *** Sa46                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreConditionsFlag
 *** Sa47                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_TriggeringOrder
 *** Sa48                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_bInterruptFlag
 *** Sa49                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreActivationFlag/If ActionSubsystem2
 *** Sa50                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreActivationFlag/If ActionSubsystem3
 *** Sa51                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreConditionsFlag/If ActionSubsystem4
 *** Sa52                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreConditionsFlag/If ActionSubsystem5
 *** Sa53                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_TriggeringOrder/If ActionSubsystem
 *** Sa54                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_TriggeringOrder/If ActionSubsystem1
 *** Sa55                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_bInterruptFlag/If ActionSubsystem4
 *** Sa56                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_bInterruptFlag/If ActionSubsystem5
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef PRE_AC_PRETENSIONING_C
#define PRE_AC_PRETENSIONING_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte.h"
#include "PRE_AC_PreTensioning_ARfrm.h"
#include "PRE_AC_PreTensioning.h"
#include "common.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   UserSLGlobal: SLGlobal = { GLOBAL_ASR4 } | Width: 16
\******************************************************************************/
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_b8BoostCyc__InhibitionModes;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_b8CyclesAbortedByMode;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_b8CyclesAbortedByMode_Ext;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_b8CyclesInhibitedByMode;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_b8CyclesInhibitedByMode_Ext;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_b8EndOfLifeLevelBoost;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_b8EndOfLifeNoBoost;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_b8IsCarCrashDetected;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_b8PresafeEnable;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_u8ATStatus_PreliminaryBoost;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_u8ATStatus_VBoost;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_u8PresafeLevel;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_u8RealBuckleSwitchStatus;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_u8RequestedCycle;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_u8Status_OverVoltage;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
sint16 Sa1_u8Status_UVDuringTensioning;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

/******************************************************************************\
   UserSLGlobal: SLGlobal = { GLOBAL_ASR4 } | Width: 8
\******************************************************************************/
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
uint8 Sa1_u8ExecutedCycle;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

/******************************************************************************\
   UserSLGlobal: SLGlobal = { GLOBAL_ASR4 } | Width: N.A.
\******************************************************************************/
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
struct BS_OP_Sa1_psrAlgoFlags_PRE1 Sa1_psrAlgoFlags_PRE1;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

struct BS_OP_Sa1_psrAlgoFlags_PRE2 Sa1_psrAlgoFlags_PRE2;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

struct BS_OP_Sa1_psrAlgoFlags_PRE3 Sa1_psrAlgoFlags_PRE3;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

struct BS_OP_Sa1_psrAlgoFlags_PRE3 Sa1_psrAlgoFlags_PRE4;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

struct BS_OP_Sa1_psrAlgoFlags_PRE3 Sa1_psrAlgoFlags_PRE5;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

struct BS_OP_Sa1_psrAlgoFlags_PRE3 Sa1_psrAlgoFlags_PRE6;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

struct BS_OP_Sa1_psrAlgoFlags_PRE3 Sa1_psrAlgoFlags_PRE7;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

struct BS_OP_Sa1_psrAlgoFlags_PRE3 Sa1_psrAlgoFlags_PRE8;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      PRE_AC_PreTensioning
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void PRE_AC_PreTensioning(void)
{
   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write9 */
   b8CyclesAbortedByModes_Ext = (uint8) Sa1_b8CyclesAbortedByMode_Ext;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write8 */
   b8CyclesInhibitedByModes_Ext = (uint8) Sa1_b8CyclesInhibitedByMode_Ext;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write7 */
   u8Status_EOL_PRE_WITHOUT_BOOST = (uint8) Sa1_b8EndOfLifeNoBoost;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write6 */
   u8Status_EOL_PRE_WITH_BOOST = (uint8) Sa1_b8EndOfLifeLevelBoost;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write5 */
   u8Status_OVO = (uint8) Sa1_u8Status_OverVoltage;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write4 */
   b8BoostInhibitingModes = (uint8) Sa1_b8BoostCyc__InhibitionModes;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write3 */
   u8Status_UVT = (uint8) Sa1_u8Status_UVDuringTensioning;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write2 */
   b8CyclesAbortedByModes = (uint8) Sa1_b8CyclesAbortedByMode;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write11 */
   u8ATStatus_VBoost = (uint8) Sa1_u8ATStatus_VBoost;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write10 */
   u8ATStatus_PreliminaryBoost = (uint8) Sa1_u8ATStatus_PreliminaryBoost;

   /* Data store write: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutputs/Data
       Store Write1 */
   b8CyclesInhibitedByModes = (uint8) Sa1_b8CyclesInhibitedByMode;

   /* update(s) for inport PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo/b8
      CarAcceleration */
   Rte_PRE_AC_PreTensioning_prrGlobalCarAcceleration_b8IsCarAccelerationLow = (uint8) 0;

   /* update(s) for inport PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo/b8
      IsCarCrashDetected */
   Rte_PRE_AC_PreTensioning_prrCustomerSpecific_b8IsCarCrashDetected = (uint8)
    Sa1_b8IsCarCrashDetected;

   /* update(s) for inport PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo/b8
      PresafeEnable */
   Rte_PRE_AC_PreTensioning_prrCustomerSpecific_b8PreCrashRequestEnable = (uint8)
    Sa1_b8PresafeEnable;

   /* update(s) for inport PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo/u8
      ExecutedCycle */
   Rte_PRE_AC_PreTensioning_prrExecutedCycle_u8CycleNumber = Sa1_u8ExecutedCycle;

   /* update(s) for inport PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo/u8
      FilteredBuckleSwitchStatus */
   Rte_PRE_AC_PreTensioning_prrBuckleDoorSwitch_u8BuckleSwitch = (uint8)
    Sa1_u8RealBuckleSwitchStatus;

   /* update(s) for inport PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo/u8
      PresafeLevel */
   Rte_PRE_AC_PreTensioning_prrPreCrashSeverityLevel_u8PreCrashSeverityLevel = (uint8)
    Sa1_u8PresafeLevel;

   /* update(s) for inport PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo/u8
      RequestedCycle */
   Rte_PRE_AC_Pre__iagRequestCycle = (uint8) Sa1_u8RequestedCycle;

   /* call of function: PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo */
   Task_PRE_runPr__sioning_Wrapper();

   /* BusOutport: PRE_AC_PreTensioning/psrAlgoFlags_PRE8 */
   Sa1_psrAlgoFlags_PRE8.Sa1_signal1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE8_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRE8.Sa1_signal2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE8_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRE8.Sa1_signal3 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE8_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRE8.Sa1_signal4 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE8_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRE8.Sa1_signal5 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE8_u8TriggeringSource;

   /* BusOutport: PRE_AC_PreTensioning/psrAlgoFlags_PRE7 */
   Sa1_psrAlgoFlags_PRE7.Sa1_signal1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE7_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRE7.Sa1_signal2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE7_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRE7.Sa1_signal3 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE7_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRE7.Sa1_signal4 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE7_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRE7.Sa1_signal5 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE7_u8TriggeringSource;

   /* BusOutport: PRE_AC_PreTensioning/psrAlgoFlags_PRE6 */
   Sa1_psrAlgoFlags_PRE6.Sa1_signal1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE6_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRE6.Sa1_signal2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE6_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRE6.Sa1_signal3 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE6_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRE6.Sa1_signal4 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE6_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRE6.Sa1_signal5 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE6_u8TriggeringSource;

   /* BusOutport: PRE_AC_PreTensioning/psrAlgoFlags_PRE5 */
   Sa1_psrAlgoFlags_PRE5.Sa1_signal1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE5_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRE5.Sa1_signal2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE5_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRE5.Sa1_signal3 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE5_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRE5.Sa1_signal4 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE5_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRE5.Sa1_signal5 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE5_u8TriggeringSource;

   /* BusOutport: PRE_AC_PreTensioning/psrAlgoFlags_PRE4 */
   Sa1_psrAlgoFlags_PRE4.Sa1_signal1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE4_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRE4.Sa1_signal2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE4_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRE4.Sa1_signal3 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE4_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRE4.Sa1_signal4 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE4_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRE4.Sa1_signal5 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE4_u8TriggeringSource;

   /* BusOutport: PRE_AC_PreTensioning/psrAlgoFlags_PRE3 */
   Sa1_psrAlgoFlags_PRE3.Sa1_signal1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE3_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRE3.Sa1_signal2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE3_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRE3.Sa1_signal3 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE3_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRE3.Sa1_signal4 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE3_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRE3.Sa1_signal5 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE3_u8TriggeringSource;

   /* BusOutport: PRE_AC_PreTensioning/psrAlgoFlags_PRE2 */
   Sa1_psrAlgoFlags_PRE2.Sa1_b8TriggerFlag_PRE2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE2_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRE2.Sa1_b8InterruptFlag_PRE2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE2_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRE2.Sa1_b8PreActivationFlag_PRE2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE2_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRE2.Sa1_b8PreConditionsFlag_PRE2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE2_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRE2.Sa1_u8TriggeringSource_PRE2 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE2_u8TriggeringSource;

   /* BusOutport: PRE_AC_PreTensioning/psrAlgoFlags_PRE1 */
   Sa1_psrAlgoFlags_PRE1.Sa1_b8TriggerFlag_PRE1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE1_b8TriggerFlag;
   Sa1_psrAlgoFlags_PRE1.Sa1_b8InterruptFlag_PRE1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE1_b8InterruptFlag;
   Sa1_psrAlgoFlags_PRE1.Sa1_b8PreActivationFlag_PRE1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE1_b8PreActivationFlag;
   Sa1_psrAlgoFlags_PRE1.Sa1_b8PreConditionsFlag_PRE1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE1_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_PRE1.Sa1_u8TriggeringSource_PRE1 = (sint16)
    Rte_PRE_AC_PreTensioning_psrAlgo_Flags_PRE1_u8TriggeringSource;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* PRE_AC_PRETENSIONING_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
