/**************************************************************************************************\
 *** 
 *** Simulink model       : PRE_TestHarness
 *** TargetLink subsystem : PRE_TestHarness/PRE_AC_PreTensioning
 *** Codefile             : PRE_Config.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-25 18:13:36
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      PRE_AC_PreTensioning
 *** Sa2                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo
 *** Sa3                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** Sa4                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/WriteSystemContextOutput
 ***                          s
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /ATM_GetAutoTestStatus
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /ATM_GetAutoTestStatus1
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /Dem_GetEventStatus
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /Dem_GetEventStatus1
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /Dem_GetEventStatus3
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /Dem_GetEventStatuss2
 *** Sa6                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE1
 *** Sa7                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE2
 *** Sa8                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE3
 *** Sa9                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE4
 *** Sa10                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE5
 *** Sa11                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE6
 *** Sa12                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE7
 *** Sa13                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /MergeFlags_PRE8
 *** Sa14                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE disabled
 *** Sa15                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext1
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext2
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext3
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext4
 *** Sa5                      PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /SCA_runCheckSystemContext5
 *** Sa16                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctCommonPREManageInputs
 *** Sa17                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctTrigAbortCycle_AllPRE
 *** Sa18                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctCommonPREManageInputs/FctCheckUnderVoltageDuringTensio
 ***                          ningForAllPRE
 *** Sa19                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctCommonPREManageInputs/FctCommonEvaluateAbortionConditi
 ***                          ons
 *** Sa20                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctCommonPREManageInputs/FctCommonEvaluatePreConditions
 *** Sa21                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctCommonPREManageInputs/FctEvaluateTrigOffForAllPRE
 *** Sa22                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem
 *** Sa23                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 ***                          /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE
 *** Sa24                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem1
 *** Sa25                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem2
 *** Sa26                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem3
 *** Sa27                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem4
 *** Sa28                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem5
 *** Sa29                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem6
 *** Sa30                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem7
 *** Sa31                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem8
 *** Sa32                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Switch Cas
 ***                          e ActionSubsystem9
 *** Sa33                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag
 *** Sa34                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE
 *** Sa35                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/Check end diag request
 *** Sa36                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/EvaluateDiagRequest
 *** Sa37                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/Check end diag request/Acquite end of diag request
 *** Sa38                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/Check end diag request/End of diag request
 *** Sa39                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/Check end diag request/Memorize end of diag request
 *** Sa40                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 ***                          valuateDiag/EvaluateDiagRequest/Acquite Diag Request From DIA
 *** Sa41                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/E
 *** valuateDiag/EvaluateDiagRequest/Acquite Diag Request From DIA/ClearDia
 ***                          gRequestCycle
 *** Sa42                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/EvaluateTriggeringSource
 *** Sa43                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/If ActionSubsystem
 *** Sa44                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/If ActionSubsystem1
 *** Sa45                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreActivationFlag
 *** Sa46                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreConditionsFlag
 *** Sa47                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_TriggeringOrder
 *** Sa48                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_bInterruptFlag
 *** Sa49                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreActivationFlag/If ActionSubsystem2
 *** Sa50                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreActivationFlag/If ActionSubsystem3
 *** Sa51                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreConditionsFlag/If ActionSubsystem4
 *** Sa52                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_PreConditionsFlag/If ActionSubsystem5
 *** Sa53                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_TriggeringOrder/If ActionSubsystem
 *** Sa54                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_TriggeringOrder/If ActionSubsystem1
 *** Sa55                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_bInterruptFlag/If ActionSubsystem4
 *** Sa56                     PRE_AC_PreTensioning/PRE_AC_PreTensioningAlgo/PRE_runPreTensioningAlgo
 *** /PRE enabled/FctTrigAbortCycle_AllPRE/For IteratorSubsystem/Algo PRE/F
 ***                          ctTriggPRE/ToFormatFlag_bInterruptFlag/If ActionSubsystem5
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef PRE_CONFIG_C
#define PRE_CONFIG_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "PRE_Config.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   PRE_Config_Calibrations: Calibratable global variables, which are declared in a user-written head
   er file | Width: 8
\******************************************************************************/
boolean pre_abPrevDiagOrder[8] = 
{
   /* [0..7] */ 0, 0, 0, 0, 0, 0, 0, 0
   /* 0., 0., 0., 0., 0., 0., 0., 0. */
};
boolean pre_abPrevEndDiagReq[8] = 
{
   /* [0..7] */ 0, 0, 0, 0, 0, 0, 0, 0
   /* 0., 0., 0., 0., 0., 0., 0., 0. */
};
uint8 pre_au8PrevTriggeringSource[8] = 
{
   /* [0..7] */ 0, 0, 0, 0, 0, 0, 0, 0
   /* 0., 0., 0., 0., 0., 0., 0., 0. */
};
uint8 CAL_B8_PRE_FCT_ENABLED = 170; /* Description: Belt Parking functions availability */
uint8 CFG_KU8_PRE_CYCLE_ID_PRE_00 = 0; /* Description: Smooth release */
uint8 CFG_KU8_PRE_CYCLE_ID_PRE_01 = 1; /* Description: Smooth release */
uint8 CFG_KU8_PRE_CYCLE_ID_PRE_02 = 2; /* Description: Smooth release */
uint8 CFG_KU8_PRE_CYCLE_ID_PRE_03 = 3; /* Description: Smooth release */
uint8 CFG_KU8_PRE_CYCLE_ID_PRE_04 = 4; /* Description: Smooth release */
uint8 CFG_KU8_PRE_CYCLE_ID_PRE_05 = 5; /* Description: Smooth release */
uint8 CFG_KU8_PRE_CYCLE_ID_PRE_06 = 6; /* Description: Smooth release */
uint8 CFG_KU8_PRE_CYCLE_ID_PRE_07 = 7; /* Description: Smooth release */
uint8 CFG_KU8_PRE_CYCLE_WBOOST_NB = 1;
uint8 CFG_KU8_PRE_CYCLE_WO_BOOST_NB = 7;
uint8 pre_kau8CyclesList[8] = 
{
   /* [0..7] */ 0, 1, 2, 3, 4, 5, 6, 7
   /* 0., 1., 2., 3., 4., 5., 6., 7. */
};
uint8 pre_kau8PresafeList[8] = 
{
   /* [0..7] */ 0, 1, 2, 3, 4, 5, 6, 7
   /* 0., 1., 2., 3., 4., 5., 6., 7. */
};

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* PRE_CONFIG_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
