/**************************************************************************************************\
 *** 
 *** Simulink model       : BFS_TestHarness
 *** TargetLink subsystem : BFS_TestHarness/BFS_AC_BeltFunctionSelection
 *** Codefile             : BFS_BeltFunctionSelection.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-24 08:33:44
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      BFS_AC_BeltFunctionSelection
 *** Sa2                      BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection
 *** Sa3                      BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBe
 ***                          ltFunctionSelection
 *** Sa4                      BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBe
 ***                          ltFunctionSelection/For IteratorSubsystem
 *** Sa5                      BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBe
 ***                          ltFunctionSelection/Subsystem
 *** Sa6                      BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBe
 ***                          ltFunctionSelection/For IteratorSubsystem/If ActionSubsystem
 *** Sa7                      BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBe
 ***                          ltFunctionSelection/For IteratorSubsystem/If ActionSubsystem1
 *** Sa8                      BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBe
 ***                          ltFunctionSelection/For IteratorSubsystem/If ActionSubsystem2
 *** Sa9                      BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBe
 ***                          ltFunctionSelection/Subsystem/If ActionSubsystem
 *** Sa10                     BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBe
 ***                          ltFunctionSelection/Subsystem/If ActionSubsystem1
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef BFS_BELTFUNCTIONSELECTION_C
#define BFS_BELTFUNCTIONSELECTION_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_BFS_AC_BeltFunctionSelection.h"
#include "NVP_Generated.h"
#include "common.h"
#include "BFS_BeltFunctionSelection.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      BFS_runBeltFunctionSelection
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
#define BFS_AC_BeltFunctionSelection_START_SEC_CODE
#include "BFS_AC_BeltFunctionSelection_MemMap.h"

FUNC(void, BFS_AC_BeltFunctionSelection_CODE) BFS_runBeltFunctionSelection(void)
{
   /* STATIC_DISP_2: static observable variables (RAM) | Width: 8 */
   b8AlgorithmFlagsStatusType au8IntFlags[25] = 
   {
      /* [0..9] */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
      /* [10..19] */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
      /* [20..24] */ 0, 0, 0, 0, 0
      /* 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
      0., 0., 0., 0., 0. */
   }; /* Label: COD_BFS_000102
[COVERS: DSG_BFS_00001] */
   b8AlgorithmFlagsStatusType au8TrigFlags[25] = 
   {
      /* [0..9] */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
      /* [10..19] */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
      /* [20..24] */ 0, 0, 0, 0, 0
      /* 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
      0., 0., 0., 0., 0. */
   }; /* Label: COD_BFS_000101
[COVERS: DSG_BFS_00002] */
   uint8 u8ExecutedCycleBFE;

   /* SLLocal: Default storage class for local variables | Width: 16 */
   sint16 Aux_S16;
   sint16 Sa4_For_Iterator_it;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   boolean Sa4_Logical_Operator;
   boolean Sa4_Relational_Operator3;
   uint8 u8LocPrevSelectedCycle;

   /* SLLocalInit: Default storage class for local variables with init value | Width: 8 */
   uint8 u8LastExecutedCycleFiltered;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
    */
   static uint8 X_u8LocalSelectedCycle = 255;

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo01__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo01_Flags_b8InterruptFlag(&(au8IntFlags[0]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo02__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo02_Flags_b8InterruptFlag(&(au8IntFlags[1]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo03__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo03_Flags_b8InterruptFlag(&(au8IntFlags[2]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo04__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo04_Flags_b8InterruptFlag(&(au8IntFlags[3]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo05__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo05_Flags_b8InterruptFlag(&(au8IntFlags[4]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo06__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo06_Flags_b8InterruptFlag(&(au8IntFlags[5]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo07__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo07_Flags_b8InterruptFlag(&(au8IntFlags[6]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo08__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo08_Flags_b8InterruptFlag(&(au8IntFlags[7]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo09__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo09_Flags_b8InterruptFlag(&(au8IntFlags[8]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo10__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo10_Flags_b8InterruptFlag(&(au8IntFlags[9]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo11__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo11_Flags_b8InterruptFlag(&(au8IntFlags[10]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo12__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo12_Flags_b8InterruptFlag(&(au8IntFlags[11]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo13__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo13_Flags_b8InterruptFlag(&(au8IntFlags[12]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo14__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo14_Flags_b8InterruptFlag(&(au8IntFlags[13]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo15__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo15_Flags_b8InterruptFlag(&(au8IntFlags[14]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo16__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo16_Flags_b8InterruptFlag(&(au8IntFlags[15]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo17__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo17_Flags_b8InterruptFlag(&(au8IntFlags[16]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo18__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo18_Flags_b8InterruptFlag(&(au8IntFlags[17]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo19__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo19_Flags_b8InterruptFlag(&(au8IntFlags[18]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo20__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo20_Flags_b8InterruptFlag(&(au8IntFlags[19]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo21__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo21_Flags_b8InterruptFlag(&(au8IntFlags[20]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo22__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo22_Flags_b8InterruptFlag(&(au8IntFlags[21]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo23__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo23_Flags_b8InterruptFlag(&(au8IntFlags[22]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo24__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo24_Flags_b8InterruptFlag(&(au8IntFlags[23]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo25__InterruptFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain */
   Rte_Read_prrAlgo25_Flags_b8InterruptFlag(&(au8IntFlags[24]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo01__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo01_Flags_b8TriggerFlag(&(au8TrigFlags[0]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo02__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo02_Flags_b8TriggerFlag(&(au8TrigFlags[1]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo03__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo03_Flags_b8TriggerFlag(&(au8TrigFlags[2]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo04__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo04_Flags_b8TriggerFlag(&(au8TrigFlags[3]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo05__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo05_Flags_b8TriggerFlag(&(au8TrigFlags[4]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo06__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo06_Flags_b8TriggerFlag(&(au8TrigFlags[5]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo07__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo07_Flags_b8TriggerFlag(&(au8TrigFlags[6]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo08__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo08_Flags_b8TriggerFlag(&(au8TrigFlags[7]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo09__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo09_Flags_b8TriggerFlag(&(au8TrigFlags[8]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo10__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo10_Flags_b8TriggerFlag(&(au8TrigFlags[9]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo11__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo11_Flags_b8TriggerFlag(&(au8TrigFlags[10]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo12__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo12_Flags_b8TriggerFlag(&(au8TrigFlags[11]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo13__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo13_Flags_b8TriggerFlag(&(au8TrigFlags[12]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo14__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo14_Flags_b8TriggerFlag(&(au8TrigFlags[13]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo15__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo15_Flags_b8TriggerFlag(&(au8TrigFlags[14]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo16__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo16_Flags_b8TriggerFlag(&(au8TrigFlags[15]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo17__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo17_Flags_b8TriggerFlag(&(au8TrigFlags[16]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo18__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo18_Flags_b8TriggerFlag(&(au8TrigFlags[17]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo19__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo19_Flags_b8TriggerFlag(&(au8TrigFlags[18]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo20__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo20_Flags_b8TriggerFlag(&(au8TrigFlags[19]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo21__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo21_Flags_b8TriggerFlag(&(au8TrigFlags[20]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo22__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo22_Flags_b8TriggerFlag(&(au8TrigFlags[21]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo23__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo23_Flags_b8TriggerFlag(&(au8TrigFlags[22]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo24__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo24_Flags_b8TriggerFlag(&(au8TrigFlags[23]));

   /* TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/DRP_prrAlgo25__b8TriggerFlag
      # combined # Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
      ctionSelection/Gain2 */
   Rte_Read_prrAlgo25_Flags_b8TriggerFlag(&(au8TrigFlags[24]));

   /* Gain: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunctionSelectio
      n/Gain1
      # combined # TargetLink inport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_
      AC_runBeltFunctionSelection/DRA_prrExecut__u8CycleNumber */
   u8ExecutedCycleBFE = Rte_IRead_BFS_runBeltFunctionSelection_prrExecutedCycle_u8CycleNumber();

   /* # combined # Relational: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runB
      eltFunctionSelection/Subsystem/Relational Operator
      # combined # update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_BeltFun
      ctionSelection/BFS_AC_runBeltFunctionSelection/Gain1 */
   if (u8ExecutedCycleBFE >= KU8_NB_MAX_CYCLES) {
      /* Reference of merge block: Merge BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/B
         FS_AC_runBeltFunctionSelection/Subsystem/Merge
         update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelec
         tion/BFS_AC_runBeltFunctionSelection/Subsystem/If Action
         Subsystem/KU8_NO_CYCLE */
      u8LastExecutedCycleFiltered = KU8_NO_CYCLE;
   }
   else {
      /* Switch: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunctionSel
         ection/Subsystem/If Action Subsystem1/Switch
         BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunctionSelection/S
         ubsystem/If Action Subsystem1/Switch: Omitted comparison with constant.
         # combined # Relational: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_r
         unBeltFunctionSelection/Subsystem/If Action Subsystem1/Relational Operator
         # combined # Selector: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_run
         BeltFunctionSelection/Subsystem/If Action Subsystem1/Selector
         # combined # update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_Belt
         FunctionSelection/BFS_AC_runBeltFunctionSelection/Gain
         # combined # BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFuncti
         onSelection/Subsystem/If Action Subsystem1/Rescaler
         # combined # update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_Belt
         FunctionSelection/BFS_AC_runBeltFunctionSelection/Gain1 */
      if (KB8_ALGO_FLAG_ON == au8IntFlags[u8ExecutedCycleBFE]) {
         /* Switch: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunction
            Selection/Subsystem/If Action Subsystem1/Switch
            # combined # Reference of merge block: Merge BFS_AC_BeltFunctionSelection/BFS_AC_BeltFun
            ctionSelection/BFS_AC_runBeltFunctionSelection/Subsystem/Merge
            update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSe
            lection/BFS_AC_runBeltFunctionSelection/Subsystem/If Action
            Subsystem1/Switch */
         u8LastExecutedCycleFiltered = KU8_NO_CYCLE;
      }
      else {
         /* Switch: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunction
            Selection/Subsystem/If Action Subsystem1/Switch
            # combined # Reference of merge block: Merge BFS_AC_BeltFunctionSelection/BFS_AC_BeltFun
            ctionSelection/BFS_AC_runBeltFunctionSelection/Subsystem/Merge
            update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSe
            lection/BFS_AC_runBeltFunctionSelection/Subsystem/If Action
            Subsystem1/Switch
            # combined # update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_B
            eltFunctionSelection/BFS_AC_runBeltFunctionSelection/Gain1 */
         u8LastExecutedCycleFiltered = u8ExecutedCycleBFE;
      }
   }
   Aux_S16 = (sint16) (((sint16) KU8_NB_MAX_CYCLES) - 1);
   for (Sa4_For_Iterator_it = 0; Sa4_For_Iterator_it <= Aux_S16; Sa4_For_Iterator_it++)
   {
      /* Switch: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunctionSel
         ection/For Iterator Subsystem/Switch
         BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunctionSelection/F
         or Iterator Subsystem/Switch: Omitted comparison with constant.
         # combined # Relational: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_r
         unBeltFunctionSelection/For Iterator Subsystem/Relational Operator
         # combined # BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFuncti
         onSelection/For Iterator Subsystem/Rescaler */
      if (KU8_ZERO == ((uint8) Sa4_For_Iterator_it)) {
         /* Switch: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunction
            Selection/For Iterator Subsystem/Switch */
         u8LocPrevSelectedCycle = u8LastExecutedCycleFiltered;
      }
      else {
         /* Switch: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunction
            Selection/For Iterator Subsystem/Switch
            # combined # Unit delay: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_A
            C_runBeltFunctionSelection/For Iterator Subsystem/Unit Delay */
         u8LocPrevSelectedCycle = X_u8LocalSelectedCycle;
      }

      /* Relational: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunctio
         nSelection/For Iterator Subsystem/Relational Operator3 */
      Sa4_Relational_Operator3 = u8LocPrevSelectedCycle == KU8_NO_CYCLE;

      /* Logical: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunctionSe
         lection/For Iterator Subsystem/Logical Operator
         # combined # Relational: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_r
         unBeltFunctionSelection/For Iterator Subsystem/Relational Operator2
         # combined # Relational: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_r
         unBeltFunctionSelection/For Iterator Subsystem/Relational Operator1
         # combined # Selector: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_run
         BeltFunctionSelection/For Iterator Subsystem/Selector
         # combined # BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFuncti
         onSelection/For Iterator Subsystem/Rescaler
         # combined # Selector: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_run
         BeltFunctionSelection/For Iterator Subsystem/Selector1
         # combined # update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_Belt
         FunctionSelection/BFS_AC_runBeltFunctionSelection/Gain
         # combined # BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFuncti
         onSelection/For Iterator Subsystem/Rescaler */
      Sa4_Logical_Operator = (KB8_ALGO_FLAG_ON == au8TrigFlags[(uint8) Sa4_For_Iterator_it]) &&
       (KB8_ALGO_FLAG_ON != au8IntFlags[(uint8) Sa4_For_Iterator_it]);

      /* # combined # Logical: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runB
         eltFunctionSelection/For Iterator Subsystem/Logical Operator1 */
      if (Sa4_Relational_Operator3 && Sa4_Logical_Operator) {
         /* Reference of merge block: Merge BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelectio
            n/BFS_AC_runBeltFunctionSelection/For Iterator Subsystem/Merge
            update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSe
            lection/BFS_AC_runBeltFunctionSelection/For Iterator
            Subsystem/If Action
            Subsystem/u8ForIndex
            # combined # BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFun
            ctionSelection/For Iterator Subsystem/Rescaler
            # combined # Unit delay: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_A
            C_runBeltFunctionSelection/For Iterator Subsystem/Unit Delay */
         X_u8LocalSelectedCycle = (uint8) Sa4_For_Iterator_it;
      }
      else {
         /* # combined # Logical: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_r
            unBeltFunctionSelection/For Iterator Subsystem/Logical Operator3
            # combined # Logical: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_r
            unBeltFunctionSelection/For Iterator Subsystem/Logical Operator2 */
         if ((!(Sa4_Relational_Operator3)) && Sa4_Logical_Operator) {
            /* Switch: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunct
               ionSelection/For Iterator Subsystem/If Action Subsystem1/Switch
               BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFunctionSelec
               tion/For Iterator Subsystem/If Action Subsystem1/Switch: Omitted comparison with cons
               tant.
               # combined # Relational: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BF
               S_AC_runBeltFunctionSelection/For Iterator Subsystem/If Action Subsystem1/Relational 
               Operator
               # combined # Selector: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_
               AC_runBeltFunctionSelection/For Iterator Subsystem/If Action Subsystem1/Selector1
               # combined # Selector: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_
               AC_runBeltFunctionSelection/For Iterator Subsystem/If Action Subsystem1/Selector
               # combined # BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBelt
               FunctionSelection/For Iterator Subsystem/Rescaler */
            if (NVP_au8BeltFctPriorities[(uint8) Sa4_For_Iterator_it] >
             NVP_au8BeltFctPriorities[u8LocPrevSelectedCycle]) {
               /* Switch: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFu
                  nctionSelection/For Iterator Subsystem/If Action Subsystem1/Switch
                  # combined # Reference of merge block: Merge BFS_AC_BeltFunctionSelection/BFS_AC_B
                  eltFunctionSelection/BFS_AC_runBeltFunctionSelection/For Iterator Subsystem/Merge
                  update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunc
                  tionSelection/BFS_AC_runBeltFunctionSelection/For Iterator
                  Subsystem/If Action
                  Subsystem1/Switch
                  # combined # BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runB
                  eltFunctionSelection/For Iterator Subsystem/Rescaler
                  # combined # Unit delay: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection
                  /BFS_AC_runBeltFunctionSelection/For Iterator Subsystem/Unit Delay */
               X_u8LocalSelectedCycle = (uint8) Sa4_For_Iterator_it;
            }
            else {
               /* Switch: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runBeltFu
                  nctionSelection/For Iterator Subsystem/If Action Subsystem1/Switch
                  # combined # Reference of merge block: Merge BFS_AC_BeltFunctionSelection/BFS_AC_B
                  eltFunctionSelection/BFS_AC_runBeltFunctionSelection/For Iterator Subsystem/Merge
                  update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunc
                  tionSelection/BFS_AC_runBeltFunctionSelection/For Iterator
                  Subsystem/If Action
                  Subsystem1/Switch
                  # combined # Unit delay: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection
                  /BFS_AC_runBeltFunctionSelection/For Iterator Subsystem/Unit Delay */
               X_u8LocalSelectedCycle = u8LocPrevSelectedCycle;
            }
         }
         else {
            /* Reference of merge block: Merge BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelec
               tion/BFS_AC_runBeltFunctionSelection/For Iterator Subsystem/Merge
               update of variable(s) associated with BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctio
               nSelection/BFS_AC_runBeltFunctionSelection/For Iterator
               Subsystem/If Action
               Subsystem2/In1
               # combined # Unit delay: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BF
               S_AC_runBeltFunctionSelection/For Iterator Subsystem/Unit Delay */
            X_u8LocalSelectedCycle = u8LocPrevSelectedCycle;
         }
      }
   }

   /* # combined # TargetLink outport: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS
      _AC_runBeltFunctionSelection/DSP_psrSelect__u8CycleNumber
      # combined # Unit delay: BFS_AC_BeltFunctionSelection/BFS_AC_BeltFunctionSelection/BFS_AC_runB
      eltFunctionSelection/For Iterator Subsystem/Unit Delay */
   Rte_Write_psrSelectedCycle_u8CycleNumber(X_u8LocalSelectedCycle);
}

#define BFS_AC_BeltFunctionSelection_STOP_SEC_CODE
#include "BFS_AC_BeltFunctionSelection_MemMap.h"

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* BFS_BELTFUNCTIONSELECTION_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
