/**************************************************************************************************\
 *** 
 *** Code generation unit : 
 *** Codefile             : common.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-24 11:22:57
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : enabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef COMMON_H
#define COMMON_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "tl_basetypes.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   MERGEABLE_MACRO: mergeable preprocessor macros
\******************************************************************************/
#define KS32_MAX ((sint32) 2147483647)
#define KS32_MIN ((sint32) -2147483647)
#define KS32_ZERO ((sint32) 0)

/******************************************************************************\
   MERGEABLE_MACRO: mergeable preprocessor macros
\******************************************************************************/
#define KS16_MAX ((sint16) 32767)
#define KS16_MIN ((sint16) -32767)
#define KS16_ZERO ((sint16) 0)
#define KU16_MAX ((uint16) 65535)
#define KU16_ZERO ((uint16) 0)

/******************************************************************************\
   MERGEABLE_MACRO: mergeable preprocessor macros
\******************************************************************************/
#define BFE_MIL_MBD ((uint8) 1)
#define B_FALSE ((uint8) 85)
#define B_TRUE ((uint8) 170)
#define KS8_ZERO ((sint8) 0)
#define KU8_FIVE ((uint8) 5)
#define KU8_FOUR ((uint8) 4)
#define KU8_MASK_BITS_2_7 ((uint8) 252)
#define KU8_MAX ((uint8) 255)
#define KU8_ONE ((uint8) 1)
#define KU8_SEVEN ((uint8) 7)
#define KU8_THREE ((uint8) 3)
#define KU8_TWO ((uint8) 2)
#define KU8_ZERO ((uint8) 0)

/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SIL_Data: Variable class | Width: 16
\******************************************************************************/
extern sint16 BoostPowerOrder;
extern sint16 MotorPowerOrder;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
#endif /* COMMON_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
