/**************************************************************************************************\
 *** 
 *** Code generation unit : 
 *** Codefile             : NVM_Param.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2012-07-09 17:24:32
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Efficient vector handling                : enabled
 *** Loop unroll threshold                    : 5
 *** Variable vector widths                   : enabled
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** No assignment of boolean expressions     : disabled
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : enabled
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 3.3\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 3.3\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CsourceCodeSS.xsl
 ***
 *** TargetLink version      : 3.3p1 from 18-Jan-2012
 *** Code generator version  : Build Id 3.3.0.63 from 2012-02-08 17:06:19
 *** Copyright (c) 2011 dSPACE GmbH
\**************************************************************************************************/

#ifndef NVM_PARAM_H
#define NVM_PARAM_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "tl_basetypes.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   Should_be_inEEPROM: global variables (RAM) | Width: 32
\******************************************************************************/
extern uint32 au32NvmCyclesCounters[17];

/******************************************************************************\
   Should_be_inEEPROM: global variables (RAM) | Width: 16
\******************************************************************************/
extern uint16 au16AdaptCurrentTempIdx[7] /* LSB: 2^-2 OFF:  0 MIN/MAX:  0 .. 16383.75 */;
extern uint16 au16CorrTargetOrderVolt[6];
extern uint16 au16NvmMRdxTemp[7] /* LSB: 2^-2 OFF:  0 MIN/MAX:  0 .. 16383.75 */;
extern uint16 au16NvmMotorResist[7];
extern uint16 au8NvmIdxTemp[7] /* LSB: 2^-2 OFF:  0 MIN/MAX:  0 .. 16383.75 */;
extern uint16 usNvmECUResistance /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 65535 */;

/******************************************************************************\
   Should_be_inEEPROM: global variables (RAM) | Width: 8
\******************************************************************************/
extern uint8 au8AdaptCurrentFactors[7];
extern uint8 au8CorrTargetOrder[6];
extern uint8 au8NvmDefinitionOfSteps[480];
extern uint8 au8NvmDescriptionOfAllCycles[204];
extern uint8 au8NvmReleaseWeight[7];
extern uint8 au8NvmTensionWeight[7];
extern uint8 b8HW_HP_Compatible /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern uint8 b8HW_PID_Compatible /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern uint8 b8NvmIsCompatibleHW_PID /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern uint8 u8NvmMaxCurrentOrder /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern uint8 u8NvmPID_Motor_D /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern uint8 u8NvmPID_Motor_I /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern uint8 u8NvmPID_Motor_P /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern uint8 u8NvmPID_Supply_D /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern uint8 u8NvmPID_Supply_I /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
extern uint8 u8NvmPID_Supply_P /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

#endif/*NVM_PARAM_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
