/*************************************************************************
                                                                          
AUTOLIV ELECTRONIC document.                                              
                                                                          
-------------------------------------                                     
                                                                          
DUPLICATION or DISCLOSURE PROHIBITED without prior written consent        
                                                                          
**************************************************************************
                                                                          
This file Nvp_Generated.c is generated by the Excel document SBE_4G_NVP_layout.xls
when using the "Generate All" Button
                                                                          
Date and time of generation of files:     1/20/2022 / 5:04:29 PM
 
COMPONENT NVP_GENERATED_C
 
Current revision: $Revision: 1.1.1.1 $
Checked in:       $Date: 2022/04/11 09:01:36CEST $
 
**************************************************************************
 
Overview of the component :
Part of the package NVP
<Component overview>
 
------------------------------------------------------------------------
 
Design document:
<Document reference>
 
*************************************************************************/
 
/*************************************************************************
Packages inclusion
*************************************************************************/
#include "Nvp_Generated.h"
 
/*************************************************************************
Intra-package inclusions
*************************************************************************/
/*************************************************************************
Private inclusion
*************************************************************************/
 
/*************************************************************************
Declaration of constants
*************************************************************************/
                                                                          
/*************************************************************************
Application Data
*************************************************************************/
 
VAR(NVP_BLOCK_ID_ECU_LOCATION_StorageType, NVP_VAR) NVP_BLOCK_ID_ECU_LOCATION_RamBlockData ;
 
VAR(NVP_BLOCK_ID_BELT_ASSEMBLY_MANUF_DATE_AND_SN_StorageType, NVP_VAR) NVP_BLOCK_ID_BELT_ASSEMBLY_MANUF_DATE_AND_SN_RamBlockData ;
 
VAR(NVP_BLOCK_ID_HB_CALIBRATION_StorageType, NVP_VAR) NVP_BLOCK_ID_HB_CALIBRATION_RamBlockData ;
 
VAR(NVP_BLOCK_ID_AEE_TRACEABILITY_StorageType, NVP_VAR) NVP_BLOCK_ID_AEE_TRACEABILITY_RamBlockData ;
 
VAR(NVP_BLOCK_ID_EXECUTION_COUNTERS_StorageType, NVP_VAR) NVP_BLOCK_ID_EXECUTION_COUNTERS_RamBlockData ;
 
VAR(NVP_BLOCK_ID_TESTS_PARAM_StorageType, NVP_VAR) NVP_BLOCK_ID_TESTS_PARAM_RamBlockData ;
 
VAR(NVP_BLOCK_ID_CYCLE_0_StorageType, NVP_VAR) NVP_BLOCK_ID_CYCLE_0_RamBlockData ;
 
VAR(NVP_BLOCK_ID_STEP_0_StorageType, NVP_VAR) NVP_BLOCK_ID_STEP_0_RamBlockData ;
 
/*********               END Application Data                    *********/
 
/*************************************************************************
Application Default Data
*************************************************************************/
 
CONST(NVP_BLOCK_ID_ECU_LOCATION_StorageType, NVP_CONST) NVP_BLOCK_ID_ECU_LOCATION_DefaultData  = {0U};
 
CONST(NVP_BLOCK_ID_BELT_ASSEMBLY_MANUF_DATE_AND_SN_StorageType, NVP_CONST) NVP_BLOCK_ID_BELT_ASSEMBLY_MANUF_DATE_AND_SN_DefaultData  = {0U};
 
CONST(NVP_BLOCK_ID_HB_CALIBRATION_StorageType, NVP_CONST) NVP_BLOCK_ID_HB_CALIBRATION_DefaultData  = {0U};
 
CONST(NVP_BLOCK_ID_AEE_TRACEABILITY_StorageType, NVP_CONST) NVP_BLOCK_ID_AEE_TRACEABILITY_DefaultData  = {0U};
 
CONST(NVP_BLOCK_ID_EXECUTION_COUNTERS_StorageType, NVP_CONST) NVP_BLOCK_ID_EXECUTION_COUNTERS_DefaultData  = {0U};
 
CONST(NVP_BLOCK_ID_TESTS_PARAM_StorageType, NVP_CONST) NVP_BLOCK_ID_TESTS_PARAM_DefaultData  = {0U};
 
CONST(NVP_BLOCK_ID_CYCLE_0_StorageType, NVP_CONST) NVP_BLOCK_ID_CYCLE_0_DefaultData  = {0U};
 
CONST(NVP_BLOCK_ID_STEP_0_StorageType, NVP_CONST) NVP_BLOCK_ID_STEP_0_DefaultData  = {0U};
 
/*********           Application Default Data                    *********/
 
/*************************************************************************
Calibration Data
*************************************************************************/
 
CONST(CALIB_BLOCK_ID_EOL_PARAM_StorageType, NVP_CONST) CALIB_BLOCK_ID_EOL_PARAM_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_BFS_PRIO_PARAM_StorageType, NVP_CONST) CALIB_BLOCK_ID_BFS_PRIO_PARAM_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_PID_PARAM_StorageType, NVP_CONST) CALIB_BLOCK_ID_PID_PARAM_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_WEIGHT_REL_TABLE_StorageType, NVP_CONST) CALIB_BLOCK_ID_WEIGHT_REL_TABLE_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_WEIGHT_TENS0_TABLE_StorageType, NVP_CONST) CALIB_BLOCK_ID_WEIGHT_TENS0_TABLE_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_WEIGHT_TENS1_TABLE_StorageType, NVP_CONST) CALIB_BLOCK_ID_WEIGHT_TENS1_TABLE_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_WEIGHT_TENS2_TABLE_StorageType, NVP_CONST) CALIB_BLOCK_ID_WEIGHT_TENS2_TABLE_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_WEIGHT_TENS3_TABLE_StorageType, NVP_CONST) CALIB_BLOCK_ID_WEIGHT_TENS3_TABLE_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_INT_CURRENT_CORR_StorageType, NVP_CONST) CALIB_BLOCK_ID_INT_CURRENT_CORR_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_INT_CURRENT_TABLE_StorageType, NVP_CONST) CALIB_BLOCK_ID_INT_CURRENT_TABLE_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_POWER_DEGRADATION_StorageType, NVP_CONST) CALIB_BLOCK_ID_POWER_DEGRADATION_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_ECPL_ALPHA_TABLE_StorageType, NVP_CONST) CALIB_BLOCK_ID_ECPL_ALPHA_TABLE_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_ECPL_BETA_TABLE_StorageType, NVP_CONST) CALIB_BLOCK_ID_ECPL_BETA_TABLE_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_ECPL_OTHER_PARAM_StorageType, NVP_CONST) CALIB_BLOCK_ID_ECPL_OTHER_PARAM_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_BPA_MOTOR_CURRENT_StorageType, NVP_CONST) CALIB_BLOCK_ID_BPA_MOTOR_CURRENT_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_VOLT_THRS_StorageType, NVP_CONST) CALIB_BLOCK_ID_VOLT_THRS_RomBlockData  = {9000U, 9500U, 9000U, 9500U, 16000U, 15500U, 16000U, 15500U, 8300U, 8800U, 17500U, 8000U, 4000U, 9000U};
 
CONST(CALIB_BLOCK_ID_BATTERY_LOSS_DETECTION_THRS_StorageType, NVP_CONST) CALIB_BLOCK_ID_BATTERY_LOSS_DETECTION_THRS_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_BOOST_StorageType, NVP_CONST) CALIB_BLOCK_ID_BOOST_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_ECU_PROPERTIES_StorageType, NVP_CONST) CALIB_BLOCK_ID_ECU_PROPERTIES_RomBlockData  = {40U, 327U, 5U, 1024U, 4000U};
 
CONST(CALIB_BLOCK_ID_SW_SELF_PROTECTION_THRS_StorageType, NVP_CONST) CALIB_BLOCK_ID_SW_SELF_PROTECTION_THRS_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_MOTOR_RESIST_PARAM_StorageType, NVP_CONST) CALIB_BLOCK_ID_MOTOR_RESIST_PARAM_RomBlockData  = {0U};
 
CONST(CALIB_BLOCK_ID_BOOST_ACTIVATION_StorageType, NVP_CONST) CALIB_BLOCK_ID_BOOST_ACTIVATION_RomBlockData  = {0U};
 
/*********               END Calibration Data                    *********/
 
 
/*************************************************************************
Declaration of macros
*************************************************************************/
 
/*************************************************************************
Declaration of types
*************************************************************************/
 
/*************************************************************************
LOCAL variables declaration
*************************************************************************/
 
/*************************************************************************
LOCAL constant data declaration
**************************************************************************/
 
/*************************************************************************
EXPORTED variables declaration
*************************************************************************/
 
/*************************************************************************
EXPORTED constant data declaration
**************************************************************************/
 
/**************************************************************************
Private Functions
**************************************************************************/
 
/**************************************************************************
Exported Functions
**************************************************************************/
 
/*************************************************************************
Evolution of the component
 
Created by: C.Sauvage
Updated by: R. Cristoi
 
$Log: Nvp_Tessy_Stubs.c  $
Revision 1.1.1.1 2022/04/11 09:01:36CEST Septimiu Vintila (septimiu.vintila) 
Temperature and KL30 voltage related thresholds updated.Temperature and KL30 voltage related thresholds updated.
Revision 1.1 2022/02/15 13:43:35EET Alexandru Paval (alexandru.paval) 
Initial revision
Member added to project e:/MKSProjects/SBE/PP/DAIMLER_MMA/Phase_02/View_Development/Tools/Tessy/Workspace/Stubs/project.pj
Revision 1.3.2.4 2022/01/21 10:11:56EET Emanuel Jivan (emanuel.jivan) 
Changed NVP_BLOCK_ID_BELT_ASSEMBLY_MANUF_DATE_AND_SN size to 28 bytes.


*************************************************************************/
 
/* end of file */
 
