/**************************************************************************************************\
 *** 
 *** Simulink model       : PRE_TestHarness
 *** TargetLink subsystem : PRE_TestHarness/PRE_AC_PreTensioning
 *** Codefile             : PRE_PreTensioningAlgo.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-25 18:04:59
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef PRE_PRETENSIONINGALGO_H
#define PRE_PRETENSIONINGALGO_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   UserSLGlobal: SLGlobal = { GLOBAL_ASR4 } | Width: 8
\******************************************************************************/
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern sint8 Sa22_For_Iterator_it;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern uint8 Sa23_Rescaler;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern uint8 Sa23_Selector;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern uint8 Sa23_Selector1;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern b8IsCarAccelerationLowType b8IsCarAccelerationLow_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern b8BooleanType b8EndOfCriticalSituation_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern b8IsCarCrashDetectedType b8IsCarCrashDetected_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern uint8 b8NewInterruptFlag;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern uint8 b8NewPreActivationFlag;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern uint8 b8NewPreConditionsFlag;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern uint8 b8NewTriggeringOrder;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern uint8 b8NewTriggeringSource_PRE;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern b8BooleanType b8PreCrashRequestEnable_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern boolean bDetectEndDiagRequest_PRE;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern boolean bDiagRequest_PRE;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8ModeStatusType bModeStatus_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8ModeStatusType bModeStatus_b; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8ModeStatusType bModeStatus_c; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8ModeStatusType bModeStatus_d; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8ModeStatusType bModeStatus_e; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8AecStatusType pu8AecStatus_a;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8AecStatusType pu8AecStatus_b;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8AecStatusType pu8AecStatus_c;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8AecStatusType pu8AecStatus_d;
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8lBuckleSwitchStatusType u8BuckleSwitch_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8CycleNumberType u8CycleNumber_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8CycleNumberType u8DiagRequestCycle_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8PreCrashSeverityLevelType u8PreCrashSeverityLevel_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
   
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8TestResultType u8TestResult_a; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
#define PRE_AC_PreTensioning_START_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"
extern u8TestResultType u8TestResult_b; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */
#define PRE_AC_PreTensioning_STOP_SEC_VAR_UNSPECIFIED
#include "PRE_AC_PreTensioning_MemMap.h"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   ARRunnable4: Default function class for AUTOSAR runnables
\******************************************************************************/
#define PRE_AC_PreTensioning_START_SEC_CODE
#include "PRE_AC_PreTensioning_MemMap.h"

FUNC(void, PRE_AC_PreTensioning_CODE) PRE_runPreTensioning(void);

#define PRE_AC_PreTensioning_STOP_SEC_CODE
#include "PRE_AC_PreTensioning_MemMap.h"

#endif /* PRE_PRETENSIONINGALGO_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
