/**************************************************************************************************\
 *** 
 *** Simulink model       : BSR_TestHarness
 *** TargetLink subsystem : BSR_TestHarness/BSR_AC_BeltSlackReductionAlgo
 *** Codefile             : BSR_AC_BeltSlackReductionAlgo.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-25 10:39:07
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      BSR_AC_BeltSlackReductionAlgo
 *** Sa2                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo
 *** Sa3                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo
 *** Sa4                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/WriteSyste
 ***                          mContextOutputs
 *** Sa5                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/BSR disabled
 *** Sa6                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/BSR enabled
 *** Sa7                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/Dem_GetEventStatus
 *** Sa7                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/Dem_GetEventStatus1
 *** Sa7                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/Dem_GetEventStatus2
 *** Sa7                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/SCA_runCheckSystemContext1
 *** Sa7                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/SCA_runCheckSystemContext2
 *** Sa7                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/SCA_runCheckSystemContext3
 *** Sa7                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/SCA_runCheckSystemContext4
 *** Sa8                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation
 *** Sa9                      BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/BSR enabled/FctCommonBSRManageInputs
 *** Sa10                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 ***                          tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles
 *** Sa11                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctBuckle
 ***                          SwitchCycleDetection
 *** Sa12                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 ***                          LoopControlTrig
 *** Sa13                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctEvalua
 ***                          tePreActivationFlag_BSR
 *** Sa14                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctManage
 ***                          BeltUnbuckledTimer 
 *** Sa15                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctBuckle
 ***                          SwitchCycleDetection/Acquite BSR Cycle detectedKeep First detection
 *** Sa16                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctBuckle
 ***                          SwitchCycleDetection/BSR cycle detectedAcquite First detection
 *** Sa17                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctBuckle
 ***                          SwitchCycleDetection/Keep previous values
 *** Sa18                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 ***                          LoopControlTrig/Loop Control Disabled
 *** Sa19                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 ***                          LoopControlTrig/Loop Control Enabled
 *** Sa20                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 ***                          LoopControlTrig/Loop Control Enabled/Loop control algo
 *** Sa21                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 ***                          LoopControlTrig/Loop Control Enabled/No loop control algo
 *** Sa22                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 *** LoopControlTrig/Loop Control Enabled/Loop control algo/Keep previous p
 ***                          ositionKeep previous Pay out condition
 *** Sa23                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 ***                          LoopControlTrig/Loop Control Enabled/Loop control algo/Keep values
 *** Sa24                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 *** LoopControlTrig/Loop Control Enabled/Loop control algo/No trig by loop
 ***                           control
 *** Sa25                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 *** LoopControlTrig/Loop Control Enabled/Loop control algo/Store the new p
 ***                          osition of te beltRemember the pay out condition has been filled
 *** Sa26                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 *** LoopControlTrig/Loop Control Enabled/Loop control algo/Store the posit
 ***                          ion of te beltRaz Pay out condition
 *** Sa27                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctDetect
 *** LoopControlTrig/Loop Control Enabled/Loop control algo/Trig by loop co
 ***                          ntrol
 *** Sa28                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctEvalua
 ***                          tePreActivationFlag_BSR/Acquite PreActivationFlagReset counter
 *** Sa29                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctEvalua
 ***                          tePreActivationFlag_BSR/No ActivationReset Counter
 *** Sa30                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctEvalua
 ***                          tePreActivationFlag_BSR/Set PreActivationFlagIncrement counter
 *** Sa31                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctManage
 ***                          BeltUnbuckledTimer /Increment counterCondition still false
 *** Sa32                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctManage
 ***                          BeltUnbuckledTimer /Reset counterReset condition
 *** Sa33                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRDetectActivation/FctManage
 ***                          BeltUnbuckledTimer /Stop incrementCondition becomes true
 *** Sa34                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRManageInputs/FctCheckCommo
 ***                          nAbortionConditionsFlagBSR
 *** Sa35                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRManageInputs/FctCheckCommo
 ***                          nPreConditionsFlagBSR
 *** Sa36                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRManageInputs/FctCheckUnder
 ***                          VoltageDuringTensioningForAllBSR
 *** Sa37                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRManageInputs/FctManageBelt
 ***                          BuckledTimer
 *** Sa38                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRManageInputs/FctManageBelt
 ***                          BuckledTimer/Increment counterCondition still false
 *** Sa39                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRManageInputs/FctManageBelt
 ***                          BuckledTimer/Reset counterReset condition
 *** Sa40                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRManageInputs/FctManageBelt
 ***                          BuckledTimer/Stop incrementCondition becomes true
 *** Sa41                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctAbortBS
 ***                          R
 *** Sa42                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R
 *** Sa43                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctAbortBS
 ***                          R/Check end diag request for BSR
 *** Sa44                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctAbortBS
 ***                          R/ToFormatFlag_bInterruptFlag_BSR
 *** Sa45                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctAbortBS
 ***                          R/Check end diag request for BSR/Acquite end of diag request
 *** Sa46                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctAbortBS
 ***                          R/Check end diag request for BSR/End of diag request
 *** Sa47                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctAbortBS
 ***                          R/Check end diag request for BSR/Memorize end of diag request
 *** Sa48                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctAbortBS
 ***                          R/ToFormatFlag_bInterruptFlag_BSR/If ActionSubsystem4
 *** Sa49                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctAbortBS
 ***                          R/ToFormatFlag_bInterruptFlag_BSR/If ActionSubsystem5
 *** Sa50                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/EvaluateDiagRequest
 *** Sa51                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/EvaluateTriggeringSource
 *** Sa52                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/ToFormatFlag_PreActivationFlag_BSR
 *** Sa53                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/ToFormatFlag_PreConditionsFlag_BSR
 *** Sa54                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/ToFormatFlag_TriggeringOrder_BSR
 *** Sa55                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/EvaluateDiagRequest/Acquite Diag Request From DIA
 *** Sa56                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 *** R/EvaluateDiagRequest/Acquite Diag Request From DIA/ClearDiagRequestCy
 ***                          cle
 *** Sa57                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/ToFormatFlag_PreActivationFlag_BSR/If ActionSubsystem2
 *** Sa58                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/ToFormatFlag_PreActivationFlag_BSR/If ActionSubsystem3
 *** Sa59                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/ToFormatFlag_PreConditionsFlag_BSR/If ActionSubsystem4
 *** Sa60                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/ToFormatFlag_PreConditionsFlag_BSR/If ActionSubsystem5
 *** Sa61                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/ToFormatFlag_TriggeringOrder_BSR/If ActionSubsystem
 *** Sa62                     BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBel
 *** tSlackReductionAlgo/BSR enabled/FctCommonBSRTrigAbortCycles/FctTriggBS
 ***                          R/ToFormatFlag_TriggeringOrder_BSR/If ActionSubsystem1
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef BSR_AC_BELTSLACKREDUCTIONALGO_C
#define BSR_AC_BELTSLACKREDUCTIONALGO_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte.h"
#include "common.h"
#include "BSR_AC_BeltSlackReductionAlgo_ARfrm.h"
#include "BSR_AC_BeltSlackReductionAlgo.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 16
\******************************************************************************/
sint16 Sa1_GetBeltPayOut_deg;
sint16 Sa1_b8CyclesAbortedByMode;
sint16 Sa1_b8CyclesAbortedByMode_Ext;
sint16 Sa1_b8CyclesInhibitedByMode;
sint16 Sa1_b8CyclesInhibitedByMode_Ext;
sint16 Sa1_b8IsCarCrashDetected;
sint16 Sa1_u16VehicleVelocity;
sint16 Sa1_u8BeltSlackStatus;
sint16 Sa1_u8ExecutedCycle;
sint16 Sa1_u8RealBuckleSwitchStatus;
sint16 Sa1_u8RequestedCycle;
sint16 Sa1_u8Status_EndOfLife;
sint16 Sa1_u8Status_OverVoltage;
sint16 Sa1_u8Status_UVDuringTensioning;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: N.A.
\******************************************************************************/
struct BS_OP_Sa1_psrAlgoFlags_BSR Sa1_psrAlgoFlags_BSR;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      BSR_AC_BeltSlackReductionAlgo
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void BSR_AC_BeltSlackReductionAlgo(void)
{
   /* Data store write: BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/WriteSystemConte
      xtOutputs/Data Store Write8 */
   b8CyclesAbortedByModes_Ext = (uint8) Sa1_b8CyclesAbortedByMode_Ext;

   /* Data store write: BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/WriteSystemConte
      xtOutputs/Data Store Write7 */
   b8CyclesInhibitedByModes_Ext = (uint8) Sa1_b8CyclesInhibitedByMode_Ext;

   /* Data store write: BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/WriteSystemConte
      xtOutputs/Data Store Write6 */
   u8Status_EOL = (uint8) Sa1_u8Status_EndOfLife;

   /* Data store write: BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/WriteSystemConte
      xtOutputs/Data Store Write5 */
   u8Status_OVO = (uint8) Sa1_u8Status_OverVoltage;

   /* Data store write: BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/WriteSystemConte
      xtOutputs/Data Store Write3 */
   u8Status_UVT = (uint8) Sa1_u8Status_UVDuringTensioning;

   /* Data store write: BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/WriteSystemConte
      xtOutputs/Data Store Write2 */
   b8CyclesAbortedByModes = (uint8) Sa1_b8CyclesAbortedByMode;

   /* Data store write: BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/WriteSystemConte
      xtOutputs/Data Store Write1 */
   b8CyclesInhibitedByModes = (uint8) Sa1_b8CyclesInhibitedByMode;

   /* update(s) for inport BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBeltSl
      ackReductionAlgo/b8IsCarCrashDetected */
   Rte_BSR_AC_BeltSlackReduction_prrCustomerSpecific_b8IsCarCrashDetected = (uint8)
    Sa1_b8IsCarCrashDetected;

   /* update(s) for inport BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBeltSl
      ackReductionAlgo/s16BeltPayOut_mm */
   Rte_BSR_AC_Bel__eltPosition_deg = Sa1_GetBeltPayOut_deg;

   /* update(s) for inport BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBeltSl
      ackReductionAlgo/u16VehicleVelocityFiltered */
   Rte_BSR_AC_BeltSlackReduction_prrDriverControls_u16VehicleSpeed = (uint16)
    Sa1_u16VehicleVelocity;

   /* update(s) for inport BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBeltSl
      ackReductionAlgo/u8BeltSlackStatus */
   Rte_BSR_AC_BeltSlackReduction_prrCustomerSpecific_u8BeltSlackStatus = (uint8)
    Sa1_u8BeltSlackStatus;

   /* update(s) for inport BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBeltSl
      ackReductionAlgo/u8ExecutedCycle */
   Rte_BSR_AC_BeltSlackReduction_prrExecutedCycle_u8CycleNumber = (uint8) Sa1_u8ExecutedCycle;

   /* update(s) for inport BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBeltSl
      ackReductionAlgo/u8FilteredBuckleSwitchStatus */
   Rte_BSR_AC_BeltSlackReduction_prrBuckleDoorSwitch_u8BuckleSwitch = (uint8)
    Sa1_u8RealBuckleSwitchStatus;

   /* update(s) for inport BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBeltSl
      ackReductionAlgo/u8RequestedCycle */
   Rte_BSR_AC_Bel__iagRequestCycle = (uint8) Sa1_u8RequestedCycle;

   /* call of function: BSR_AC_BeltSlackReductionAlgo/BSR_AC_BeltSlackReductionAlgo/BSR_runBeltSlack
      ReductionAlgo */
   Task_BSR_runBe__ionAlgo_Wrapper();

   /* BusOutport: BSR_AC_BeltSlackReductionAlgo/psrAlgoFlags_BSR */
   Sa1_psrAlgoFlags_BSR.Sa1_b8TriggerFlag_BSR = (sint16)
    Rte_BSR_AC_BeltSlackReduction_psrAlgo_Flags_BSR_b8TriggerFlag;
   Sa1_psrAlgoFlags_BSR.Sa1_b8InterruptFlag_BSR = (sint16)
    Rte_BSR_AC_BeltSlackReduction_psrAlgo_Flags_BSR_b8InterruptFlag;
   Sa1_psrAlgoFlags_BSR.Sa1_b8PreActivationFlag_BSR = (sint16)
    Rte_BSR_AC_BeltSlackReduction_psrAlgo_Flags_BSR_b8PreActivationFlag;
   Sa1_psrAlgoFlags_BSR.Sa1_b8PreConditionsFlag_BSR = (sint16)
    Rte_BSR_AC_BeltSlackReduction_psrAlgo_Flags_BSR_b8PreConditionsFlag;
   Sa1_psrAlgoFlags_BSR.Sa1_u8TriggeringSource_BSR = (sint16)
    Rte_BSR_AC_BeltSlackReduction_psrAlgo_Flags_BSR_u8TriggeringSource;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* BSR_AC_BELTSLACKREDUCTIONALGO_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
