/**************************************************************************************************\
 *** 
 *** Simulink model       : BSR_TestHarness
 *** TargetLink subsystem : BSR_TestHarness/BSR_AC_BeltSlackReductionAlgo
 *** Codefile             : BSR_Config.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-04-25 10:39:07
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef BSR_CONFIG_H
#define BSR_CONFIG_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   MERGEABLE_MACRO: mergeable preprocessor macros
\******************************************************************************/
#define CFG_KU32_BSR_MASK_EXT_ABORTING_MODES ((uint32) 2)
#define CFG_KU32_BSR_MASK_EXT_INHIBITING_MODES ((uint32) 8)
#define CFG_KU32_BSR_MASK_INT_ABORTING_MODES ((uint32) 1)
#define CFG_KU32_BSR_MASK_INT_INHIBITING_MODES ((uint32) 4)

/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   BSR_Config_Calibration: Calibratable global variables, which are declared in a user-written heade
   r file | Width: 16
\******************************************************************************/
extern uint16 CAL_U16_BSR_ACQUITE_PRE_ACTIVATION_TIME; /* Description: lsb=10ms */
extern uint16 CAL_U16_BSR_BUCKLE_SWITCH_DEBOUNCE_TIME; /* Description: lsb=10ms */
extern uint16 CAL_U16_BSR_VEH_SPEED_THRS; /* Description: Vehicle speed threshold for Belt Parking c
   ycles */
extern uint16 CFG_KU16_DISABLE_BSR_ACTIVATION_TIMEOUT; /* Description: lsb=10ms */

/******************************************************************************\
   BSR_Config_Calibration: Calibratable global variables, which are declared in a user-written heade
   r file | Width: 8
\******************************************************************************/
extern uint8 CAL_B8_BSR_FCT_ENABLED; /* Description: Belt Parking functions availability */
extern uint8 CAL_B8_BSR_LOOP_CONTROL_ENABLED; /* Description: loop control enable */
extern uint8 CAL_U8_BSR_BELT_BUCKLED_DELAY; /* Description: lsb=10ms */
extern uint8 CAL_U8_BSR_LOOP_CONTROL_BELT_MISUSE_PAY_IN; /* Description: misuse thrs lsb=10 */
extern uint8 CAL_U8_BSR_LOOP_CONTROL_PAYIN_AFTER_OUT; /* Description: pay in thrs lsb=10 */
extern uint8 CAL_U8_BSR_LOOP_CONTROL_PAYOUT_THRS; /* Description: pay out thrs lsb=10 */
extern uint8 CFG_KU8_BSR_BELT_SLACK_REDUCTION_CYCLE_ID; /* Description: Smooth release */
extern uint8 CFG_KU8_BSR_HIGHEST_PRE_CYCLE_ID; /* Description: PRE 8 */

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
#endif /* BSR_CONFIG_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
