//full CPU load
const aCPU_Load_Test_Type = [1, 2, 3, 4, 6];
//test only certain tasks
// const aCPU_Load_Test_Type = [3];

const aConfigured_Test_Cases = [
'idle', nullFunc, idle, nullFunc,
// 'preBeltFunction', nullFunc, preBeltFunction, beltFunctionDelay,
// 'qualifyUVAec', nullFunc, qualifyUVAec, nullFunc,
// 'qualifyOVAec', nullFunc, qualifyOVAec, nullFunc,
// 'diagnosticBeltFunctionPRECycle', nullFunc, diagnosticBeltFunction1, beltFunctionDelay,
// 'diagnosticBeltFunctionPROCycle', nullFunc, diagnosticBeltFunction2, beltFunctionDelay,
'diagnosticServiceTest_1', nullFunc, diagnosticServiceTest_1, nullFunc,
'diagnosticServiceTest_2', nullFunc, diagnosticServiceTest_2, nullFunc,
'diagnosticServiceTest_3', nullFunc, diagnosticServiceTest_3, nullFunc,
'diagnosticServiceTest_4', nullFunc, diagnosticServiceTest_4, nullFunc,
'diagnosticServiceTest_5_1', nullFunc, diagnosticServiceTest_5, nullFunc,
'diagnosticServiceTest_5_2', nullFunc, diagnosticServiceTest_5, nullFunc,
'diagnosticServiceTest_5_3', nullFunc, diagnosticServiceTest_5, nullFunc,
'diagnosticServiceTest_5_4', nullFunc, diagnosticServiceTest_5, nullFunc,
'diagnosticServiceTest_5_5', nullFunc, diagnosticServiceTest_5, nullFunc,
'diagnosticServiceTest_5_6', nullFunc, diagnosticServiceTest_5, nullFunc,
'diagnosticServiceTest_5_7', nullFunc, diagnosticServiceTest_5, nullFunc,
'diagnosticServiceTest_5_8', nullFunc, diagnosticServiceTest_5, nullFunc,
'diagnosticServiceTest_5_9', nullFunc, diagnosticServiceTest_5, nullFunc,
'diagnosticServiceTest_5_10', nullFunc, diagnosticServiceTest_5, nullFunc,
// 'qualifyC40081DTC', nullFunc, qualifyC40081DTC, nullFunc,
// 'qualifyC40087DTC', nullFunc, qualifyC40087DTC, nullFunc,
'diagnosticServiceTestLockUnlock', nullFunc, diagnosticServiceTestLockUnlock, nullFunc,
// 'measurementFrameTransmission', nullFunc, measurementFrameTransmission, beltFunctionDelay,
];

const aSCH_Configuration = [
0, "SCM_runManageSystemContext",
1, "ADC_runManageFilters",
2, "MMG_runUpdateVbatStatus",
3, "ATM_runMainFunction",
4, "BFE_runExecuteStandardSteps",
5, "PAL_runMainFunction",
6, "NVP_runMainFunction",
7, "FEE_MainFunction",
8, "FLS_MainFunction",
9, "WDG_Refresh",
11, "COM_RX_MainFunction",
12, "COM_DCM_TM_MainFunction",
13, "COM_DCM_NL_MainFunction",
14, "COM_DCM_DTC_MainFunction",
15, "COM_DCM_DG_MainFunction",
16, "COM_TX_MainFunction",
18, "PRT_Refresh",
19, "CIL_runCANToAppli",
20, "MMG_runManageModeDelays",
21, "MMG_runUpdateModeStatus",
22, "ERH_runStoreEverQualifiedAECsToNVP",
23, "VDA_runMainFunction",
24, "PRE_runPreTensioning",
25, "PRO_runProductionCycles",
26, "SFR_runStandardFunctionRecovery",
27, "BFS_runBeltFunctionSelection",
28, "BFE_runScheduleStep",
29, "SCM_runMonitoreExecutedCycle",
30, "MMG_runComputeCalibrationData",
31, "EOL_runMainFunction",
32, "STM_runIncreaseSystemTime",
33, "CIL_runAppliToCAN",
34, "CIL_runMF24Logger",
35, "COM_NM_MainFunction",
36, "FLT_runMainFunction",
37, "FLT_runStoreEverQualifiedDTCsToNVP",
38, "ESM_MainFunction",
40, "PMP_runComputeDeficiencyLevel",
];