tracked_documents: [
"E5480777", # Daimler MMA EMC Test Plan
"E5574661", # Start Of Preparation SYS R1.1
"E5532511", # System Integration Summary Report
"E5530938", # System Qualification Summary Report
"E5505448", # Weekly Meeting
"E5505444", # EO_SYSQ
"E5505443", # SOP_SYS
"E5503052", # SOSysQ Document
"E5381364", # Increment SYS Integration Test Plan
"E5381363", # SYS Integration Test Plan
"E5381342", # Increment SYS Qualification Plan
"E5381341", # SYS Qualification Plan =============================
"E5461019", # System Architecture Daimler MMA
"E5528966", # Daimler MMA Requirements Management Plan
"E5493433", # DAI_MMA_SW_Reqs_R1.0_SRM
"E5439589", # DAI MMA SW Reqs R1.0 PRWB
"E5437329", # DAI_MMA_Sys_Reqs_R1.1_SysRM
"E5437310", # DAI_MMA_Sys_Cust_Reqs_R1.0_PRM
"E5432652", # DAI MMA Sys Reqs PRWB ===============================
"E5555474", # DAI MMA DV Electrical Test Plan
"E5574433", # Start Of Preparation SW R01.1
"E5530640", # Software Qualification Summary Report
"E5504772", # Meeting Minutes
"E5504775", # EOQ
"E5504768", # SOP Document
"E5503020", # SOQ Document
"E5502677", # SWQ Entry Exit Checklist
"E5381336", # Increment SW Qualification Plan
"E5381334", # SW Qualification Plan
"E5381328", # SW SYS Qualification Test Schedule ===================
"E5535406", # Software design and code template
"E5529403", # Daimler MMA SW Architecture Matrix
"E5519340", # Software Release Notes
"E5389757", # DAI MMA SW Reuse Strategy
"E5380553", # DAI MMA Software Project Schedule
"E5380519", # DAI MMA Software Development Plan ====================
"E5612356", # MSS Daimler Standards
"E5612063", # Customer Requirements Export for Production ==========
"E5315892", # Process Version Definition Daimler
"E5315891", # Quality LOP ==========================================
"E5606579", # Internal Process Audit - MAN3 - SW
"E5595150", # Internal Process Audit - SYS4 - System Integration Qual
"E5595120", # Internal Process Audit - SWE6 - Software Qualification
"E5595084", # Internal Process Audit - SYS5 - Qualification
"E5595013", # Internal Process Audit - SWE4
"E5558959", # Internal Process Audit_SUP1_Quality Assurance
"E5544623", # Internal Process Audit - SW2 - SW ARC
"E5540603", # Internal Process Audit - SWE3 - DD and Unit Construction
"E5533411", # Internal Process Audit - SYS2 - Req
"E5521607", # Internal Process Audit - SYS3
"E5521551", # Internal Process Audit - SWE1
"E5509253", # Internal Process Audit MAN3 - QUAL
"E5500360", # Internal Process Audit - MAN3 - SYS
"E5393169", # System_Software_Milestone
"E5383820", # Quality Metrics
"E5378394", # Quality Assurance Plan
"E5376231", # Planning Internal Audits Milestones ===================
"E5310442", # DAI MMA Kick-Off Presentation
"E5509453", # DAI MMA Project Org Chart Skills Training
"E5380506", # DAI MMA Project Members List
"E5380420", # DAI MMA Project Risk Control Plan
"E5275239", # DAI MMA Project Development Plan
"E5214242", # DAI MMA Feature Release Plan
"E5189095", # DAI MMA Project Schedule ==============================
"E5291537", # DAI MMA Electronics LOP
"E5216286", # DAI MMA LOP ===========================================
"E5542314", # TARA
"E5529464", # DAI_MMA_Cyber Security Plan
"E5529455", # E5529455_DAI_MMA_Cyber Security Concept
"E5528666", # DAI MMA_ CIA - Cybersecurity Interface Agreement
"E5461080", # Daimler Customer Delivery Form
"E5228831", # Customer requirements export
"E5189101", # DAI MMA CUstomer Timing Plan
"E5495469", # DAI MMA Configuration Management Plan
"E5321442", # Project Master Document

]

document_name: "Exxxxxxx DAIMLER MMA CM Items Status PLM"

# document_revision_type: "Last only"
document_revision_type: "Last only"