from mod_functions import *

# keywords
mandatory, visible, visible_not_editable = ("mandatory", "visible", "visible_not_editable")

# command line
ptc_view_issue_cmd = '''im viewissue --hostname=ALVA-MKS03 --port=7001 --password=jnk01 --user=Jenkins01 {ptc_issue_id}'''

# command line
ptc_edit_issue_cmd = '''im editissue --hostname=ALVA-MKS03 --port=7001 --password=jnk01 --user=Jenkins01 {ptc_field_value} {ptc_issue_id}'''

# configuration options
ptc_im_commandline_fields = [
"Minor Version ID:",
"Major Version ID:",
"Live Item ID:",
"Bookmarks:",
"Backward Relationships:",
"Forward Relationships:",
"Type:",
"Summary:",
"State:",
"Project:",
"ID:",
"Modified By:",
"Created By:",
"Modified Date:",
"Created Date:",
"Issue Title:",
"Issue Type:",
"Customer visible:",
"Assignee SW:",
"Requirement ID:",
"Assignee TEST:",
"Verification_Validation:",
"Integration Date:",
"Keywords:",
"Restraints_Requirements_Traceability_Status:",
"Restraints_Design_Specification_Status:",
"Restraints_Code_Implementation_Peer_Review_Status:",
"Restraints_QAC_Analysis_Status:",
"Restraints_Unit_Test_Status:",
"Restraints_Requirements_Traceability_Comments:",
"Restraints_Design_Specification_Comments:",
"Restraints_QAC_Analysis_Comments:",
"Restraints_Unit_Test_Comments:",
"Assignee SW Due Date:",
"Assignee Integrator:",
"Restraints_Severity:",
"Restraints_Design_Specification_Effort_Est:",
"Restraints_QAC_Analysis_Effort_Est:",
"Restraints_Requirements_Traceability_Effort_Est:",
"Restraints_Unit_Test_Effort_Est:",
"Estimated Effort:",
"Assignee Analyze:",
"Analysis Due Date:",
"Restraints_Implementation_Complete (Old):",
"Restraints_Code_Implementation_Effort_Est:",
"Restraints_Requirements_Traceability_Effort_Actual:",
"Restraints_Design_Specification_Effort_Actual:",
"Restraints_Code_Implementation_Effort_Actual:",
"Restraints_QAC_Analysis_Effort_Actual:",
"Restraints_Unit_Test_Effort_Actual:",
"Actual Effort:",
"Restraints_Code_Implementation_Status:",
"Restraints_Code_Implementation_Comments:",
"Restraints_Validation_Change_Implementation_Effort_Est:",
"Restraints_Validation_Test_Execution_Effort_Est:",
"Restraints_Assignee_Analyze_Est:",
"Restraints_Assignee_Analyze_Actual:",
"Restraints_Assignee_Analyze_Status:",
"Age (days):",
"Restraints_Requirements_Traceability_Peer_Review_Status:",
"Restraints_Design_Specification_Peer_Review_Status:",
"Restraints_QAC_Analysis_Peer_Review_Status:",
"Restraints_Unit_Test_Peer_Review_Status:",
"Age Status:",
"Assignee Integrator Due Date:",
"Restraints_CCB_Comments:",
"Restraints_Description:",
"Add Container to Issue:",
"Add Candidate to Issue:",
"Release Container:",
"Release Candidate:",
"Restraints_Target_Software_Release:",
"Target Release Container:",
"Target Build Date:",
"Create or Add  Peer Reviews From Issue:",
"Create or Add  ALE Deviation From Issue:",
"Restraints_Assignee_Analyze_Complete_Date:",
"Restraints_Code_Implementation_Complete_Date:",
"Restraints_Code_Implementation_Peer_Review_Complete_Date:",
"Restraints_Design_Specification_Complete_Date:",
"Restraints_Design_Specification_Peer_Review_Complete_Date:",
"Restraints_QAC_Analysis_Complete_Date:",
"Restraints_QAC_Analysis_Peer_Review_Complete_Date:",
"Restraints_Requirements_Traceability_Complete_Date:",
"Restraints_Requirements_Traceability_Peer_Review_Complete_Date:",
"Restraints_Unit_Test_Complete_Date:",
"Restraints_Unit_Test_Peer_Review_Complete_Date:",
"Restraints_Validation_Change_Implementation_Complete_Date:",
"Restraints_Validation_Change_Implementation_Peer_Review_Complete_Date:",
"Restraints_Validation_Test_Execution_Complete_Date:",
"Restraints_Validation_Test_Execution_Peer_Review_Complete_Date:",
"Restraints_Days_In_State_Submitted:",
"Restraints_Days_In_State_To_Be_Analyzed:",
"Restraints_Days_In_State_Analyzed:",
"Restraints_Days_In_State_To_Be_Implemented:",
"Restraints_Days_In_State_Integrated:",
"Restraints_Days_In_State_Implemented:",
"Restraints_Days_In_State_To_Be_Verified:",
"Restraints_Days_In_State_Verified:",
"Restraints_Assignee_Validation:",
"Restraints_Overdue_Submitted:",
"Restraints_CONST_CCB_Interval:",
"Restraints_Overdue_Analyzed:",
"Restraints_Overdue_To_Be_Analyzed:",
"Restraints_Overdue_To_Be_Implemented:",
"Restraints_Overdue_Implemented:",
"Restraints_Overdue_Integrated:",
"Restraints_Overdue_To_Be_Verified:",
"Restraints_Overdue_Verified:",
"Restraints_Overdue_Issue:",
"Restraints_Days_In_State_Rejected:",
"Restraints_Days_In_State_Closed:",
"Restraints_Days_In_State_Postponed:",
"Restraints_CONST_Postponed_Overdue_Max:",
"Restraints_Overdue_Postponed:",
"Restraints_Overdue_Int:",
"Overdue:",
"Priority:",
"Assigned:",
"Restraints_SW_Val:",
"Restraints_Issue_is_Part_of_ISS:",
"Restraints_Integration_Date_Complete:",
"Restraints_Assignee_Analyze_Date_Complete:",
"Restraints_Implementation_Date_Complete:",
"Restraints_Issue_Date_Complete:",
"Restraints_Integration_Effort_Est:",
"Restraints_Integration_Effort_Act:",
"Restraints_CCB_Responsible:",
"Create or Add Action Item From Issue:",
"Restraints_Global_Issue_Boolean:",
"Currently Assigned To:",
"Restraints_Daimler_Status:",
"Restraints_Issue_Found_HWVersion:",
"Restraints_Daimler_Model:",
"Restraints_Issue_Found_SWVersion:",
"Restraints_Customer_Targetfix_Release:",
"Restraints_Integration_Planned_Week:",
"Restraints_Filtered_Release:",
"Restraints_Assignee_Analyze_Planned_Start_Date:",
"Restraints_Assignee_Requirements_Planned_Start_Date:",
"Restraints_Assignee_Design_Planned_Start_Date:",
"Restraints_Assignee_Code_Planned_Start_Date:",
"Restraints_Assignee_QAC_Planned_Start_Date:",
"Restraints_Assignee_Unit_Test_Planned_Start_Date:",
"Member Move:",
"Restraints_Daimler_Model_Show_Label_Mandatory_No:",
"Restraints_Daimler_RejectReason:",
"Restraints_Issue_Current_Effort_Est:",
"Restraints_Issue_Current_Effort_Actual:",
"Restraints_Overall_Effort_Est:",
"Restraints_Overall_Effort_Actual:",
"Restraints_IA_ReqSpec_Archi:",
"Restraints_IA_ReqSpec_Design:",
"Restraints_IA_ReqSpec_SWVer:",
"Restraints_IA_UserInter_Archi:",
"Restraints_IA_Interface_Archi:",
"Restraints_IA_FuncDescC_Archi:",
"Restraints_IA_FuncDescS_Archi:",
"Restraints_IA_Dynamic_Archi:",
"Restraints_IA_DataDef_Design:",
"Restraints_IA_LogicDesc_Design:",
"Restraints_IA_Logic_Code:",
"Restraints_IA_Compute_Code:",
"Restraints_IA_Implem_Code:",
"Restraints_IA_Comments_Code:",
"Restraints_IA_Nominal_UT:",
"Restraints_IA_Nominal_IT:",
"Restraints_IA_Robust_UT:",
"Restraints_IA_Robust_IT:",
"Restraints_IA_Endurance_IT:",
"Restraints_IA_Qualif_IT:",
"Restraints_IA_ScenTC_SWVer:",
"Restraints_IA_DevTools_UT:",
"Restraints_IA_DevTools_IT:",
"Restraints_IA_DevTools_SWVer:",
"Restraints_IA_ProcessCom_MiscOther:",
"Restraints_IA_ReqSpec_Req2:",
"Restraints_Issue_CP_Files_Updated:",
"Restraints_Issue_CP_Files_Dropped:",
"Restraints_Issue_CP_Files_Added:",
"Restraints_Issue_CP_Open:",
"Restraints_Issue_CP_Closed:",
"Restraints_Issue_CP_Days_Open:",
"Restraints_Issue_CP_Lines_Added:",
"Restraints_Issue_CP_Lines_Deleted:",
"Restraints_Daimler_Protocol_IIP2:",
"Customer Detection Date:",
"Customer Status:",
"Customer System Issue ID:",
"Customer Severity:",
"Customer Software Component:",
"Daimler Transition Counter:",
"Reject Reason:",
"Customer Device:",
"Restraint_Daimler_Protocol_XML_IIP2:",
"Restraints_Daimler_Protocol_DanTe_History_IIP2:",
"Restraints_Daimler_Protocol_Entry_IIP2:",
"Restraints_Issues_Current_Phase:",
"Restraints_Issue_Current_Phase_Status:",
"Customer_to_be _updated:",
"Restraints_Issue_CP_PR_Value:",
"Restraints_Issue_Customer_Item_Type:",
"Effort Estimation Information:",
"Restraints_Edit_All_Issues_Switch:",
"Peer Review Held:",
"Customer DefectMode:",
"Customer Author Name:",
"Customer Responsible Name:",
"Restraints_Customer_Reason:",
"Restraints_Issue_Associated_Meeting_Minutes:",
"Restraints_Daimler_Customer_CRL_Processed:",
"Restraints_Diamler_Customer_MultipleWorkflowParentID:",
"Restraints_Issue_Change_Scope_Area:",
"Restraints_Daimler_Is_IIP_exchanged:",
"Shared Attachments:",
"Start Date:",
"involved I-Step:",
"Backward ELE_Change_Request_Related_ALE_Issue:",
"Attachments:",
]


ptc_im_field_restrictions = {
    # {"(Submitted)", "(To Be Analyzed)", "(Analyzed)", "(To Be Implemented)", "(Implemented)", "(To Be Reviewed)", "(Reviewed)", "(To Be Verified)", "(Verified)", "(Closed)"},
    "Assignee Analyze": {
        "(To Be Analyzed)": mandatory,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": visible,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Assignee Analyze Due Date": {
        "(To Be Analyzed)": mandatory,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": visible,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Assignee Integrator": {  # for review
        "(To Be Reviewed)": mandatory,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Assignee Integrator Due Date": {  # for review
        "(To Be Reviewed)": mandatory,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Assignee SW": {
        "(To Be Implemented)": mandatory,
        "(Implemented)": visible,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Assignee SW Due Date": {
        "(To Be Implemented)": mandatory,
        "(Implemented)": visible,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_Assignee_Analyze_Actual": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": mandatory,
        "(To Be Implemented)": visible,
        "(Implemented)": visible,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_Assignee_Analyze_Est": {
        "(To Be Analyzed)": mandatory,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": visible,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_Requirements_Traceability_Effort_Est": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": mandatory,
        "(To Be Implemented)": visible_not_editable,
        "(Implemented)": visible_not_editable, # visible
        "(To Be Reviewed)": visible_not_editable, # visible
        "(Reviewed)": visible_not_editable, # visible
        "(To Be Verified)": visible_not_editable, # visible
        "(Verified)": visible_not_editable, # visible
        "(Closed)": visible_not_editable # visible
    },
    "Restraints_Requirements_Traceability_Effort_Actual": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_Code_Implementation_Effort_Actual": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_Code_Implementation_Effort_Est": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": mandatory,
        "(To Be Implemented)": visible_not_editable,
        "(Implemented)": visible_not_editable, # visible
        "(To Be Reviewed)": visible_not_editable, # visible
        "(Reviewed)": visible_not_editable, # visible
        "(To Be Verified)": visible_not_editable, # visible
        "(Verified)": visible_not_editable, # visible
        "(Closed)": visible_not_editable # visible
    },
    "Restraints_Design_Specification_Effort_Actual": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_Design_Specification_Effort_Est": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": mandatory,
        "(To Be Implemented)": visible_not_editable,
        "(Implemented)": visible_not_editable, # visible
        "(To Be Reviewed)": visible_not_editable, # visible
        "(Reviewed)": visible_not_editable, # visible
        "(To Be Verified)": visible_not_editable, # visible
        "(Verified)": visible_not_editable, # visible
        "(Closed)": visible_not_editable # visible
    },
    "Restraints_Integration_Effort_Act": {
        "(To Be Reviewed)": visible,
        "(Reviewed)": mandatory,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_Integration_Effort_Est": {
        "(To Be Reviewed)": mandatory,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_QAC_Analysis_Effort_Actual": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_QAC_Analysis_Effort_Est": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": mandatory,
        "(To Be Implemented)": visible_not_editable,
        "(Implemented)": visible_not_editable, # visible
        "(To Be Reviewed)": visible_not_editable, # visible
        "(Reviewed)": visible_not_editable, # visible
        "(To Be Verified)": visible_not_editable, # visible
        "(Verified)": visible_not_editable, # visible
        "(Closed)": visible_not_editable # visible
    },
    "Restraints_Unit_Test_Effort_Actual": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_Unit_Test_Effort_Est": {
        "(To Be Analyzed)": visible,
        "(Analyzed)": mandatory,
        "(To Be Implemented)": visible_not_editable,
        "(Implemented)": visible_not_editable, # visible
        "(To Be Reviewed)": visible_not_editable, # visible
        "(Reviewed)": visible_not_editable, # visible
        "(To Be Verified)": visible_not_editable, # visible
        "(Verified)": visible_not_editable, # visible
        "(Closed)": visible_not_editable # visible
    },
    "State": {
        "(Submitted)": visible,
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": visible,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    "Restraints_CCB_Comments": {
        "(Submitted)": visible,
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": visible,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },

    'Restraints_Analysis': {
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": visible,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    'Restraints_Unit_Test_Status':{
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    'Restraints_QAC_Analysis_Status':{
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    'Restraints_Code_Implementation_Status':{
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    'Restraints_Design_Specification_Status':{
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
    'Restraints_Requirements_Traceability_Status':{
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },

    'Restraints_Target_Software_Release': {
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },

    'Restraints_Target_Release_Container': {
        "(To Be Analyzed)": visible,
        "(Analyzed)": visible,
        "(To Be Implemented)": visible,
        "(Implemented)": mandatory,
        "(To Be Reviewed)": visible,
        "(Reviewed)": visible,
        "(To Be Verified)": visible,
        "(Verified)": visible,
        "(Closed)": visible
    },
}

# used for defining optional formatting type
ptc_im_field_date_formatting = {
    "Assignee Analyze Due Date":  1,  # formatting type 1: Oct 16, 2020
    "Assignee Integrator Due Date": 1,  # formatting type 1: Oct 16, 2020
    "Assignee SW Due Date": 1,  # formatting type 1: Oct 16, 2020
}

# used for defining a formatting option for IM Edit Item
ptc_im_ei_field_dispatch_formatting = {
    "Assignee Analyze": format_team_member_name_for_ptc_ei,
    "Assignee Analyze Due Date": format_date_time,
    "Assignee Integrator": format_team_member_name_for_ptc_ei,
    "Assignee Integrator Due Date": format_date_time,
    "Assignee SW": format_team_member_name_for_ptc_ei,
    "Assignee SW Due Date": format_date_time,
    "Restraints_Assignee_Analyze_Actual": format_duration_to_hrs,
    "Restraints_Assignee_Analyze_Est": format_duration_to_hrs,
    "Restraints_Integration_Effort_Est": format_duration_to_hrs,
    "Restraints_Integration_Effort_Act": format_duration_to_hrs,
    "Restraints_Requirements_Traceability_Effort_Est": format_duration_to_hrs,
    "Restraints_Requirements_Traceability_Effort_Actual": format_duration_to_hrs,
    'Restraints_Code_Implementation_Effort_Actual': format_duration_to_hrs,
    'Restraints_Code_Implementation_Effort_Est': format_duration_to_hrs,
    'Restraints_QAC_Analysis_Effort_Est': format_duration_to_hrs,
    'Restraints_QAC_Analysis_Effort_Actual': format_duration_to_hrs,
    'Restraints_Design_Specification_Effort_Est': format_duration_to_hrs,
    'Restraints_Design_Specification_Effort_Actual': format_duration_to_hrs,
    'Restraints_Unit_Test_Effort_Actual': format_duration_to_hrs,
    'Restraints_Unit_Test_Effort_Est': format_duration_to_hrs,

}

# used for defining a formatting option for IM View Item
ptc_im_vi_field_dispatch_formatting = {
    "Assignee Analyze": format_team_member_name_for_ptc_vi,
    "Assignee Integrator": format_team_member_name_for_ptc_vi,
    "Assignee SW": format_team_member_name_for_ptc_vi,
    "Restraints_Assignee_Analyze_Actual": format_duration_to_hrs,
    "Restraints_Assignee_Analyze_Est": format_duration_to_hrs,
    "Restraints_Integration_Effort_Est": format_duration_to_hrs,
    "Restraints_Integration_Effort_Act": format_duration_to_hrs,
    "Restraints_Requirements_Traceability_Effort_Est": format_duration_to_hrs,
    "Restraints_Requirements_Traceability_Effort_Actual": format_duration_to_hrs,
    'Restraints_Code_Implementation_Effort_Actual': format_duration_to_hrs,
    'Restraints_Code_Implementation_Effort_Est': format_duration_to_hrs,
    'Restraints_QAC_Analysis_Effort_Est': format_duration_to_hrs,
    'Restraints_QAC_Analysis_Effort_Actual': format_duration_to_hrs,
    'Restraints_Design_Specification_Effort_Est': format_duration_to_hrs,
    'Restraints_Design_Specification_Effort_Actual': format_duration_to_hrs,
    'Restraints_Unit_Test_Effort_Actual': format_duration_to_hrs,
    'Restraints_Unit_Test_Effort_Est': format_duration_to_hrs,

#
}

# used for defining a function to compare and restrict field content
ptc_im_vi_field_dispatch_comparison = {
    "Restraints_Analysis": compare_analysis,
}

# used for converting mpp column name to ptc field name
mpp_to_ptc_field_mapping = {
    "State": "State",
    "Description": 'Restraints_Analysis',
    "Finish - Analysis": "Assignee Analyze Due Date",
    "Finish - Review": "Assignee Integrator Due Date",
    "Finish - Requirements": "Assignee SW Due Date",
    "Finish - Architecture": "Assignee SW Due Date",
    "Finish - Design": "Assignee SW Due Date",
    "Finish - Integration": "Assignee SW Due Date",
    "Finish - Implementation": "Assignee SW Due Date",
    "Finish - QAC": "Assignee SW Due Date",
    "Finish - Unit": "Assignee SW Due Date",
    "Resource Names - Analysis": "Assignee Analyze",
    "Resource Names - Review": "Assignee Integrator",
    "Resource Names - Requirements": "Assignee SW",
    "Resource Names - Architecture": "Assignee SW",
    "Resource Names - Design": "Assignee SW",
    "Resource Names - Integration": "Assignee SW",
    "Resource Names - Implementation": "Assignee SW",
    "Resource Names - QAC": "Assignee SW",
    "Resource Names - Unit": "Assignee SW",
    "Duration Act - Analysis": "Restraints_Assignee_Analyze_Actual",
    "Duration Est - Analysis": "Restraints_Assignee_Analyze_Est",
    "Duration Est - Review": "Restraints_Integration_Effort_Est",
    "Duration Act - Review": "Restraints_Integration_Effort_Act",
    "Requirements_Est_Effort": "Restraints_Requirements_Traceability_Effort_Est",
    "Requirements_Act_Effort": "Restraints_Requirements_Traceability_Effort_Actual",
    'Requirements_Status': 'Restraints_Requirements_Traceability_Status',
    'Implementation_Act_Effort': "Restraints_Code_Implementation_Effort_Actual",
    'Implementation_Status': 'Restraints_Code_Implementation_Status',
    'Implementation_Est_Effort': "Restraints_Code_Implementation_Effort_Est",
    'QAC_Est_Effort': "Restraints_QAC_Analysis_Effort_Est",
    'QAC_Act_Effort': "Restraints_QAC_Analysis_Effort_Actual",
    'QAC_Status': 'Restraints_QAC_Analysis_Status',
    'Design_Status': 'Restraints_Design_Specification_Status',
    'Design_Est_Effort': "Restraints_Design_Specification_Effort_Est",
    'Design_Act_Effort': "Restraints_Design_Specification_Effort_Actual",
    'UnitTest_Act_Effort': "Restraints_Unit_Test_Effort_Actual",
    'UnitTest_Est_Effort': "Restraints_Unit_Test_Effort_Est",
    'UnitTest_Status': 'Restraints_Unit_Test_Status',
    'Restraints_Target_Release_Container': 'Restraints_Target_Release_Container',
    'Restraints_Target_Software_Release': 'Restraints_Target_Software_Release',
    # 'Architecture_Est_Effort': "???",
    # 'Architecture_Act_Effort': "???",
    # 'Architecture_Status': "???",
    # 'Integration_Est_Effort': "???",
    # 'Integration_Act_Effort': "???",
    # 'Integration_Status': "???",
}

# used for converting command line field name to field name that you see in IM
ptc_real_to_view_value_mapping = {
    "State": "State",
    "Restraints_Analysis": 'Restraints_Description',
    "Assignee Analyze": "Assignee Analyze",
    "Assignee Analyze Due Date": "Analysis Due Date",
    "Assignee Integrator": "Assignee Integrator",
    "Assignee Integrator Due Date": "Assignee Integrator Due Date",
    "Assignee SW": "Assignee SW",
    "Assignee SW Due Date": "Assignee SW Due Date",
    "Restraints_Assignee_Analyze_Actual": "Restraints_Assignee_Analyze_Actual",
    "Restraints_Assignee_Analyze_Est": "Restraints_Assignee_Analyze_Est",
    "Restraints_Requirements_Traceability_Effort_Est": "Restraints_Requirements_Traceability_Effort_Est",
    "Restraints_Requirements_Traceability_Effort_Actual": "Restraints_Requirements_Traceability_Effort_Actual",
    'Restraints_Requirements_Traceability_Status': 'Restraints_Requirements_Traceability_Status',
    "Restraints_Design_Specification_Effort_Est": "Restraints_Design_Specification_Effort_Est",
    "Restraints_Design_Specification_Effort_Actual": "Restraints_Design_Specification_Effort_Actual",
    'Restraints_Design_Specification_Status': 'Restraints_Design_Specification_Status',
    "Restraints_Code_Implementation_Effort_Est": "Restraints_Code_Implementation_Effort_Est",
    "Restraints_Code_Implementation_Effort_Actual": "Restraints_Code_Implementation_Effort_Actual",
    'Restraints_Code_Implementation_Status': 'Restraints_Code_Implementation_Status',
    "Restraints_QAC_Analysis_Effort_Est": "Restraints_QAC_Analysis_Effort_Est",
    "Restraints_QAC_Analysis_Effort_Actual": "Restraints_QAC_Analysis_Effort_Actual",
    'Restraints_QAC_Analysis_Status': 'Restraints_QAC_Analysis_Status',
    "Restraints_Unit_Test_Effort_Est": "Restraints_Unit_Test_Effort_Est",
    "Restraints_Unit_Test_Effort_Actual": "Restraints_Unit_Test_Effort_Actual",
    'Restraints_Unit_Test_Status': 'Restraints_Unit_Test_Status',
    "Restraints_Integration_Effort_Est": "Restraints_Integration_Effort_Est",
    "Restraints_Integration_Effort_Act": "Restraints_Integration_Effort_Act",
    'Restraints_Target_Release_Container': 'Target Release Container',
    'Restraints_Target_Software_Release': 'Restraints_Target_Software_Release',

}
