# ============================================================
#         CONFIG FILE FOR RUN TEST DURING RELEASE TOOL
#   Written by: Ardeleanu Lucian
#   Date: 18 Nov. 2021
#   Copyright Autoliv, RBE, 2021
#   Status: Released
# ============================================================

# DO NOT DELETE NOWHERE ' ' CHARACHTERS!

# Define here path to tests, be sure not to define S: drive path
# DO NOT PLACE HERE S: DRIVE PATH, PLACE ONLY C: PATH WHERE PTC PROJECT IS
Path to tests: 'D:\jenkins\Jenkins\workspace\KPI_Manager\AUDI_TR6_Reports\Tests'

# Define here USERNAME and PASSWORD for PTC Account
PTC Username: 'Jenkins01'
PTC Password: 'jnk01'

# Write here Global path to si.exe ( if is not exist in bench )
# This paths are paths to PTC Engines
Path to si.exe: '"C:/Program Files (x86)/Integrity/ILMClient11/bin/si.exe" '
Path to im.exe: '"C:/Program Files (x86)/Integrity/ILMClient11/bin/im.exe" '

# Define here list of Release Containers to be compared.
List of release containers: [
"811603",
"811502",
"811036",
"810440",
"810192",
"810056",
"807745",
"807743",
"807684",
"807229",
"803823",
"803671",
"803670",
"801566",
"801564",
"800195",
]

# Write here test types to ignore
# All this test types are taken from S:/Tests folder
# Uncoment test type to ignore it
List of test types to ignore: [
# "Tests_Deliveries",
# "Tests_Integration",
# "Tests_Issues",
# "Tests_Qualification",
# "Tests_Verification_Qualification",
]

# Path to generated file with name and extension
# If only filename and extension is given, file will be generated right beside script!
File name and path: "Run_Test_During_Release_Generated_Report.xlsx"
